import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync, readFileSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outputDir = "output";

// Ensure output directory exists
if (prod && !existsSync(outputDir)) {
	mkdirSync(outputDir, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outputDir}/main.js`,
});

if (prod) {
	await context.rebuild();

	// Copy manifest.json and styles.css to output directory
	copyFileSync("manifest.json", `${outputDir}/manifest.json`);

	// Guard: manifest.json must not contain Chinese characters
	const manifestContent = readFileSync("manifest.json", "utf8");
	if (/[\u4e00-\u9fa5]/.test(manifestContent)) {
		console.error("❌ Build aborted: manifest.json contains Chinese characters. Please use English only.");
		process.exit(1);
	}

	if (existsSync("styles.css")) {
		copyFileSync("styles.css", `${outputDir}/styles.css`);
	}

	console.log(`Build complete. Output files in ${outputDir}/`);
	process.exit(0);
} else {
	await context.watch();
}