// Host surface that the extracted publish-modal sub-components depend on.
// The WpPublishModalV2 modal implements this interface and passes `this`
// into each component, so the components stay decoupled from the modal class.

import type WordpressPlugin from '../main';
import type { WordPressPostParams } from '../wp-types';
import type { FeaturedImageResult } from '../featured-image-modal';
import type { UnsplashService } from '../unsplash-service';
import type { AIService } from '../ai-service';
import type { MatterData } from '../types';
import type { Term } from '../wp-api';

export interface PublishModalContext {
  readonly plugin: WordpressPlugin;

  // ── Shared mutable state ──
  featuredImage: FeaturedImageResult | null;
  autoFeaturedImage: FeaturedImageResult | null;
  imageSource: 'local' | 'unsplash' | 'ai' | 'vault' | 'cached' | 'auto';
  titleInput: HTMLInputElement | null;
  slugInput: HTMLInputElement | null;
  lastAutoGeneratedSlug: string;
  publishBtn: HTMLButtonElement | null;
  matterData: MatterData;
  unsplashService: UnsplashService | null;
  aiService: AIService | null;
  categories: { items: Term[]; selected: number[] };
  isLoadingRemoteImage: boolean;
  remoteImageLoadFailed: boolean;
  remoteImageError: string | null;
  remoteImagePostId: string | number | null;

  // ── Actions (delegated back into the modal) ──
  display(params: WordPressPostParams): void;
  selectLocalFile(params: WordPressPostParams): void;
  selectVaultImage(params: WordPressPostParams): void;
  selectUnsplashImage(params: WordPressPostParams): void;
  generateFeaturedImage(params: WordPressPostParams): Promise<void>;
  loadRemoteFeaturedImage(postId: string | number, params: WordPressPostParams): Promise<void>;
  generateSummary(params: WordPressPostParams): Promise<void>;
  generateTags(params: WordPressPostParams): Promise<void>;
  generateDefaultSlug(title: string, params?: WordPressPostParams): void;
  setupDateMask(inputEl: HTMLInputElement, params: WordPressPostParams): void;
  doPublish(params: WordPressPostParams, btn?: HTMLButtonElement): void;
}
