// Settings sidebar of the V3 publish modal: the basic-settings card (title,
// slug, status, schedule, comments, format, categories, publish-as-new) and the
// collapsible history card. Extracted from WpPublishModalV2.

import type { WordPressPostParams } from '../wp-types';
import { PostStatus, CommentStatus } from '../wp-api';
import { SafeAny } from '../utils';
import { SlugGenerator } from '../slug-generator';
import { format } from 'date-fns';
import type { PublishModalContext } from './publish-modal-context';
import { addV3HintBtn, createV3Section, renderV3Field } from './v3-layout';

export class SettingsSidebar {
  constructor(private readonly ctx: PublishModalContext) {}

  render(container: HTMLElement, params: WordPressPostParams): void {
    this.renderSettingsCard(container, params);
    this.renderHistoryCard(container, params);
  }

  private renderSettingsCard(container: HTMLElement, params: WordPressPostParams): void {
    const ctx = this.ctx;
    const card = container.createDiv('wp-v3-settings-card');
    card.createDiv({
      cls: 'wp-v3-settings-card-title',
      text: ctx.plugin.t('publishModal_basicSettings') || 'Settings'
    });

    const body = card.createDiv('wp-v3-settings-body');

    // 标题
    renderV3Field(ctx, body, ctx.plugin.t('publishModal_titleName'), 'publishModal_titleInfo', (fieldEl) => {
      const input = fieldEl.createEl('input', { cls: 'wp-v3-input', type: 'text' });
      input.value = params.title || '';
      input.placeholder = ctx.plugin.t('publishModal_titlePlaceholder');
      ctx.titleInput = input;
      input.addEventListener('input', () => { params.title = input.value; });
      input.addEventListener('blur', () => {
        if (ctx.plugin.settings.autoGenerateSlug && ctx.slugInput) {
          if (!ctx.lastAutoGeneratedSlug || params.slug === ctx.lastAutoGeneratedSlug) {
            ctx.generateDefaultSlug(params.title, params);
            ctx.lastAutoGeneratedSlug = params.slug || '';
            if (ctx.slugInput) ctx.slugInput.value = params.slug || '';
          }
        }
      });
    });

    // Slug
    renderV3Field(ctx, body, ctx.plugin.t('publishModal_slugName'), 'publishModal_slugInfo', (fieldEl) => {
      const slugRow = fieldEl.createDiv();
      slugRow.style.display = 'flex';
      slugRow.style.gap = '6px';
      slugRow.style.alignItems = 'center';

      const input = fieldEl.createEl('input', { cls: 'wp-v3-input', type: 'text' });
      input.value = params.slug || '';
      input.placeholder = ctx.plugin.t('publishModal_slugPlaceholder');
      ctx.slugInput = input;
      const initialSlugValue = params.slug;
      input.addEventListener('input', () => {
        const sanitized = SlugGenerator.sanitizeSlug(input.value);
        params.slug = sanitized;
        if (sanitized && initialSlugValue && sanitized !== initialSlugValue) {
          ctx.lastAutoGeneratedSlug = '';
        }
      });
    });

    // 分隔线
    body.createDiv('wp-v3-divider');

    // 发布状态
    renderV3Field(ctx, body, ctx.plugin.t('publishModal_statusName'), 'publishModal_statusDesc', (fieldEl) => {
      const select = fieldEl.createEl('select', { cls: 'wp-v3-select' });
      [
        [PostStatus.Draft, ctx.plugin.t('publishModal_statusDraft')],
        [PostStatus.Publish, ctx.plugin.t('publishModal_statusPublish')],
        [PostStatus.Private, ctx.plugin.t('publishModal_statusPrivate')],
        [PostStatus.Future, ctx.plugin.t('publishModal_statusFuture')]
      ].forEach(([val, label]) => {
        const opt = select.createEl('option', { value: val, text: label });
        if (val === params.status) opt.selected = true;
      });
      select.addEventListener('change', () => {
        params.status = select.value as PostStatus;
        ctx.display(params);
      });
    });

    // 定时发布（仅 Future）
    if (params.status === PostStatus.Future) {
      renderV3Field(ctx, body, ctx.plugin.t('publishModal_postDateTimeName'), 'publishModal_postDateTimeDescFormat' as SafeAny, (fieldEl) => {
        const input = fieldEl.createEl('input', { cls: 'wp-v3-input', type: 'text' });
        input.value = format(new Date(), 'yyyy-MM-dd HH:mm:ss');
        this.ctx.setupDateMask(input, params);
      });
    } else {
      delete params.datetime;
    }

    // 评论
    renderV3Field(ctx, body, ctx.plugin.t('publishModal_commentName'), 'publishModal_commentDesc', (fieldEl) => {
      const select = fieldEl.createEl('select', { cls: 'wp-v3-select' });
      [
        [CommentStatus.Open, ctx.plugin.t('publishModal_commentOpen')],
        [CommentStatus.Closed, ctx.plugin.t('publishModal_commentClosed')]
      ].forEach(([val, label]) => {
        const opt = select.createEl('option', { value: val, text: label });
        if (val === params.commentStatus) opt.selected = true;
      });
      select.addEventListener('change', () => { params.commentStatus = select.value as CommentStatus; });
    });

    // 发布格式
    renderV3Field(ctx, body, ctx.plugin.t('publishModal_postTypeName'), 'publishModal_postTypeDesc', (fieldEl) => {
      const select = fieldEl.createEl('select', { cls: 'wp-v3-select' });
      [
        ['html', ctx.plugin.t('publishModal_formatHTML')],
        ['markdown', ctx.plugin.t('publishModal_formatMarkdown')]
      ].forEach(([val, label]) => {
        select.createEl('option', { value: val, text: label });
      });
      select.addEventListener('change', () => { (params as SafeAny).contentFormat = select.value; });
    });

    // 分类（始终显示）
    const getValidCategoriesV3 = () => ctx.categories.items.filter(it => it.name && it.name.trim());
    body.createDiv('wp-v3-divider');
    renderV3Field(ctx, body, ctx.plugin.t('publishModal_categoryName'), 'publishModal_categoryInfo', (fieldEl) => {
      const tagsWrap = fieldEl.createDiv();
      tagsWrap.style.display = 'flex';
      tagsWrap.style.flexWrap = 'wrap';
      tagsWrap.style.gap = '4px';

      // 默认选中"未分类"
      if (params.categories.length === 0) {
        const uncategorized = getValidCategoriesV3().find(it =>
          ['Uncategorized', '未分类', ctx.plugin.t('publishModal_uncategorized')].includes(it.name)
        );
        if (uncategorized) params.categories = [Number(uncategorized.id)];
      }

      const renderCats = () => {
        tagsWrap.empty();
        const validCategories = getValidCategoriesV3();

        // 已选分类标签
        params.categories.forEach(catId => {
          const cat = validCategories.find(c => Number(c.id) === catId);
          if (!cat) return;
          const tag = tagsWrap.createEl('span', { cls: 'wp-v3-tag-item' });
          tag.style.backgroundColor = 'var(--interactive-accent)';
          tag.style.fontSize = '11px';
          tag.createSpan({ text: cat.name });
          const removeBtn = tag.createEl('button', { cls: 'wp-v3-tag-delete-btn', text: '×' });
          removeBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            params.categories = params.categories.filter(id => id !== catId);
            renderCats();
          });
        });

        // 操作按钮行
        const btnRow = tagsWrap.createEl('span', { cls: 'wp-v3-cat-btn-row' });

        // 下拉框 — 从已有分类中选（始终显示）
        const available = validCategories.filter(cat => !params.categories.includes(Number(cat.id)));
        const select = btnRow.createEl('select', { cls: 'wp-v3-select' });
        select.style.width = 'auto';
        select.style.fontSize = '11px';
        select.createEl('option', { value: '', text: ctx.plugin.t('publishModal_selectCategory') || '选择分类...' });
        available.forEach(cat => select.createEl('option', { value: String(cat.id), text: cat.name }));
        select.addEventListener('change', () => {
          if (select.value) { params.categories.push(Number(select.value)); renderCats(); }
        });

        // 「增加」按钮 — 创建新分类（发布时在远端创建）
        const addBtn = btnRow.createEl('button', { cls: 'wp-v3-cat-add-btn', text: ctx.plugin.t('publishModal_addCategory') || '增加' });
        addBtn.addEventListener('click', () => {
          addBtn.style.display = 'none';
          const input = btnRow.createEl('input', { cls: 'wp-v3-input', type: 'text' });
          input.style.width = '80px';
          input.style.fontSize = '11px';
          input.placeholder = ctx.plugin.t('publishModal_newCategoryPlaceholder') || '新分类名称';
          const commit = () => {
            const name = input.value.trim();
            if (name) {
              const tempId = -(ctx.categories.items.length + 100 + params.categories.length);
              ctx.categories.items.push({ id: String(tempId), name, slug: name.toLowerCase().replace(/\s+/g, '-'), taxonomy: 'category', description: '', count: 0 });
              params.categories.push(tempId);
            }
            input.remove();
            addBtn.style.display = '';
            renderCats();
          };
          let v3CatCommitted = false;
          input.addEventListener('keydown', (e) => {
            if (e.key === 'Enter') { v3CatCommitted = true; commit(); }
            if (e.key === 'Escape') { v3CatCommitted = true; input.remove(); addBtn.style.display = ''; }
          });
          input.addEventListener('blur', () => { if (!v3CatCommitted) commit(); });
          input.focus();
        });
      };

      renderCats();
    });

    // 发布为新文章（仅当已有关联文章）
    if (ctx.matterData.postId) {
      body.createDiv('wp-v3-divider');
      const toggleRow = body.createDiv('wp-v3-toggle-row');
      const labelRow = toggleRow.createDiv('wp-v3-field-label-row');
      labelRow.createSpan({ text: ctx.plugin.t('publishModal_publishAsNewName'), cls: 'wp-v3-field-label' });
      addV3HintBtn(labelRow, ctx.plugin.t('publishModal_publishAsNewDesc'));

      const label = toggleRow.createEl('label', { cls: 'wp-v3-toggle' });
      const checkbox = label.createEl('input', { type: 'checkbox' });
      checkbox.checked = params.publishAsNew || false;
      checkbox.addEventListener('change', () => { params.publishAsNew = checkbox.checked; });
      label.createDiv('wp-v3-toggle-slider');
    }
  }

  private renderHistoryCard(container: HTMLElement, params: WordPressPostParams): void {
    const ctx = this.ctx;
    const card = container.createDiv('wp-v3-settings-card wp-v3-collapsible-card');
    card.addClass('is-collapsed'); // 默认折叠

    const titleRow = card.createDiv('wp-v3-settings-card-title wp-v3-card-title-clickable');
    titleRow.createSpan({ text: ctx.plugin.t('publishModal_historyPanel') || 'History' });
    const chevron = titleRow.createSpan({ cls: 'wp-v3-collapse-chevron', text: '▶' });

    const body = card.createDiv('wp-v3-settings-body wp-v3-collapsible-body');
    body.style.display = 'none'; // 默认隐藏

    const historyList = body.createDiv('wp-v3-history-list');
    historyList.createDiv({ cls: 'wp-v3-history-empty', text: ctx.plugin.t('publishModal_noHistory') || 'No history yet' });

    titleRow.addEventListener('click', () => {
      const collapsed = card.hasClass('is-collapsed');
      if (collapsed) {
        card.removeClass('is-collapsed');
        body.style.display = '';
        chevron.textContent = '▼';
      } else {
        card.addClass('is-collapsed');
        body.style.display = 'none';
        chevron.textContent = '▶';
      }
    });
  }
}
