import { Setting, Notice, TFile, requestUrl, setIcon, Menu } from 'obsidian';
import { toNumber } from 'lodash-es';
import { format, parse } from 'date-fns';
import IMask, { DynamicMaskType, InputMask } from 'imask';

import WordpressPlugin from './main';
import { WordPressPostParams } from './wp-client';
import { CommentStatus, PostStatus, PostType, PostTypeConst, Term } from './wp-api';
import { MatterData } from './types';
import { ConfirmCode, openConfirmModal } from './confirm-modal';
import { AbstractModal } from './abstract-modal';
import { SafeAny } from './utils';
import { SlugGenerator } from './slug-generator';
import { FeaturedImageResult, VaultImagePickerModal, UnsplashPickerModal, resizeFeaturedImage } from './featured-image-modal';
import { UnsplashService, UnsplashImage } from './unsplash-service';
import { AIService } from './ai-service';
import { AppState } from './app-state';
import { ImageCacheManager, CachedFeaturedImage } from './image-cache-manager';
import { createModuleLogger } from './utils/logger';
import { TagFormatter } from './tag-formatter';
import { getApiCapabilities, getApiLimitations, getApiRecommendation } from './api-capability';
import { TranslateKey } from './i18n';
import { FloatingPanel, createPanelContainer } from './components/floating-panel';
import { createBottomButtons, createBottomButtonsWithRetry, createEditIcon } from './components/bottom-buttons';
import {
    createFeaturedImageSection,
    createExcerptSection,
    createTagsSection,
    createArticlePreviewSection,
    PreviewSection
} from './components/preview-section';

const log = createModuleLogger('WpPublishModalV3');

/**
 * Tag colors - using CSS variables for theme support
 */
const TAG_COLORS = [
    'var(--wp-tag-color-1)',
    'var(--wp-tag-color-2)',
    'var(--wp-tag-color-3)',
    'var(--wp-tag-color-4)',
    'var(--wp-tag-color-5)',
    'var(--wp-tag-color-6)',
    'var(--wp-tag-color-7)',
    'var(--wp-tag-color-8)',
    'var(--wp-tag-color-9)',
];

/**
 * Get tag color based on name hash
 */
function getTagColor(tagName: string): string {
    const hash = tagName.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    return TAG_COLORS[hash % TAG_COLORS.length];
}

/**
 * Detect text language
 */
function detectLanguage(text: string): 'zh' | 'en' | 'other' {
    if (!text || text.length < 10) return 'en';
    const chineseChars = text.match(/[\u4e00-\u9fa5]/g);
    const chineseCount = chineseChars ? chineseChars.length : 0;
    const englishChars = text.match(/[a-zA-Z]/g);
    const englishCount = englishChars ? englishChars.length : 0;
    if (chineseCount > text.length * 0.3) return 'zh';
    if (englishCount > text.length * 0.4) return 'en';
    return 'other';
}

/**
 * Get localized prompt
 */
function getLocalizedPrompt(plugin: WordpressPlugin, language: 'zh' | 'en' | 'other', type: 'summary' | 'tags' | 'image'): string {
    if (type === 'summary' && plugin.settings.summaryPrompt) return plugin.settings.summaryPrompt;
    if (type === 'tags' && plugin.settings.tagsPrompt) return plugin.settings.tagsPrompt;
    if (type === 'image' && plugin.settings.imageGenerationPrompt) return plugin.settings.imageGenerationPrompt;

    if (language === 'en' || language === 'other') {
        if (type === 'summary') return plugin.t('defaultPrompt_summaryEn');
        if (type === 'tags') return plugin.t('defaultPrompt_tagsEn');
        return plugin.t('defaultPrompt_imageEn');
    }

    if (type === 'summary') return plugin.t('defaultPrompt_summary');
    if (type === 'tags') return plugin.t('defaultPrompt_tags');
    return plugin.t('defaultPrompt_image');
}

/**
 * Edit state for preview sections
 */
interface EditState {
    featuredImage: boolean;
    excerpt: boolean;
    tags: boolean;
    article: boolean;
}

/**
 * WordPress publish modal V3 - Preview-first layout with floating panels
 */
export class WpPublishModalV3 extends AbstractModal {
    // State
    private dateInputMask: InputMask<DynamicMaskType> | null = null;
    private featuredImage: FeaturedImageResult | null = null;
    private aiService: AIService | null = null;
    private unsplashService: UnsplashService | null = null;
    private slugInput: HTMLInputElement | null = null;
    private titleInput: HTMLInputElement | null = null;
    private editableContent: string = '';
    private autoFeaturedImage: FeaturedImageResult | null = null;
    private slugGenerated: boolean = false;
    private lastAutoGeneratedSlug: string = '';
    private isPublishing: boolean = false;
    private lastPublishParams: WordPressPostParams | null = null;
    private publishBtn: HTMLButtonElement | null = null;
    private imageCacheManager: ImageCacheManager;
    private notePath: string;
    private imageSource: 'local' | 'unsplash' | 'ai' | 'vault' | 'cached' | 'auto' = 'auto';
    private currentParams: WordPressPostParams | null = null;
    private editableTags: string[] = [];
    private tagsContainer: HTMLElement | null = null;
    private cachedFeaturedImageId: number | undefined;
    private isLoadingRemoteImage: boolean = false;
    private remoteImageLoadFailed: boolean = false;
    private remoteImagePostId: string | number | null = null;
    private remoteImageError: string | null = null;

    // New state for preview-first layout
    private editState: EditState = {
        featuredImage: false,
        excerpt: false,
        tags: false,
        article: false
    };
    private settingsPanelExpanded: boolean = true;
    private historyPanelExpanded: boolean = false;
    private mobilePanelVisible: boolean = false;
    private mobileActivePanel: 'settings' | 'history' = 'settings';

    // Panel references
    private settingsPanel: FloatingPanel | null = null;
    private historyPanel: FloatingPanel | null = null;

    // Getters for prompts
    private get imageGenerationPrompt(): string {
        return this.plugin.settings.imageGenerationPrompt || this.plugin.t('defaultPrompt_image');
    }
    private get summaryPrompt(): string {
        return this.plugin.settings.summaryPrompt || this.plugin.t('defaultPrompt_summary');
    }
    private get tagsPrompt(): string {
        return this.plugin.settings.tagsPrompt || this.plugin.t('defaultPrompt_tags');
    }

    constructor(
        readonly plugin: WordpressPlugin,
        private readonly categories: { items: Term[]; selected: number[] },
        private readonly postTypes: { items: PostType[]; selected: PostType },
        private readonly onSubmit: (
            params: WordPressPostParams,
            updateMatterData: (matter: MatterData) => void,
            featuredImage?: FeaturedImageResult
        ) => void,
        private readonly matterData: MatterData,
        private readonly articleContent: string = '',
        private readonly noteTitle: string = '',
        notePath: string = ''
    ) {
        super(plugin);
        log.info('Constructor called');

        this.imageCacheManager = new ImageCacheManager(plugin.app);
        this.notePath = notePath;

        if (plugin.settings.aiConfig) {
            this.aiService = new AIService(plugin.settings.aiConfig);
        }
        if (plugin.settings.unsplashAccessKey) {
            this.unsplashService = new UnsplashService(plugin.settings.unsplashAccessKey);
        }

        // Load featured image from cache
        if (matterData.postId) {
            this.loadFeaturePictureFromCache(matterData.postId);
        } else {
            this.loadCachedImage();
        }
    }

    // ==================== Image Loading Methods ====================
    // (Keep all existing image loading methods from V2)
    private async loadFeaturePictureFromCache(postId: string | number): Promise<void> {
        try {
            if (this.notePath) {
                const localCachedImage = await this.imageCacheManager.loadImage(this.notePath);
                if (localCachedImage) {
                    log.info('Found local cached image:', localCachedImage.fileName);
                    this.featuredImage = {
                        fileName: localCachedImage.fileName,
                        mimeType: localCachedImage.mimeType,
                        content: localCachedImage.content,
                        width: localCachedImage.width
                    };
                    this.imageSource = 'cached';
                    if (this.currentParams) this.display(this.currentParams);
                    return;
                }
            }

            const cached = this.plugin.featurePictureCacheManager.get(postId);
            if (cached) {
                log.info('Loading featured image from cache:', cached.url);
                this.cachedFeaturedImageId = cached.featuredImageId;
                await this.loadFeaturePictureFromUrl(cached.url);
                return;
            }
            log.info('No cached feature picture found for post:', postId);

            const remoteImage = await this.loadFeaturePictureFromRemote(postId);
            if (!remoteImage) {
                await this.loadCachedImage();
            }
        } catch (e) {
            log.error('Failed to load feature picture from cache:', e);
            await this.loadCachedImage();
        }
    }

    private async loadFeaturePictureFromRemote(postId: string | number): Promise<boolean> {
        try {
            log.info('Fetching featured image from remote WordPress:', postId);
            this.isLoadingRemoteImage = true;
            this.remoteImageLoadFailed = false;
            this.remoteImagePostId = postId;
            this.remoteImageError = null;

            if (this.currentParams) this.display(this.currentParams);

            const profile = this.plugin.settings.profiles.find(p => p.isDefault);
            if (!profile) {
                log.warn('No default profile found');
                this.remoteImageError = '未配置 WordPress 账号，请先在设置中配置';
                return false;
            }

            const { getWordPressClient } = await import('./wp-clients');
            const client = getWordPressClient(this.plugin, profile);
            if (!client || !('getPost' in client)) {
                log.warn('Client does not support getPost method');
                this.remoteImageError = '客户端不支持获取文章';
                return false;
            }

            const auth = {
                username: profile.username || null,
                password: profile.password || null
            };

            const post = await (client as SafeAny).getPost(postId, auth);
            if (!post) {
                log.info('Post not found on remote');
                return false;
            }

            const featuredImageId = post.featured_media;
            const featurePictureUrl = post._embedded?.['wp:featuredmedia']?.[0]?.source_url;

            if (!featurePictureUrl || !featuredImageId) {
                log.info('No featured image found on remote post');
                return false;
            }

            log.info('Found featured image on remote:', { featuredImageId, featurePictureUrl });

            await this.plugin.featurePictureCacheManager.set(postId, featurePictureUrl, featuredImageId);
            this.cachedFeaturedImageId = featuredImageId;
            await this.loadFeaturePictureFromUrl(featurePictureUrl);
            return true;
        } catch (e) {
            log.error('Failed to load featured image from remote:', e);
            this.remoteImageLoadFailed = true;
            const profile = this.plugin.settings.profiles.find(p => p.isDefault);
            const profileName = profile?.name || '默认配置';
            this.remoteImageError = `连接 ${profileName} 失败：${e instanceof Error ? e.message : String(e)}`;
            return false;
        } finally {
            this.isLoadingRemoteImage = false;
            if (this.currentParams) this.display(this.currentParams);
        }
    }

    private async loadFeaturePictureFromUrl(url: string): Promise<void> {
        try {
            log.info('Loading featured image from URL:', url);
            const response = await requestUrl({ url, method: 'GET' });
            const contentType = response.headers['content-type'];
            const mimeType = this.getMimeTypeFromResponse(contentType, url);
            const fileName = this.extractFileName(url);

            this.autoFeaturedImage = {
                fileName,
                mimeType,
                content: response.arrayBuffer,
                width: 1200
            };
            log.info('Successfully loaded featured image:', fileName);
            if (this.currentParams) this.display(this.currentParams);
        } catch (e) {
            log.info('Failed to load featured image from URL:', e);
            await this.loadCachedImage();
        }
    }

    private async loadCachedImage(): Promise<void> {
        if (!this.notePath) {
            await this.detectFirstImage();
            return;
        }

        try {
            const cachedImage = await this.imageCacheManager.loadImage(this.notePath);
            if (cachedImage) {
                log.info('Restored featured image from cache:', cachedImage.fileName);
                this.featuredImage = {
                    fileName: cachedImage.fileName,
                    mimeType: cachedImage.mimeType,
                    content: cachedImage.content,
                    width: cachedImage.width
                };
                this.imageSource = 'cached';
                if (this.currentParams) this.display(this.currentParams);
            } else {
                await this.detectFirstImage();
            }
        } catch (e) {
            log.info('Failed to load cached image:', e);
            await this.detectFirstImage();
        }
    }

    private async saveImageToCache(
        imageData: ArrayBuffer,
        fileName: string,
        mimeType: string,
        sourceType: 'local' | 'unsplash' | 'ai' | 'vault'
    ): Promise<void> {
        if (!this.notePath) return;
        try {
            await this.imageCacheManager.saveImage(this.notePath, imageData, fileName, mimeType, sourceType);
            log.info('Image saved to cache:', fileName);
        } catch (e) {
            log.error('Failed to save image to cache:', e);
        }
    }

    async clearImageCache(): Promise<void> {
        if (!this.notePath) return;
        try {
            await this.imageCacheManager.clearCache(this.notePath);
            log.info('Image cache cleared for:', this.notePath);
        } catch (e) {
            log.error('Failed to clear image cache:', e);
        }
    }

    getCachedFeaturedImageId(): number | undefined {
        return this.cachedFeaturedImageId;
    }

    private getMimeTypeFromResponse(contentType: string | null, url: string): string {
        if (contentType?.startsWith('image/')) return contentType.split(';')[0];
        const ext = url.split('.').pop()?.toLowerCase()?.split('?')[0];
        return this.getMimeType(ext || 'jpg');
    }

    private extractFileName(url: string): string {
        const urlParts = url.split('/');
        const lastPart = urlParts[urlParts.length - 1]?.split('?')[0];
        return (lastPart && lastPart.includes('.')) ? lastPart : 'featured-image.jpg';
    }

    private async detectFirstImage(): Promise<void> {
        try {
            const imagePath = this.extractFirstImagePath();
            if (!imagePath) {
                await this.loadEmptyImage();
                return;
            }
            if (imagePath.startsWith('http')) {
                await this.loadOnlineImage(imagePath);
            } else {
                await this.loadLocalImage(imagePath);
            }
            if (this.currentParams && this.autoFeaturedImage) {
                this.display(this.currentParams);
            }
        } catch (e) {
            log.info('Error detecting first image:', e);
            await this.loadEmptyImage();
        }
    }

    private extractFirstImagePath(): string | null {
        const content = this.articleContent || '';
        const imageRegex = /!\[.*?\]\((.*?)\)|!\[\[(.*?)(?:\|.*?)?\]\]/g;
        const match = imageRegex.exec(content);
        return match ? (match[1] || match[2]) : null;
    }

    private async loadLocalImage(imagePath: string): Promise<void> {
        const file = this.app.metadataCache.getFirstLinkpathDest(imagePath, this.noteTitle);
        if (file instanceof TFile) {
            const binaryContent = await this.app.vault.readBinary(file);
            this.autoFeaturedImage = {
                fileName: file.name,
                mimeType: this.getMimeType(file.extension.toLowerCase()),
                content: binaryContent,
                width: 1200
            };
            log.info('Auto-detected first image:', file.name);
            if (this.currentParams) this.display(this.currentParams);
        }
    }

    private async loadOnlineImage(imagePath: string): Promise<void> {
        try {
            const response = await fetch(imagePath);
            const arrayBuffer = await response.arrayBuffer();
            this.autoFeaturedImage = {
                fileName: `featured-${Date.now()}.jpg`,
                mimeType: 'image/jpeg',
                content: arrayBuffer,
                width: 1200
            };
            if (this.currentParams) this.display(this.currentParams);
        } catch (e) {
            log.info('Failed to download online image:', e);
        }
    }

    private async loadEmptyImage(): Promise<void> {
        try {
            const emptyFile = this.app.vault.getAbstractFileByPath('empty.png');
            if (emptyFile instanceof TFile) {
                const content = await this.app.vault.readBinary(emptyFile);
                this.autoFeaturedImage = {
                    fileName: 'empty.png',
                    mimeType: 'image/png',
                    content: content,
                    width: 1200
                };
            }
        } catch (e) {
            log.info('Could not load empty.png:', e);
        }
    }

    private getMimeType(extension: string): string {
        const mimeTypes: Record<string, string> = {
            'jpg': 'image/jpeg', 'jpeg': 'image/jpeg', 'png': 'image/png',
            'gif': 'image/gif', 'webp': 'image/webp'
        };
        return mimeTypes[extension.toLowerCase()] || 'image/jpeg';
    }

    private arrayBufferToBase64(buffer: ArrayBuffer): string {
        const bytes = new Uint8Array(buffer);
        let binary = '';
        for (let i = 0; i < bytes.byteLength; i++) {
            binary += String.fromCharCode(bytes[i]);
        }
        return btoa(binary);
    }

    private formatFileSize(bytes: number): string {
        if (bytes < 1024) return bytes + ' B';
        if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
        return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
    }

    // ==================== Modal Lifecycle ====================

    onOpen() {
        log.info('onOpen called');
        const params: WordPressPostParams = {
            status: this.plugin.settings.defaultPostStatus,
            commentStatus: this.plugin.settings.defaultCommentStatus,
            postType: this.postTypes.selected,
            categories: this.categories.selected,
            tags: this.normalizeTags(this.matterData.tags),
            title: this.noteTitle || '',
            content: '',
            slug: this.matterData.slug || '',
            excerpt: this.matterData.excerpt || ''
        };

        if (this.matterData.featuredImageId) {
            params.featuredMedia = Number(this.matterData.featuredImageId);
        }

        this.editableContent = this.articleContent;
        this.editableTags = params.tags ? [...params.tags] : [];

        if (!this.featuredImage && this.autoFeaturedImage) {
            this.featuredImage = this.autoFeaturedImage;
        }

        // Auto-generate slug
        if (this.plugin.settings.autoGenerateSlug && params.title && !params.slug) {
            setTimeout(() => {
                if (!this.slugGenerated && !params.slug) {
                    this.generateDefaultSlug(params.title, params);
                    this.slugGenerated = true;
                    this.lastAutoGeneratedSlug = params.slug || '';
                }
            }, 100);
        }

        this.display(params);
    }

    async onClose() {
        await this.saveGeneratedContentToFrontmatter();
        this.contentEl.empty();
        if (this.dateInputMask) this.dateInputMask.destroy();
    }

    private async saveGeneratedContentToFrontmatter(): Promise<void> {
        if (!this.currentParams || !this.notePath) return;

        const file = this.plugin.app.vault.getAbstractFileByPath(this.notePath);
        if (!file || !(file instanceof TFile)) return;

        try {
            const hasGeneratedTags = this.currentParams.tags?.length > 0 &&
                JSON.stringify(this.currentParams.tags) !== JSON.stringify(this.matterData.tags);
            const hasGeneratedExcerpt = this.currentParams.excerpt &&
                this.currentParams.excerpt !== this.matterData.excerpt;

            if (!hasGeneratedTags && !hasGeneratedExcerpt) return;

            await this.plugin.app.fileManager.processFrontMatter(file, (fm) => {
                if (hasGeneratedTags) {
                    fm.tags = TagFormatter.formatTags(this.currentParams!.tags, this.plugin.settings.tagFormat);
                    log.info('Saved generated tags to frontmatter:', this.currentParams!.tags);
                }
                if (hasGeneratedExcerpt) {
                    fm.excerpt = this.currentParams!.excerpt;
                    log.info('Saved generated excerpt to frontmatter');
                }
            });
        } catch (error) {
            log.error('Failed to save generated content to frontmatter:', error);
        }
    }

    // ==================== Display ====================

    private display(params: WordPressPostParams): void {
        const { contentEl } = this;
        this.currentParams = params;

        contentEl.empty();
        contentEl.addClass('wp-publish-modal-v3');

        this.createHeader(this.t('publishModal_title'));
        this.updateModalWidth();

        // Main container with two-column layout
        const mainContainer = contentEl.createDiv('wp-layout-container');

        // Left: Preview area
        const previewArea = mainContainer.createDiv('wp-layout-preview');
        this.renderPreviewArea(previewArea, params);

        // Right: Floating panels (desktop) or toggle buttons (mobile)
        const panelsArea = mainContainer.createDiv('wp-layout-panels');
        this.renderPanelsArea(panelsArea, params);

        // Bottom action bar
        this.renderBottomBar(contentEl, params);
    }

    private updateModalWidth(): void {
        const modalEl = this.modalEl;
        if (modalEl) {
            modalEl.style.width = '95vw';
            modalEl.style.maxWidth = '1000px';
            modalEl.style.minWidth = '400px';
        }
    }

    // ==================== Preview Area ====================

    private renderPreviewArea(container: HTMLElement, params: WordPressPostParams): void {
        // Mobile panel toggle buttons
        if (window.innerWidth < 768) {
            const mobileToggle = container.createDiv('wp-mobile-panels-toggle');
            
            const settingsBtn = mobileToggle.createEl('button', {
                cls: `wp-mobile-panel-btn ${this.mobileActivePanel === 'settings' ? 'active' : ''}`,
                text: '⚙️ 设置'
            });
            settingsBtn.onclick = () => this.toggleMobilePanel('settings');

            const historyBtn = mobileToggle.createEl('button', {
                cls: `wp-mobile-panel-btn ${this.mobileActivePanel === 'history' ? 'active' : ''}`,
                text: '🕐 历史'
            });
            historyBtn.onclick = () => this.toggleMobilePanel('history');
        }

        // Section 1: Featured Image
        this.renderFeaturedImageSection(container, params);

        // Section 2: Excerpt
        this.renderExcerptSection(container, params);

        // Section 3: Tags
        this.renderTagsSection(container, params);

        // Section 4: Article Preview (sticky)
        this.renderArticleSection(container, params);
    }

    private renderFeaturedImageSection(container: HTMLElement, params: WordPressPostParams): void {
        const section = container.createDiv('wp-preview-section');
        const header = section.createDiv('wp-preview-section-header');
        
        header.createEl('span', { cls: 'wp-preview-section-title', text: this.plugin.t('publishModal_featuredImage') || 'Featured Image' });
        createEditIcon(header, () => this.openFeaturedImageEditor(params));

        const content = section.createDiv('wp-preview-section-content');

        if (this.editState.featuredImage) {
            // Show editor
            this.renderFeaturedImageEditor(content, params);
        } else {
            // Show preview
            this.renderFeaturedImagePreview(content);
        }
    }

    private renderFeaturedImagePreview(content: HTMLElement): void {
        const imageToDisplay = this.featuredImage || this.autoFeaturedImage;

        if (imageToDisplay) {
            const img = content.createEl('img', { cls: 'wp-preview-featured-image' });
            img.src = `data:${imageToDisplay.mimeType};base64,${this.arrayBufferToBase64(imageToDisplay.content)}`;
            img.alt = imageToDisplay.fileName;

            const info = content.createDiv('wp-preview-image-info');
            info.setText(`${imageToDisplay.fileName} (${this.formatFileSize(imageToDisplay.content.byteLength)})`);
        } else {
            const placeholder = content.createDiv('wp-preview-placeholder');
            placeholder.setText('No image selected');
        }
    }

    private renderFeaturedImageEditor(content: HTMLElement, params: WordPressPostParams): void {
        // Image preview
        this.renderFeaturedImagePreview(content);

        // Button row
        const btnRow = content.createDiv('featured-image-btn-row');

        // Vault button
        const vaultBtn = btnRow.createEl('button', {
            cls: 'feature-btn',
            text: '📁 ' + this.t('publishModal_selectFromVault')
        });
        vaultBtn.onclick = () => this.selectVaultImage(params);

        // Unsplash button
        if (this.unsplashService) {
            const unsplashBtn = btnRow.createEl('button', {
                cls: 'feature-btn',
                text: '🖼️ Unsplash'
            });
            unsplashBtn.onclick = () => this.selectUnsplashImage(params);
        }

        // AI Generate button
        const aiBtn = btnRow.createEl('button', {
            cls: `feature-btn ${this.aiService?.hasImageAIKey() ? '' : 'disabled'}`,
            text: '🤖 ' + this.t('publishModal_aiGenerate')
        });
        if (this.aiService?.hasImageAIKey()) {
            aiBtn.onclick = () => this.generateAImage(params);
        } else {
            aiBtn.onclick = () => new Notice(this.t('notice_imageAIApiKeyRequired'));
        }

        // Bottom buttons
        createBottomButtons(content, {
            cancel: { onClick: () => this.cancelEdit('featuredImage') },
            save: { onClick: () => this.saveFeaturedImageEdit() }
        }, (key: string) => this.plugin.t(key as TranslateKey));
    }

    private openFeaturedImageEditor(params: WordPressPostParams): void {
        this.editState.featuredImage = true;
        this.display(params);
    }

    private cancelEdit(section: keyof EditState): void {
        this.editState[section] = false;
        if (this.currentParams) this.display(this.currentParams);
    }

    private saveFeaturedImageEdit(): void {
        this.editState.featuredImage = false;
        if (this.currentParams) this.display(this.currentParams);
    }

    private renderExcerptSection(container: HTMLElement, params: WordPressPostParams): void {
        const section = container.createDiv('wp-preview-section');
        const header = section.createDiv('wp-preview-section-header');

        header.createEl('span', { cls: 'wp-preview-section-title', text: this.plugin.t('publishModal_aiExcerpt') || 'Excerpt' });
        createEditIcon(header, () => this.openExcerptEditor(params));

        const content = section.createDiv('wp-preview-section-content');

        if (this.editState.excerpt) {
            this.renderExcerptEditor(content, params);
        } else {
            this.renderExcerptPreview(content, params);
        }
    }

    private renderExcerptPreview(content: HTMLElement, params: WordPressPostParams): void {
        if (params.excerpt) {
            const text = content.createDiv('wp-preview-excerpt-text');
            text.setText(params.excerpt);
        } else {
            const placeholder = content.createDiv('wp-preview-placeholder');
            placeholder.setText('No excerpt');
        }
    }

    private renderExcerptEditor(content: HTMLElement, params: WordPressPostParams): void {
        const textarea = content.createEl('textarea', { cls: 'wp-excerpt-textarea' });
        textarea.value = params.excerpt || '';
        textarea.placeholder = this.t('publishModal_excerptPlaceholder') || 'Enter excerpt...';

        textarea.oninput = () => {
            params.excerpt = textarea.value;
        };

        createBottomButtons(content, {
            aiGenerate: {
                show: !!this.aiService?.hasTextAIKey(),
                onClick: async () => {
                    await this.generateSummary(params);
                    textarea.value = params.excerpt || '';
                },
                disabled: !this.aiService?.hasTextAIKey()
            },
            cancel: { onClick: () => this.cancelEdit('excerpt') },
            save: { onClick: () => this.saveExcerptEdit() }
        }, (key: string) => this.plugin.t(key as TranslateKey));
    }

    private openExcerptEditor(params: WordPressPostParams): void {
        this.editState.excerpt = true;
        this.display(params);
    }

    private saveExcerptEdit(): void {
        this.editState.excerpt = false;
        if (this.currentParams) this.display(this.currentParams);
    }

    private renderTagsSection(container: HTMLElement, params: WordPressPostParams): void {
        const section = container.createDiv('wp-preview-section');
        const header = section.createDiv('wp-preview-section-header');

        header.createEl('span', { cls: 'wp-preview-section-title', text: this.plugin.t('publishModal_aiTags') || 'Tags' });
        createEditIcon(header, () => this.openTagsEditor(params));

        const content = section.createDiv('wp-preview-section-content');

        if (this.editState.tags) {
            this.renderTagsEditor(content, params);
        } else {
            this.renderTagsPreview(content, params);
        }
    }

    private renderTagsPreview(content: HTMLElement, params: WordPressPostParams): void {
        const tagsContainer = content.createDiv('wp-preview-tags');

        if (this.editableTags.length > 0) {
            this.editableTags.forEach(tag => {
                const tagEl = tagsContainer.createEl('span', { cls: 'wp-tag-item', text: tag });
                tagEl.style.backgroundColor = getTagColor(tag);
            });
        } else {
            const placeholder = tagsContainer.createDiv('wp-preview-placeholder');
            placeholder.setText('No tags');
        }
    }

    private renderTagsEditor(content: HTMLElement, params: WordPressPostParams): void {
        const container = content.createDiv('wp-tags-editor-container');

        // Tags list with shake animation
        const tagsList = container.createDiv('wp-tags-list');
        this.editableTags.forEach((tag, index) => {
            const tagEl = tagsList.createEl('span', { cls: 'wp-tag-item wp-tag-shaking' });
            tagEl.style.backgroundColor = getTagColor(tag);

            const text = tagEl.createEl('span', { text: tag });
            
            // Delete button
            const deleteBtn = tagEl.createEl('span', { cls: 'wp-tag-delete-btn', text: '×' });
            deleteBtn.onclick = () => {
                this.editableTags.splice(index, 1);
                params.tags = [...this.editableTags];
                this.renderTagsEditor(content, params);
            };
        });

        // Add button and AI generate
        const addContainer = container.createDiv('wp-tag-add-container');

        const addBtn = addContainer.createEl('button', { cls: 'wp-btn wp-btn-cancel', text: '+ Add' });
        addBtn.onclick = () => {
            const input = addContainer.createEl('input', {
                cls: 'wp-tag-add-input',
                attr: { type: 'text', placeholder: 'Tag name...' }
            });
            input.focus();

            input.onkeydown = (e) => {
                if (e.key === 'Enter' && input.value.trim()) {
                    this.editableTags.push(input.value.trim());
                    params.tags = [...this.editableTags];
                    this.renderTagsEditor(content, params);
                }
            };
        };

        // Bottom buttons
        createBottomButtons(content, {
            aiGenerate: {
                show: true,
                onClick: async () => {
                    await this.generateTags(params);
                    this.editableTags = params.tags ? [...params.tags] : [];
                    this.renderTagsEditor(content, params);
                },
                disabled: !this.aiService?.hasTextAIKey()
            },
            cancel: { onClick: () => this.cancelEdit('tags') },
            save: { onClick: () => this.saveTagsEdit(params) }
        }, (key: string) => this.plugin.t(key as TranslateKey));
    }

    private openTagsEditor(params: WordPressPostParams): void {
        this.editableTags = params.tags ? [...params.tags] : [];
        this.editState.tags = true;
        this.display(params);
    }

    private saveTagsEdit(params: WordPressPostParams): void {
        params.tags = [...this.editableTags];
        this.editState.tags = false;
        if (this.currentParams) this.display(this.currentParams);
    }

    private renderArticleSection(container: HTMLElement, params: WordPressPostParams): void {
        const section = container.createDiv('wp-preview-section wp-preview-section-sticky');
        const header = section.createDiv('wp-preview-section-header');

        header.createEl('span', { cls: 'wp-preview-section-title', text: this.plugin.t('publishModal_previewTitle') || 'Article Preview' });
        createEditIcon(header, () => this.openArticleEditor(params));

        const content = section.createDiv('wp-preview-section-content');

        if (this.editState.article) {
            this.renderArticleEditor(content, params);
        } else {
            this.renderArticlePreview(content);
        }
    }

    private renderArticlePreview(content: HTMLElement): void {
        const previewContent = content.createDiv('wp-preview-article');
        const html = AppState.markdownParser.render(this.editableContent);
        previewContent.innerHTML = html;
    }

    private renderArticleEditor(content: HTMLElement, params: WordPressPostParams): void {
        const textarea = content.createEl('textarea', { cls: 'wp-article-editor-textarea' });
        textarea.value = this.editableContent;

        textarea.oninput = () => {
            this.editableContent = textarea.value;
        };

        createBottomButtons(content, {
            cancel: { onClick: () => this.cancelEdit('article') },
            save: { onClick: () => this.saveArticleEdit() }
        }, (key: string) => this.plugin.t(key as TranslateKey));
    }

    private openArticleEditor(params: WordPressPostParams): void {
        this.editState.article = true;
        this.display(params);
    }

    private saveArticleEdit(): void {
        this.editState.article = false;
        if (this.currentParams) this.display(this.currentParams);
    }

    // ==================== Panels Area ====================

    private renderPanelsArea(container: HTMLElement, params: WordPressPostParams): void {
        const isMobile = window.innerWidth < 768;

        if (isMobile) {
            // Mobile: render panels in modal view when toggled
            if (this.mobilePanelVisible) {
                container.addClass('mobile-visible');
                this.renderMobilePanel(container, params);
            }
        } else {
            // Desktop: render floating panels
            const panelsContainer = createPanelContainer(container);

            // Settings panel
            this.settingsPanel = new FloatingPanel(panelsContainer, {
                title: this.t('publishModal_settingsTab') || 'Settings',
                icon: 'settings',
                defaultExpanded: this.settingsPanelExpanded,
                mobileDefaultExpanded: false,
                content: (panelContent) => this.renderSettingsPanel(panelContent, params)
            });

            // History panel
            this.historyPanel = new FloatingPanel(panelsContainer, {
                title: '🕐 History',
                icon: 'clock',
                defaultExpanded: this.historyPanelExpanded,
                mobileDefaultExpanded: false,
                content: (panelContent) => this.renderHistoryPanel(panelContent, params)
            });
        }
    }

    private toggleMobilePanel(panel: 'settings' | 'history'): void {
        this.mobileActivePanel = panel;
        this.mobilePanelVisible = !this.mobilePanelVisible;
        if (this.currentParams) this.display(this.currentParams);
    }

    private renderMobilePanel(container: HTMLElement, params: WordPressPostParams): void {
        if (this.mobileActivePanel === 'settings') {
            this.renderSettingsPanel(container, params);
        } else {
            this.renderHistoryPanel(container, params);
        }

        // Close button
        const closeBtn = container.createEl('button', {
            cls: 'wp-btn wp-btn-cancel',
            text: '✕ Close',
            attr: { style: 'margin-top: 16px; width: 100%;' }
        });
        closeBtn.onclick = () => {
            this.mobilePanelVisible = false;
            if (this.currentParams) this.display(this.currentParams);
        };
    }

    // ==================== Settings Panel ====================

    private renderSettingsPanel(container: HTMLElement, params: WordPressPostParams): void {
        const card = container.createDiv('wp-settings-card');

        // Title
        const titleSetting = new Setting(card)
            .setName(this.t('publishModal_titleName'))
            .addText(text => {
                this.titleInput = text.inputEl;
                text.setPlaceholder(this.t('publishModal_titlePlaceholder'))
                    .setValue(params.title || '')
                    .onChange(value => params.title = value);
                text.inputEl.style.width = '100%';
            });

        // Slug
        const slugSetting = new Setting(card)
            .setName(this.t('publishModal_slugName'))
            .addText(text => {
                this.slugInput = text.inputEl;
                text.setPlaceholder(this.t('publishModal_slugPlaceholder'))
                    .setValue(params.slug || '')
                    .onChange(value => {
                        params.slug = SlugGenerator.sanitizeSlug(value);
                    });
                text.inputEl.style.width = '100%';
            });

        // Slug retry button (for AI translate mode)
        if (this.plugin.settings.slugGenerationMode === 'ai-translate' && this.aiService?.hasTextAIKey()) {
            slugSetting.addButton(btn => {
                btn.setButtonText('🔄 ' + this.t('publishModal_retryButton') || 'Retry')
                    .onClick(async () => {
                        if (!params.title) {
                            new Notice(this.t('publishModal_slugNeedTitle'));
                            return;
                        }
                        btn.setDisabled(true);
                        try {
                            const slug = await this.aiService!.translateToSlug(params.title);
                            if (this.slugInput) {
                                this.slugInput.value = slug;
                                params.slug = slug;
                            }
                        } catch (error) {
                            new Notice(this.t('publishModal_slugTranslateFailed', { error: String(error) }));
                        } finally {
                            btn.setDisabled(false);
                        }
                    });
            });
        }

        // Categories (only for Post type)
        if (params.postType === PostTypeConst.Post && this.categories.items.length > 0) {
            this.renderCategorySelector(card, params);
        }

        // Status
        new Setting(card)
            .setName(this.t('publishModal_statusName'))
            .addDropdown(dropdown => {
                dropdown
                    .addOption(PostStatus.Draft, this.plugin.t('publishModal_statusDraft'))
                    .addOption(PostStatus.Publish, this.plugin.t('publishModal_statusPublish'))
                    .addOption(PostStatus.Private, this.plugin.t('publishModal_statusPrivate'))
                    .addOption(PostStatus.Future, this.plugin.t('publishModal_statusFuture'))
                    .setValue(params.status)
                    .onChange(value => {
                        params.status = value as PostStatus;
                        this.display(params);
                    });
            });

        // Scheduled date (if Future status)
        if (params.status === PostStatus.Future) {
            new Setting(card)
                .setName(this.t('publishModal_postDateTimeName'))
                .addText(text => {
                    text.setValue(format(new Date(), 'yyyy-MM-dd HH:mm:ss'));
                    this.setupDateMask(text.inputEl, params);
                });
        }

        // Comment status
        new Setting(card)
            .setName(this.t('publishModal_commentName'))
            .addDropdown(dropdown => {
                dropdown
                    .addOption(CommentStatus.Open, this.plugin.t('publishModal_commentOpen'))
                    .addOption(CommentStatus.Closed, this.plugin.t('publishModal_commentClosed'))
                    .setValue(params.commentStatus)
                    .onChange(value => params.commentStatus = value as CommentStatus);
            });
    }

    private renderCategorySelector(container: HTMLElement, params: WordPressPostParams): void {
        const validCategories = this.categories.items.filter(it => it.name && it.name.trim());
        if (validCategories.length === 0) return;

        const wrapper = container.createDiv({ cls: 'setting-item' });
        const info = wrapper.createDiv('setting-item-info');
        info.createDiv('setting-item-name').setText(this.t('publishModal_categoryName'));

        const control = wrapper.createDiv('setting-item-control');
        const tagsContainer = control.createDiv('wp-category-tags-container');

        const renderTags = () => {
            tagsContainer.empty();

            params.categories.forEach(catId => {
                const cat = validCategories.find(c => Number(c.id) === catId);
                if (cat) {
                    const tag = tagsContainer.createEl('span', { cls: 'wp-category-tag', text: cat.name });
                    const removeBtn = tag.createEl('span', { cls: 'wp-category-tag-remove', text: '×' });
                    removeBtn.onclick = () => {
                        params.categories = params.categories.filter(id => id !== catId);
                        renderTags();
                    };
                }
            });

            // Add button
            const available = validCategories.filter(c => !params.categories.includes(Number(c.id)));
            if (available.length > 0) {
                const addBtn = tagsContainer.createEl('button', { cls: 'wp-category-add-btn', text: '+' });
                addBtn.onclick = () => {
                    const select = tagsContainer.createEl('select', { cls: 'wp-category-dropdown' });
                    select.createEl('option', { value: '', text: this.t('publishModal_selectCategory') || 'Select...' });
                    available.forEach(c => select.createEl('option', { value: String(c.id), text: c.name }));
                    select.onchange = () => {
                        if (select.value) {
                            params.categories.push(Number(select.value));
                            renderTags();
                        }
                    };
                    select.focus();
                    addBtn.style.display = 'none';
                };
            }
        };

        renderTags();

        // Default to "Uncategorized"
        if (params.categories.length === 0) {
            const uncategorized = validCategories.find(c =>
                c.name === 'Uncategorized' || c.name === '未分类' || c.name === this.plugin.t('publishModal_uncategorized')
            );
            if (uncategorized) {
                params.categories = [Number(uncategorized.id)];
                renderTags();
            }
        }
    }

    // ==================== History Panel ====================

    private renderHistoryPanel(container: HTMLElement, params: WordPressPostParams): void {
        const card = container.createDiv('wp-settings-card');
        card.createEl('h3', { text: '🕐 History', cls: 'wp-settings-section-title' });

        if (this.matterData.postId) {
            // Show history for existing post
            const info = card.createDiv('wp-advanced-notice');
            info.createEl('p', { text: `Post ID: ${this.matterData.postId}` });
            info.createEl('p', { text: 'History feature coming soon...', cls: 'wp-preview-placeholder' });
        } else {
            const placeholder = card.createDiv('wp-preview-placeholder');
            placeholder.setText('No history available for new posts');
        }
    }

    // ==================== Bottom Bar ====================

    private renderBottomBar(container: HTMLElement, params: WordPressPostParams): void {
        const bottomContainer = container.createDiv('wp-publish-bottom-bar');

        const publishBtn = bottomContainer.createEl('button', {
            cls: 'mod-cta publish-btn-full',
            text: this.t('publishModal_publishButton')
        });
        this.publishBtn = publishBtn;
        publishBtn.onclick = () => this.doPublish(params, publishBtn);
    }

    // ==================== Image Selection Methods ====================

    private selectLocalImage(params: WordPressPostParams): void {
        const fileInput = document.createElement('input');
        fileInput.type = 'file';
        fileInput.accept = 'image/*';
        fileInput.onchange = async (e) => {
            const file = (e.target as HTMLInputElement).files?.[0];
            if (file) {
                try {
                    const arrayBuffer = await file.arrayBuffer();
                    this.featuredImage = {
                        fileName: file.name,
                        mimeType: file.type,
                        content: arrayBuffer,
                        width: 1200
                    };
                    this.imageSource = 'local';
                    await this.saveImageToCache(arrayBuffer, file.name, file.type, 'local');
                    this.display(params);
                    new Notice(this.t('publishModal_imageSelected_simple'));
                } catch (error) {
                    new Notice(this.t('publishModal_imageSelectFailed', { error: String(error) }));
                }
            }
        };
        fileInput.click();
    }

    private selectVaultImage(params: WordPressPostParams): void {
        const modal = new VaultImagePickerModal(
            this.app,
            this.plugin,
            async (file: TFile, arrayBuffer: ArrayBuffer, mimeType: string) => {
                this.featuredImage = {
                    fileName: file.name,
                    mimeType: mimeType,
                    content: arrayBuffer,
                    width: 1200
                };
                this.imageSource = 'vault';
                await this.saveImageToCache(arrayBuffer, file.name, mimeType, 'vault');
                this.display(params);
                new Notice(this.t('publishModal_imageFromGallery', { fileName: file.name }));
            }
        );
        modal.open();
    }

    private selectUnsplashImage(params: WordPressPostParams): void {
        if (!this.unsplashService) {
            new Notice(this.t('publishModal_unsplashKeyRequiredSimple'));
            return;
        }

        const tagsQuery = this.getSearchQuery(params);
        const targetWidth = this.plugin.settings.imageCropWidth || 1200;
        const ratio = this.plugin.settings.imageCropRatio || '16:9';

        const modal = new UnsplashPickerModal(
            this.app,
            this.plugin,
            this.unsplashService,
            async (image: UnsplashImage, arrayBuffer: ArrayBuffer) => {
                const processed = await resizeFeaturedImage(arrayBuffer, 'image/jpeg', targetWidth, ratio);
                const finalBuffer = processed || arrayBuffer;
                const fileName = `unsplash-${image.id}.jpg`;
                this.featuredImage = {
                    fileName,
                    mimeType: 'image/jpeg',
                    content: finalBuffer,
                    width: targetWidth
                };
                this.imageSource = 'unsplash';
                await this.saveImageToCache(finalBuffer, fileName, 'image/jpeg', 'unsplash');
                this.display(params);
                new Notice(this.t('publishModal_imageSelected_simple'));
            },
            tagsQuery
        );
        modal.open();
    }

    private getSearchQuery(params: WordPressPostParams): string {
        const frontmatterTag = this.matterData.tag;
        if (Array.isArray(frontmatterTag) && frontmatterTag.length > 0) {
            return String(frontmatterTag[0]);
        }
        if (typeof frontmatterTag === 'string' && frontmatterTag) {
            return frontmatterTag;
        }
        return params.tags?.[0] ? String(params.tags[0]) : '';
    }

    private async generateAImage(params: WordPressPostParams): Promise<void> {
        if (!this.plugin.settings.aiConfig || !this.aiService) {
            new Notice(this.t('publishModal_aiServiceRequired'));
            return;
        }
        if (!this.aiService.hasImageAIKey()) {
            new Notice(this.t('notice_imageAIApiKeyRequired'));
            return;
        }

        try {
            const imagePromptContent = await this.getImagePromptContent(params);
            if (!imagePromptContent) return;

            const contentToDetect = this.editableContent || this.articleContent;
            const language = detectLanguage(contentToDetect);
            const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'image');
            const imageDescriptionPrompt = localizedPrompt
                .replace('{title}', params.title || '')
                .replace('{content}', imagePromptContent);

            new Notice(this.t('publishModal_aiGeneratingImage'));
            const imageUrl = await this.aiService.generateImage(imageDescriptionPrompt);
            const response = await fetch(imageUrl);
            const arrayBuffer = await response.arrayBuffer();

            const fileName = `ai-generated-${Date.now()}.png`;
            this.featuredImage = {
                fileName,
                mimeType: 'image/png',
                content: arrayBuffer,
                width: 1200
            };
            this.imageSource = 'ai';
            await this.saveImageToCache(arrayBuffer, fileName, 'image/png', 'ai');

            this.display(params);
            new Notice(this.t('publishModal_aiImageGenerated'));
        } catch (error) {
            log.error('AI image generation error:', error);
            new Notice(this.t('publishModal_aiImageGenerateFailed', { error: String(error) }));
        }
    }

    private async getImagePromptContent(params: WordPressPostParams): Promise<string | null> {
        if (params.excerpt) return params.excerpt;
        if (params.tags?.length) return params.tags.join(', ');

        if (!this.aiService?.hasTextAIKey()) {
            new Notice(this.t('notice_textAIApiKeyRequired'));
            return null;
        }

        const contentToUse = this.editableContent || this.articleContent;
        if (!contentToUse) {
            new Notice(this.t('publishModal_emptyContent'));
            return null;
        }

        try {
            new Notice(this.t('publishModal_generatingSummary'));
            const cleanContent = this.sanitizeContentForAI(contentToUse, 2000);
            const language = detectLanguage(cleanContent);
            const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'summary');
            const prompt = localizedPrompt.replace('{content}', cleanContent);

            const summary = await this.aiService.generateText(prompt);
            params.excerpt = summary.trim();
            this.display(params);
            return params.excerpt;
        } catch (error) {
            log.error('Generate summary for image error:', error);
            new Notice(this.t('publishModal_summaryGenerateFailed', { error: String(error) }));
            return null;
        }
    }

    // ==================== AI Generation Methods ====================

    private async generateSummary(params: WordPressPostParams): Promise<void> {
        if (!this.aiService?.hasTextAIKey()) {
            new Notice(this.t('notice_textAIApiKeyRequired'));
            return;
        }

        const contentToUse = this.editableContent || this.articleContent;
        if (!contentToUse) {
            new Notice(this.t('publishModal_emptyContentForTags'));
            return;
        }

        try {
            new Notice(this.t('publishModal_generatingSummary'));
            const cleanContent = this.sanitizeContentForAI(contentToUse, 2000);
            const language = detectLanguage(cleanContent);
            const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'summary');
            const prompt = localizedPrompt.replace('{content}', cleanContent);

            const summary = await this.aiService.generateText(prompt);
            params.excerpt = summary.trim();
            new Notice(this.t('publishModal_summaryGenerated', { summary: params.excerpt.substring(0, 50) }));
        } catch (error) {
            log.error('Generate summary error:', error);
            new Notice(this.t('publishModal_summaryGenerateFailed', { error: String(error) }));
        }
    }

    private async generateTags(params: WordPressPostParams): Promise<void> {
        if (!this.aiService?.hasTextAIKey()) {
            new Notice(this.t('notice_textAIApiKeyRequired'));
            return;
        }

        const contentToUse = this.editableContent || this.articleContent;
        if (!contentToUse) {
            new Notice(this.t('publishModal_emptyContentForTags'));
            return;
        }

        try {
            new Notice(this.t('publishModal_generatingTags'));
            const cleanContent = this.sanitizeContentForAI(contentToUse, 2000);
            const language = detectLanguage(cleanContent);
            const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'tags');
            const prompt = localizedPrompt.replace('{content}', cleanContent);

            const tags = await this.aiService.generateText(prompt);
            params.tags = tags.split(/[,，]/).map(t => t.trim()).filter(t => t).slice(0, 4);
            new Notice(this.t('publishModal_tagsGenerated', { tags: params.tags.join(', ') }));
        } catch (error) {
            log.error('Generate tags error:', error);
            new Notice(this.t('publishModal_tagsGenerateFailed', { error: String(error) }));
        }
    }

    private sanitizeContentForAI(content: string, maxLen: number = 2000): string {
        let cleaned = content
            .replace(/^---[\s\S]*?---\n?/m, '')
            .replace(/```[\s\S]*?```/g, '')
            .replace(/!\[.*?\]\(.*?\)/g, '')
            .replace(/!\[\[.*?\]\]/g, '')
            .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
            .replace(/\[\[([^\]|]*)\|?([^\]]*)\]\]/g, '$2$1')
            .replace(/#{1,6}\s*/g, '')
            .replace(/[*_~`]+/g, '')
            .replace(/\n{3,}/g, '\n\n')
            .trim();
        return cleaned.substring(0, maxLen);
    }

    // ==================== Date Mask ====================

    private setupDateMask(inputEl: HTMLInputElement, params: WordPressPostParams): void {
        const dateTimeFormat = 'yyyy-MM-dd HH:mm:ss';
        const dateBlocks = {
            yyyy: { mask: IMask.MaskedRange, from: 1970, to: 9999 },
            MM: { mask: IMask.MaskedRange, from: 1, to: 12 },
            dd: { mask: IMask.MaskedRange, from: 1, to: 31 },
        };

        if (this.dateInputMask) this.dateInputMask.destroy();

        this.dateInputMask = IMask(inputEl, [{
            mask: Date,
            lazy: false,
            overwrite: true,
            pattern: dateTimeFormat,
            blocks: {
                ...dateBlocks,
                HH: { mask: IMask.MaskedRange, from: 0, to: 23 },
                mm: { mask: IMask.MaskedRange, from: 0, to: 59 },
                ss: { mask: IMask.MaskedRange, from: 0, to: 59 },
            },
            format: (date: SafeAny) => format(date, dateTimeFormat),
            parse: (str: string) => parse(str, dateTimeFormat, new Date())
        }]);

        this.dateInputMask.on('accept', () => {
            if (this.dateInputMask?.masked.isComplete) {
                params.datetime = this.dateInputMask.typedValue;
            }
        });
    }

    // ==================== Slug Generation ====================

    private generateDefaultSlug(title: string, params?: WordPressPostParams): void {
        if (!title || !this.slugInput) return;

        try {
            if (this.plugin.settings.slugGenerationMode === 'ai-translate' && this.aiService) {
                this.aiService.translateToSlug(title).then(slug => {
                    if (this.slugInput) {
                        this.slugInput.value = slug;
                        if (params) params.slug = slug;
                    }
                    this.slugGenerated = true;
                }).catch(() => {
                    const fallbackSlug = SlugGenerator.autoGenerateSlug(title);
                    if (this.slugInput) {
                        this.slugInput.value = fallbackSlug;
                        if (params) params.slug = fallbackSlug;
                    }
                    this.slugGenerated = true;
                });
            } else {
                const slug = SlugGenerator.autoGenerateSlug(title);
                if (this.slugInput) {
                    this.slugInput.value = slug;
                    if (params) params.slug = slug;
                }
                this.slugGenerated = true;
            }
        } catch (error) {
            log.error('Slug generation failed:', error);
        }
    }

    // ==================== Publish ====================

    private doPublish(params: WordPressPostParams, btn?: HTMLButtonElement): void {
        if (this.isPublishing) return;

        this.isPublishing = true;
        this.lastPublishParams = params;
        params.content = this.editableContent;

        if (this.editableTags.length > 0) {
            params.tags = [...this.editableTags];
        }

        this.modalEl.style.display = 'none';
        const progressOverlay = this.showPublishProgress();

        const doSubmit = () => {
            if (this.matterData.postType && this.matterData.postType !== PostTypeConst.Post &&
                (this.matterData.tags || this.matterData.categories)) {
                return openConfirmModal({ message: this.t('publishModal_wrongMatterDataForPage') }, this.plugin)
                    .then(result => {
                        if (result.code === ConfirmCode.Confirm) {
                            return this.onSubmit(params, fm => { delete fm.categories; delete fm.tags; },
                                this.featuredImage || undefined);
                        }
                        throw new Error('User cancelled');
                    });
            }

            return new Promise<void>((resolve, reject) => {
                try {
                    this.onSubmit(params, fm => {
                        if (params.excerpt) fm.excerpt = params.excerpt;
                        if (params.tags?.length > 0) {
                            fm.tags = TagFormatter.formatTags(params.tags, this.plugin.settings.tagFormat);
                        }
                    }, this.featuredImage || undefined);
                    resolve();
                } catch (e) {
                    reject(e);
                }
            });
        };

        doSubmit()
            .then(() => {
                progressOverlay.remove();
                this.showConfetti();
                this.showSuccessNotice();
            })
            .catch(err => {
                log.error('Publish error:', err);
                progressOverlay.remove();
                if (err instanceof Error && err.message !== 'User cancelled') {
                    this.showErrorCard(err.message);
                } else {
                    this.close();
                }
                this.isPublishing = false;
            });
    }

    private showPublishProgress(): HTMLElement {
        const overlay = document.body.createDiv('wp-publish-overlay');
        const container = overlay.createDiv('wp-publish-progress-container');
        const spinner = container.createDiv('wp-publish-spinner');
        spinner.createSpan({ cls: 'wp-spinner-cat' });
        const text = container.createDiv('wp-publish-progress-text');
        text.textContent = this.plugin.t('publishModal_publishingProgress');
        const progressBar = container.createDiv('wp-publish-progress-bar');
        progressBar.createDiv('wp-publish-progress-fill');
        return overlay;
    }

    private showSuccessNotice(): void {
        new Notice(this.t('publishModal_publishSuccess'), 5000);
        setTimeout(() => this.close(), 2000);
    }

    private showConfetti(): void {
        const container = document.body.createDiv('wp-confetti-container');
        const colors = ['#ff6b6b', '#ffd93d', '#6bcb77', '#4d96ff', '#9c88ff', '#ff9ff3', '#54a0ff', '#5f27cd'];
        const confettiCount = 150;

        for (let i = 0; i < confettiCount; i++) {
            const confetti = container.createDiv('wp-confetti');
            const color = colors[Math.floor(Math.random() * colors.length)];
            const size = Math.random() * 10 + 5;
            const left = Math.random() * 100;
            const animDuration = Math.random() * 2 + 2;
            const animDelay = Math.random() * 0.5;

            confetti.style.cssText = `
                position: fixed; width: ${size}px; height: ${size}px; background: ${color};
                left: ${left}vw; top: -20px; opacity: 1;
                border-radius: ${Math.random() > 0.5 ? '50%' : '2px'};
                animation: confettiFall ${animDuration}s ease-out ${animDelay}s forwards;
                transform: rotate(${Math.random() * 360}deg); z-index: 10000; pointer-events: none;
            `;
        }

        setTimeout(() => container.remove(), 4000);
    }

    private showErrorCard(errorMessage: string): void {
        const overlay = document.body.createDiv('wp-publish-overlay');
        const container = overlay.createDiv('wp-error-card');

        const icon = container.createDiv('wp-error-icon');
        icon.setText('😢');

        const title = container.createDiv('wp-error-title');
        title.setText(this.t('publishModal_publishFailedTitle'));

        const detail = container.createDiv('wp-error-detail');
        detail.setText(errorMessage);

        const buttons = container.createDiv('wp-error-buttons');

        const retryBtn = buttons.createEl('button', { cls: 'wp-error-retry-btn' });
        retryBtn.setText(this.t('publishModal_retryButton'));
        retryBtn.onclick = () => {
            overlay.remove();
            this.modalEl.style.display = '';
            if (this.lastPublishParams) this.doPublish(this.lastPublishParams);
        };

        const closeBtn = buttons.createEl('button', { cls: 'wp-error-close-btn' });
        closeBtn.setText(this.t('publishModal_closeButton'));
        closeBtn.onclick = () => {
            overlay.remove();
            this.close();
        };

        setTimeout(() => {
            if (overlay.isConnected) {
                overlay.remove();
                this.close();
            }
        }, 8000);
    }

    // ==================== Utility ====================

    private normalizeTags(tags: SafeAny): string[] {
        return TagFormatter.parseToArray(tags);
    }
}
