import { Setting, Notice, TFile, requestUrl, setIcon } from 'obsidian';
import { toNumber } from 'lodash-es';
import { format, parse } from 'date-fns';
import IMask, { DynamicMaskType, InputMask } from 'imask';

import WordpressPlugin from './main';
import { WordPressPostParams } from './wp-client';
import { CommentStatus, PostStatus, PostType, PostTypeConst, Term } from './wp-api';
import { MatterData } from './types';
import { ConfirmCode, openConfirmModal } from './confirm-modal';
import { AbstractModal } from './abstract-modal';
import { SafeAny } from './utils';
import { SlugGenerator } from './slug-generator';
import { FeaturedImageResult, VaultImagePickerModal, UnsplashPickerModal, resizeFeaturedImage } from './featured-image-modal';
import { UnsplashService, UnsplashImage } from './unsplash-service';
import { AIService } from './ai-service';
import { AppState } from './app-state';
import { ImageCacheManager, CachedFeaturedImage } from './image-cache-manager';
import { createModuleLogger } from './utils/logger';
import { TagFormatter } from './tag-formatter';
import { getApiCapabilities, getApiLimitations, getApiRecommendation } from './api-capability';
import { TranslateKey } from './i18n';

const log = createModuleLogger('WpPublishModalV2');

// Default prompt templates will be loaded from i18n

/**
 * 预定义的标签颜色池 - 使用 CSS 变量以支持主题切换
 */
const TAG_COLORS = [
  'var(--wp-tag-color-1)',
  'var(--wp-tag-color-2)',
  'var(--wp-tag-color-3)',
  'var(--wp-tag-color-4)',
  'var(--wp-tag-color-5)',
  'var(--wp-tag-color-6)',
  'var(--wp-tag-color-7)',
  'var(--wp-tag-color-8)',
  'var(--wp-tag-color-9)',
];

/**
 * 根据标签名称哈希分配颜色（确保同名标签颜色一致）
 */
function getTagColor(tagName: string): string {
  const hash = tagName.split('').reduce((acc, char) =>
    acc + char.charCodeAt(0), 0);
  return TAG_COLORS[hash % TAG_COLORS.length];
}

/**
 * 检测文本的主要语言
 */
function detectLanguage(text: string): 'zh' | 'en' | 'other' {
  if (!text || text.length < 10) return 'en';

  // 统计中文字符数量
  const chineseChars = text.match(/[\u4e00-\u9fa5]/g);
  const chineseCount = chineseChars ? chineseChars.length : 0;

  // 统计英文字符数量
  const englishChars = text.match(/[a-zA-Z]/g);
  const englishCount = englishChars ? englishChars.length : 0;

  // 如果中文字符占比超过30%，认为是中文
  if (chineseCount > text.length * 0.3) {
    return 'zh';
  }

  // 如果英文字符占比超过40%，认为是英文
  if (englishCount > text.length * 0.4) {
    return 'en';
  }

  // 其他情况，默认英文
  return 'other';
}

/**
 * Get localized prompt based on language
 */
function getLocalizedPrompt(plugin: WordpressPlugin, language: 'zh' | 'en' | 'other', type: 'summary' | 'tags' | 'image'): string {
  // Check if user has custom prompt in settings
  if (type === 'summary' && plugin.settings.summaryPrompt) {
    return plugin.settings.summaryPrompt;
  } else if (type === 'tags' && plugin.settings.tagsPrompt) {
    return plugin.settings.tagsPrompt;
  } else if (type === 'image' && plugin.settings.imageGenerationPrompt) {
    return plugin.settings.imageGenerationPrompt;
  }

  // Use English prompts for English or other languages
  if (language === 'en' || language === 'other') {
    if (type === 'summary') {
      return plugin.t('defaultPrompt_summaryEn');
    } else if (type === 'tags') {
      return plugin.t('defaultPrompt_tagsEn');
    } else {
      return plugin.t('defaultPrompt_imageEn');
    }
  }

  // Use Chinese prompts for Chinese
  if (type === 'summary') {
    return plugin.t('defaultPrompt_summary');
  } else if (type === 'tags') {
    return plugin.t('defaultPrompt_tags');
  } else {
    return plugin.t('defaultPrompt_image');
  }
}

/**
 * WordPress publish modal V2 - New version with improved UI
 * Tabs: settings/preview/advanced
 */
export class WpPublishModalV2 extends AbstractModal {

  private dateInputMask: InputMask<DynamicMaskType> | null = null;
  private featuredImage: FeaturedImageResult | null = null;
  private aiService: AIService | null = null;
  private unsplashService: UnsplashService | null = null;
  private slugInput: HTMLInputElement | null = null;
  private titleInput: HTMLInputElement | null = null;
  private currentTab: 'settings' | 'preview' = 'settings';
  private currentAITab: 'featured-image' | 'excerpt' | 'tags' = 'featured-image'; // AI 标签页状态
  private editableContent: string = '';
  private isEditingPreview: boolean = false;
  private autoFeaturedImage: FeaturedImageResult | null = null;
  private slugGenerated: boolean = false;
  private lastAutoGeneratedSlug: string = '';
  private isPublishing: boolean = false;
  private lastPublishParams: WordPressPostParams | null = null;
  private publishBtn: HTMLButtonElement | null = null;
  private imageCacheManager: ImageCacheManager; // 图片缓存管理器
  private notePath: string; // 当前笔记路径，用于缓存关联
  private imageSource: 'local' | 'unsplash' | 'ai' | 'vault' | 'cached' | 'auto' = 'auto'; // 图片来源类型
  private currentParams: WordPressPostParams | null = null; // 当前的发布参数，用于在关闭时保存生成的内容
  private editableTags: string[] = []; // 可编辑的标签数组（预览标签页使用）
  private tagsContainer: HTMLElement | null = null; // 标签容器的引用
  private cachedFeaturedImageId: number | undefined; // 从缓存或远程获取的特色图片 ID
  private isLoadingRemoteImage: boolean = false; // 是否正在加载远程图片
  private remoteImageLoadFailed: boolean = false; // 远程图片加载是否失败
  private remoteImagePostId: string | number | null = null; // 需要加载远程图片的 postId
  private remoteImageError: string | null = null; // 远程图片加载失败的错误信息

  // Prompt templates from settings, with proper defaults
  private get imageGenerationPrompt(): string {
    return this.plugin.settings.imageGenerationPrompt || this.plugin.t('defaultPrompt_image');
  }

  private get summaryPrompt(): string {
    return this.plugin.settings.summaryPrompt || this.plugin.t('defaultPrompt_summary');
  }

  private get tagsPrompt(): string {
    return this.plugin.settings.tagsPrompt || this.plugin.t('defaultPrompt_tags');
  }

  constructor(
    readonly plugin: WordpressPlugin,
    private readonly categories: {
      items: Term[],
      selected: number[]
    },
    private readonly postTypes: {
      items: PostType[],
      selected: PostType
    },
    private readonly onSubmit: (
      params: WordPressPostParams,
      updateMatterData: (matter: MatterData) => void,
      featuredImage?: FeaturedImageResult
    ) => void,
    private readonly matterData: MatterData,
    private readonly articleContent: string = '',
    private readonly noteTitle: string = '',
    notePath: string = ''
  ) {
    super(plugin);
    log.info('Constructor called');

    // 初始化图片缓存管理器
    this.imageCacheManager = new ImageCacheManager(plugin.app);
    this.notePath = notePath;

    if (plugin.settings.aiConfig) {
      this.aiService = new AIService(plugin.settings.aiConfig);
    }

    if (plugin.settings.unsplashAccessKey) {
      this.unsplashService = new UnsplashService(plugin.settings.unsplashAccessKey);
    }

    // 尝试从缓存加载特色图片
    if (matterData.postId) {
      this.loadFeaturePictureFromCache(matterData.postId);
    } else {
      // 如果没有 postId，尝试从图片缓存恢复
      this.loadCachedImage();
    }
  }

  // 从缓存加载特色图片
  private async loadFeaturePictureFromCache(postId: string | number): Promise<void> {
    try {
      // 优先检查本地是否有用户选择的图片缓存
      if (this.notePath) {
        const localCachedImage = await this.imageCacheManager.loadImage(this.notePath);
        if (localCachedImage) {
          log.info('Found local cached image, using it instead of remote:', localCachedImage.fileName);
          this.featuredImage = {
            fileName: localCachedImage.fileName,
            mimeType: localCachedImage.mimeType,
            content: localCachedImage.content,
            width: localCachedImage.width
          };
          this.imageSource = 'cached';

          // 图片加载完成后，刷新 UI 显示
          if (this.currentParams) {
            this.display(this.currentParams);
          }
          return;
        }
      }

      // 本地无缓存，检查 featurePicture 缓存
      const cached = this.plugin.featurePictureCacheManager.get(postId);
      if (cached) {
        log.info('Loading featured image from cache:', cached.url);
        // 保存缓存的 featuredImageId
        this.cachedFeaturedImageId = cached.featuredImageId;
        await this.loadFeaturePictureFromUrl(cached.url);
        return;
      }
      log.info('No cached feature picture found for post:', postId);

      // 缓存未命中，尝试从远程 WordPress 获取
      const remoteImage = await this.loadFeaturePictureFromRemote(postId);
      if (remoteImage) {
        return; // 成功从远程加载
      }

      // 远程也没有，尝试从图片缓存恢复
      await this.loadCachedImage();
    } catch (e) {
      log.error('Failed to load feature picture from cache:', e);
      await this.loadCachedImage();
    }
  }

  /**
   * 从远程 WordPress 获取特色图片
   * @param postId - 文章 ID
   * @returns 是否成功加载
   */
  private async loadFeaturePictureFromRemote(postId: string | number): Promise<boolean> {
    try {
      log.info('Fetching featured image from remote WordPress:', postId);

      // 设置加载状态
      this.isLoadingRemoteImage = true;
      this.remoteImageLoadFailed = false;
      this.remoteImagePostId = postId;
      this.remoteImageError = null;

      // 如果 UI 已经初始化，刷新显示加载状态
      if (this.currentParams) {
        this.display(this.currentParams);
      }

      // 获取当前配置文件
      const profile = this.plugin.settings.profiles.find(p => p.isDefault);
      if (!profile) {
        log.warn('No default profile found');
        this.remoteImageError = '未配置 WordPress 账号，请先在设置中配置';
        return false;
      }

      // 创建临时客户端
      const { getWordPressClient } = await import('./wp-clients');
      const client = getWordPressClient(this.plugin, profile);
      if (!client) {
        log.warn('Failed to create WordPress client');
        this.remoteImageError = `无法创建 ${profile.name} 客户端`;
        return false;
      }

      // 检查客户端是否有 getPost 方法（AbstractWpClient 的子类）
      if (!('getPost' in client)) {
        log.warn('Client does not support getPost method');
        this.remoteImageError = '客户端不支持获取文章';
        return false;
      }

      // 获取认证信息
      const auth = {
        username: profile.username || null,
        password: profile.password || null
      };

      // 获取文章信息（网络已在发布前检测，不需要超时）
      const post = await (client as any).getPost(postId, auth);

      if (!post) {
        log.info('Post not found on remote');
        return false;
      }

      // 提取特色图片信息
      const featuredImageId = post.featured_media;
      const featurePictureUrl = post._embedded?.['wp:featuredmedia']?.[0]?.source_url;

      if (!featurePictureUrl || !featuredImageId) {
        log.info('No featured image found on remote post');
        return false;
      }

      log.info('Found featured image on remote:', { featuredImageId, featurePictureUrl });

      // 更新缓存
      await this.plugin.featurePictureCacheManager.set(
        postId,
        featurePictureUrl,
        featuredImageId
      );

      // 保存 featuredImageId
      this.cachedFeaturedImageId = featuredImageId;

      // 加载图片
      await this.loadFeaturePictureFromUrl(featurePictureUrl);

      return true;
    } catch (e) {
      log.error('Failed to load featured image from remote:', e);
      this.remoteImageLoadFailed = true;

      // 获取配置名称用于错误提示
      const profile = this.plugin.settings.profiles.find(p => p.isDefault);
      const profileName = profile?.name || '默认配置';
      const errorMessage = e instanceof Error ? e.message : String(e);
      this.remoteImageError = `连接 ${profileName} 失败：${errorMessage}`;

      return false;
    } finally {
      // 清除加载状态
      this.isLoadingRemoteImage = false;

      // 如果 UI 已经初始化，刷新显示
      if (this.currentParams) {
        this.display(this.currentParams);
      }
    }
  }

  // 从 URL 加载已有的特色图片
  private async loadFeaturePictureFromUrl(url: string): Promise<void> {
    try {
      log.info('Loading featured image from URL:', url);
      // 使用 Obsidian 的 requestUrl API 绕过 CORS 限制
      const response = await requestUrl({
        url,
        method: 'GET'
      });

      // 从 URL 或 Content-Type 获取 MIME 类型
      const contentType = response.headers['content-type'];
      const mimeType = this.getMimeTypeFromResponse(contentType, url);

      // 从 URL 提取文件名
      const fileName = this.extractFileName(url);

      this.autoFeaturedImage = {
        fileName,
        mimeType,
        content: response.arrayBuffer,
        width: 1200
      };
      log.info('Successfully loaded featured image:', fileName);

      // 图片加载完成后，刷新 UI 显示
      if (this.currentParams) {
        this.display(this.currentParams);
      }
    } catch (e) {
      log.info('Failed to load featured image from URL:', e);
      // 加载失败，尝试从缓存恢复
      await this.loadCachedImage();
    }
  }

  /**
   * 从缓存加载图片，如果没有缓存则检测文章第一张图片
   */
  private async loadCachedImage(): Promise<void> {
    if (!this.notePath) {
      // 没有笔记路径，直接检测第一张图片
      await this.detectFirstImage();
      return;
    }

    try {
      const cachedImage = await this.imageCacheManager.loadImage(this.notePath);
      if (cachedImage) {
        log.info('Restored featured image from cache:', cachedImage.fileName);
        this.featuredImage = {
          fileName: cachedImage.fileName,
          mimeType: cachedImage.mimeType,
          content: cachedImage.content,
          width: cachedImage.width
        };
        this.imageSource = 'cached';

        // 图片加载完成后，刷新 UI 显示
        if (this.currentParams) {
          this.display(this.currentParams);
        }
      } else {
        // 没有缓存，自动检测文章第一张图片
        await this.detectFirstImage();
      }
    } catch (e) {
      log.info('Failed to load cached image:', e);
      await this.detectFirstImage();
    }
  }

  /**
   * 保存图片到缓存
   */
  private async saveImageToCache(
    imageData: ArrayBuffer,
    fileName: string,
    mimeType: string,
    sourceType: 'local' | 'unsplash' | 'ai' | 'vault'
  ): Promise<void> {
    if (!this.notePath) {
      log.info('No note path, skipping cache save');
      return;
    }

    try {
      await this.imageCacheManager.saveImage(
        this.notePath,
        imageData,
        fileName,
        mimeType,
        sourceType
      );
      log.info('Image saved to cache:', fileName);
    } catch (e) {
      log.error('Failed to save image to cache:', e);
    }
  }

  /**
   * 清除当前笔记的图片缓存
   */
  async clearImageCache(): Promise<void> {
    if (!this.notePath) return;

    try {
      await this.imageCacheManager.clearCache(this.notePath);
      log.info('Image cache cleared for:', this.notePath);
    } catch (e) {
      log.error('Failed to clear image cache:', e);
    }
  }

  /**
   * 获取从缓存中加载的特色图片 ID
   */
  getCachedFeaturedImageId(): number | undefined {
    return this.cachedFeaturedImageId;
  }

  private getMimeTypeFromResponse(contentType: string | null, url: string): string {
    if (contentType?.startsWith('image/')) {
      return contentType.split(';')[0];
    }

    // 从 URL 扩展名推断
    const ext = url.split('.').pop()?.toLowerCase()?.split('?')[0];
    return this.getMimeType(ext || 'jpg');
  }

  private extractFileName(url: string): string {
    const urlParts = url.split('/');
    const lastPart = urlParts[urlParts.length - 1]?.split('?')[0];
    return (lastPart && lastPart.includes('.')) ? lastPart : 'featured-image.jpg';
  }

  // 检测文章第一张图片
  private async detectFirstImage(): Promise<void> {
    try {
      const imagePath = this.extractFirstImagePath();
      if (!imagePath) {
        await this.loadEmptyImage();
        return;
      }

      if (imagePath.startsWith('http')) {
        await this.loadOnlineImage(imagePath);
      } else {
        await this.loadLocalImage(imagePath);
      }

      // 图片检测完成后，刷新 UI 显示
      if (this.currentParams && this.autoFeaturedImage) {
        this.display(this.currentParams);
      }
    } catch (e) {
      log.info('Error detecting first image:', e);
      await this.loadEmptyImage();
    }
  }

  private extractFirstImagePath(): string | null {
    const content = this.articleContent || '';
    const imageRegex = /!\[.*?\]\((.*?)\)|!\[\[(.*?)(?:\|.*?)?\]\]/g;
    const match = imageRegex.exec(content);
    return match ? (match[1] || match[2]) : null;
  }

  private async loadLocalImage(imagePath: string): Promise<void> {
    const file = this.app.metadataCache.getFirstLinkpathDest(imagePath, this.noteTitle);
    if (file instanceof TFile) {
      const binaryContent = await this.app.vault.readBinary(file);
      this.autoFeaturedImage = {
        fileName: file.name,
        mimeType: this.getMimeType(file.extension.toLowerCase()),
        content: binaryContent,
        width: 1200
      };
      log.info('Auto-detected first image:', file.name);

      // 图片加载完成后，刷新 UI 显示
      if (this.currentParams) {
        this.display(this.currentParams);
      }
    }
  }

  private async loadOnlineImage(imagePath: string): Promise<void> {
    try {
      const response = await fetch(imagePath);
      const arrayBuffer = await response.arrayBuffer();
      this.autoFeaturedImage = {
        fileName: `featured-${Date.now()}.jpg`,
        mimeType: 'image/jpeg',
        content: arrayBuffer,
        width: 1200
      };

      // 图片加载完成后，刷新 UI 显示
      if (this.currentParams) {
        this.display(this.currentParams);
      }
    } catch (e) {
      log.info('Failed to download online image:', e);
    }
  }

  private async loadEmptyImage(): Promise<void> {
    try {
      const emptyFile = this.app.vault.getAbstractFileByPath('empty.png');
      if (emptyFile instanceof TFile) {
        const content = await this.app.vault.readBinary(emptyFile);
        this.autoFeaturedImage = {
          fileName: 'empty.png',
          mimeType: 'image/png',
          content: content,
          width: 1200
        };
      }
    } catch (e) {
      log.info('Could not load empty.png:', e);
    }
  }

  private getMimeType(extension: string): string {
    const mimeTypes: Record<string, string> = {
      'jpg': 'image/jpeg',
      'jpeg': 'image/jpeg',
      'png': 'image/png',
      'gif': 'image/gif',
      'webp': 'image/webp'
    };
    return mimeTypes[extension.toLowerCase()] || 'image/jpeg';
  }

  /**
   * 将 ArrayBuffer 转换为 Base64 字符串
   */
  private arrayBufferToBase64(buffer: ArrayBuffer): string {
    const bytes = new Uint8Array(buffer);
    let binary = '';
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }

  /**
   * 格式化文件大小
   */
  private formatFileSize(bytes: number): string {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  }

  /**
   * 加载远程特色图片（别名方法）
   */
  private async loadRemoteFeaturedImage(postId: string | number, params: WordPressPostParams): Promise<void> {
    await this.loadFeaturePictureFromRemote(postId);
  }

  onOpen() {
    log.info('onOpen called');
    const params: WordPressPostParams = {
      status: this.plugin.settings.defaultPostStatus,
      commentStatus: this.plugin.settings.defaultCommentStatus,
      postType: this.postTypes.selected,
      categories: this.categories.selected,
      tags: this.normalizeTags(this.matterData.tags),
      title: this.noteTitle || '',
      content: '',
      slug: this.matterData.slug || '',
      excerpt: this.matterData.excerpt || ''
    };

    // 从 frontmatter 恢复特色图片 ID（如果存在）
    if (this.matterData.featuredImageId) {
      params.featuredMedia = Number(this.matterData.featuredImageId);
    }

    this.editableContent = this.articleContent;
    this.currentTab = 'settings';

    // 设置默认特色图片为自动检测的图片
    if (!this.featuredImage && this.autoFeaturedImage) {
      this.featuredImage = this.autoFeaturedImage;
    }

    // Slug generation: only auto-generate if no existing slug in frontmatter
    // Delay slug generation until title is confirmed available
    if (this.plugin.settings.autoGenerateSlug && params.title && !params.slug) {
      // Use setTimeout to ensure slugInput is created first
      setTimeout(() => {
        if (!this.slugGenerated && !params.slug) {
          this.generateDefaultSlug(params.title, params);
          this.slugGenerated = true;
          this.lastAutoGeneratedSlug = params.slug || '';
        }
      }, 100);
    }

    this.display(params);
  }

  async onClose() {
    const { contentEl } = this;

    // 在关闭前保存生成的内容到 frontmatter
    await this.saveGeneratedContentToFrontmatter();

    contentEl.empty();
    if (this.dateInputMask) {
      this.dateInputMask.destroy();
    }
  }

  /**
   * 保存生成的内容（标签、摘要等）到 frontmatter
   * 当用户生成内容后关闭窗口时，确保内容不会丢失
   */
  private async saveGeneratedContentToFrontmatter(): Promise<void> {
    if (!this.currentParams || !this.notePath) {
      return;
    }

    const file = this.plugin.app.vault.getAbstractFileByPath(this.notePath);
    if (!file || !(file instanceof TFile)) {
      return;
    }

    try {
      // 检查是否有需要保存的生成内容
      const hasGeneratedTags = this.currentParams.tags &&
                               this.currentParams.tags.length > 0 &&
                               JSON.stringify(this.currentParams.tags) !== JSON.stringify(this.matterData.tags);

      const hasGeneratedExcerpt = this.currentParams.excerpt &&
                                  this.currentParams.excerpt !== this.matterData.excerpt;

      if (!hasGeneratedTags && !hasGeneratedExcerpt) {
        return; // 没有需要保存的内容
      }

      // 使用 processFrontMatter 更新 frontmatter
      await this.plugin.app.fileManager.processFrontMatter(file, (fm) => {
        if (hasGeneratedTags) {
          // 根据用户设置格式化标签
          fm.tags = TagFormatter.formatTags(
            this.currentParams!.tags,
            this.plugin.settings.tagFormat
          );
          log.info('Saved generated tags to frontmatter:', this.currentParams!.tags);
        }
        if (hasGeneratedExcerpt) {
          fm.excerpt = this.currentParams!.excerpt;
          log.info('Saved generated excerpt to frontmatter');
        }
      });
    } catch (error) {
      log.error('Failed to save generated content to frontmatter:', error);
    }
  }

  private display(params: WordPressPostParams): void {
    const { contentEl } = this;

    // 保存当前参数，用于在关闭时保存生成的内容
    this.currentParams = params;

    contentEl.empty();
    contentEl.addClass('wp-publish-modal-v2');

    this.createHeader(this.t('publishModal_title'));

    // 自适应窗口宽度
    this.updateModalWidth();

    // 创建标签切换
    this.renderTabBar(contentEl, params);

    // 显示API能力警告（仅限XML-RPC）
    const profile = this.plugin.settings.profiles.find(p => p.name === params.profileName);
    if (profile && profile.apiType === 'xml-rpc') {
      this.renderApiWarning(contentEl, profile.apiType);
    }

    const mainContainer = contentEl.createDiv('wp-publish-container');

    if (this.currentTab === 'settings') {
      this.renderSettingsTab(mainContainer, params);
    } else if (this.currentTab === 'preview') {
      this.renderPreviewTab(mainContainer, params);
    }

    // 底部操作栏
    this.renderBottomBar(contentEl, params);
  }

  private updateModalWidth(): void {
    const modalEl = this.modalEl;
    if (modalEl) {
      modalEl.style.width = '90vw';
      modalEl.style.maxWidth = '800px';
      modalEl.style.minWidth = '400px';
      modalEl.style.boxSizing = 'border-box';
    }
  }

  private renderTabBar(container: HTMLElement, params: WordPressPostParams): void {
    const tabContainer = container.createDiv('wp-publish-tabs');

    const tabs = [
      { id: 'settings', label: this.plugin.t('publishModal_settingsTab') },
      { id: 'preview', label: this.plugin.t('publishModal_previewTab') }
    ];

    tabs.forEach(tab => {
      const tabEl = tabContainer.createDiv({
        cls: `wp-publish-tab-item ${this.currentTab === tab.id ? 'active' : ''}`
      });
      tabEl.createSpan({ text: tab.label });
      tabEl.onclick = () => {
        this.currentTab = tab.id as 'settings' | 'preview';
        this.display(params);
      };
    });
  }

  // ==================== 设置标签 ====================
  private renderSettingsTab(container: HTMLElement, params: WordPressPostParams): void {
    // AI 标签页区域（包含特色图片、摘要、标签）
    const aiSection = container.createDiv('wp-settings-ai');
    this.renderAIAssistSection(aiSection, params);

    // 基本设置区域
    const bottomSection = container.createDiv('wp-settings-bottom');
    this.renderBasicSettings(bottomSection, params);
  }

  private selectLocalImage(params: WordPressPostParams): void {
    const fileInput = document.createElement('input');
    fileInput.type = 'file';
    fileInput.accept = 'image/*';
    fileInput.onchange = async (e) => {
      const file = (e.target as HTMLInputElement).files?.[0];
      if (file) {
        try {
          let arrayBuffer = await file.arrayBuffer();
          this.featuredImage = {
            fileName: file.name,
            mimeType: file.type,
            content: arrayBuffer,
            width: 1200
          };
          this.imageSource = 'local';
          // 保存到缓存
          await this.saveImageToCache(arrayBuffer, file.name, file.type, 'local');
          this.display(params);
          new Notice(this.t('publishModal_imageSelected_simple'));
        } catch (error) {
          new Notice(this.t('publishModal_imageSelectFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
        }
      }
    };
    fileInput.click();
  }

  private selectUnsplashImage(params: WordPressPostParams): void {
    if (!this.unsplashService) {
      new Notice(this.t('publishModal_unsplashKeyRequiredSimple'));
      return;
    }

    const tagsQuery = this.getSearchQuery(params);
    const targetWidth = this.plugin.settings.imageCropWidth || 1200;
    const ratio = this.plugin.settings.imageCropRatio || '16:9';

    const modal = new UnsplashPickerModal(
      this.app,
      this.plugin,
      this.unsplashService,
      async (image: UnsplashImage, arrayBuffer: ArrayBuffer) => {
        const processed = await resizeFeaturedImage(arrayBuffer, 'image/jpeg', targetWidth, ratio);
        const finalBuffer = processed || arrayBuffer;
        const fileName = `unsplash-${image.id}.jpg`;
        this.featuredImage = {
          fileName,
          mimeType: 'image/jpeg',
          content: finalBuffer,
          width: targetWidth
        };
        this.imageSource = 'unsplash';
        // 保存到缓存
        await this.saveImageToCache(finalBuffer, fileName, 'image/jpeg', 'unsplash');
        this.display(params);
        new Notice(this.t('publishModal_imageSelected_simple'));
      },
      tagsQuery
    );
    modal.open();
  }

  private getSearchQuery(params: WordPressPostParams): string {
    const frontmatterTag = this.matterData.tag;

    if (Array.isArray(frontmatterTag) && frontmatterTag.length > 0) {
      return String(frontmatterTag[0]);
    }

    if (typeof frontmatterTag === 'string' && frontmatterTag) {
      return frontmatterTag;
    }

    return params.tags?.[0] ? String(params.tags[0]) : '';
  }

  private async generateAImage(params: WordPressPostParams): Promise<void> {
    if (!this.plugin.settings.aiConfig || !this.aiService) {
      new Notice(this.t('publishModal_aiServiceRequired'));
      return;
    }
    if (!this.aiService.hasImageAIKey()) {
      new Notice(this.t('notice_imageAIApiKeyRequired'));
      return;
    }

    try {
      const imagePromptContent = await this.getImagePromptContent(params);
      if (!imagePromptContent) return;

      // 检测文章语言并生成图片描述提示词
      const contentToDetect = this.editableContent || this.articleContent;
      const language = detectLanguage(contentToDetect);
      log.info('Detected language for image generation:', language);

      const basePrompt = this.imageGenerationPrompt || this.plugin.t('defaultPrompt_image');
      const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'image');
      const imageDescriptionPrompt = localizedPrompt
        .replace('{title}', params.title || '')
        .replace('{content}', imagePromptContent);

      new Notice(this.t('publishModal_aiGeneratingImage'));
      const imageUrl = await this.aiService.generateImage(imageDescriptionPrompt);
      const response = await fetch(imageUrl);
      const arrayBuffer = await response.arrayBuffer();

      const fileName = `ai-generated-${Date.now()}.png`;
      this.featuredImage = {
        fileName,
        mimeType: 'image/png',
        content: arrayBuffer,
        width: 1200
      };
      this.imageSource = 'ai';
      // 保存到缓存
      await this.saveImageToCache(arrayBuffer, fileName, 'image/png', 'ai');

      this.display(params);
      new Notice(this.t('publishModal_aiImageGenerated'));
    } catch (error) {
      log.error('AI image generation error:', error);
      new Notice(this.t('publishModal_aiImageGenerateFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
    }
  }

  /**
   * 别名方法：生成特色图片（用于新的 AI 标签页）
   */
  private async generateFeaturedImage(params: WordPressPostParams): Promise<void> {
    return this.generateAImage(params);
  }

  private async getImagePromptContent(params: WordPressPostParams): Promise<string | null> {
    // Priority: excerpt > tags > generate summary
    if (params.excerpt) {
      return params.excerpt;
    }

    if (params.tags?.length) {
      return params.tags.join(', ');
    }

    // Generate summary first
    if (!this.aiService) {
      new Notice(this.t('notice_aiConfigRequired'));
      return null;
    }
    if (!this.aiService.hasTextAIKey()) {
      new Notice(this.t('notice_textAIApiKeyRequired'));
      return null;
    }

    const contentToUse = this.editableContent || this.articleContent;
    if (!contentToUse) {
      new Notice(this.t('publishModal_emptyContent'));
      return null;
    }

    try {
      new Notice(this.t('publishModal_generatingSummary'));
      const cleanContent = this.sanitizeContentForAI(contentToUse, 2000);

      // 检测文章语言并适配提示词
      const language = detectLanguage(cleanContent);
      log.info('Detected language for image summary:', language);
      const basePrompt = this.summaryPrompt || this.plugin.t('defaultPrompt_summary');
      const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'summary');
      const prompt = localizedPrompt.replace('{content}', cleanContent);

      const summary = await this.aiService.generateText(prompt);
      params.excerpt = summary.trim();
      new Notice(this.t('publishModal_generatingSummary'));
      this.display(params);
      return params.excerpt;
    } catch (error) {
      log.error('Generate summary for image error:', error);
      new Notice(this.t('publishModal_summaryGenerateFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
      return null;
    }
  }

  private selectVaultImage(params: WordPressPostParams): void {
    const modal = new VaultImagePickerModal(
      this.app,
      this.plugin,
      async (file: TFile, arrayBuffer: ArrayBuffer, mimeType: string) => {
        this.featuredImage = {
          fileName: file.name,
          mimeType: mimeType,
          content: arrayBuffer,
          width: 1200
        };
        this.imageSource = 'vault';
        // 保存到缓存
        await this.saveImageToCache(arrayBuffer, file.name, mimeType, 'vault');
        this.display(params);
        new Notice(this.t('publishModal_imageFromGallery', { fileName: file.name }));
      }
    );
    modal.open();
  }

  /**
   * 为 Setting 添加信息按钮
   */
  private addInfoButton(setting: Setting, infoKey: TranslateKey): void {
    setting.addExtraButton(btn => {
      btn.setIcon('info')
        .setTooltip(this.t(infoKey))
        .onClick(() => {
          new Notice(this.t(infoKey), 5000);
        });
      btn.extraSettingsEl.addClass('wp-info-button');
    });
  }

  private renderBasicSettings(container: HTMLElement, params: WordPressPostParams): void {
    const card = container.createDiv('wp-settings-card');
    card.createEl('h3', { text: this.plugin.t('publishModal_basicSettings'), cls: 'wp-settings-section-title' });

    // 标题
    const titleSetting = new Setting(card)
      .setName(this.t('publishModal_titleName'))
      .addText(text => {
        this.titleInput = text.inputEl;
        text.setPlaceholder(this.t('publishModal_titlePlaceholder'))
          .setValue(params.title || '')
          .onChange(value => {
            params.title = value;
          });
        text.inputEl.style.width = '100%';

        // 自动更新 slug 的通用逻辑
        const autoUpdateSlug = () => {
          if (this.plugin.settings.autoGenerateSlug && this.slugInput) {
            // Only regenerate if current slug matches the last auto-generated one (not manually modified)
            if (!this.lastAutoGeneratedSlug || params.slug === this.lastAutoGeneratedSlug) {
              this.generateDefaultSlug(params.title, params);
              this.lastAutoGeneratedSlug = params.slug || '';
              new Notice(this.t('publishModal_slugAutoUpdated'));
            }
          }
        };

        // 按下回车时触发 slug 自动更新
        text.inputEl.addEventListener('keydown', (e) => {
          if (e.key === 'Enter') {
            e.preventDefault();
            autoUpdateSlug();
          }
        });

        // 失去焦点时触发 slug 自动更新
        text.inputEl.addEventListener('blur', () => {
          autoUpdateSlug();
        });
      });

    // 添加标题信息按钮
    this.addInfoButton(titleSetting, 'publishModal_titleInfo');

    // Slug
    const slugSetting = new Setting(card)
      .setName(this.t('publishModal_slugName'));

    // Track the initial slug value to detect manual edits
    const initialSlugValue = params.slug;

    slugSetting.addText(text => {
      this.slugInput = text.inputEl;
      text.setPlaceholder(this.t('publishModal_slugPlaceholder'))
        .setValue(params.slug || '')
        .onChange(value => {
          const sanitized = SlugGenerator.sanitizeSlug(value);
          params.slug = sanitized;
          // Clear the auto-generated slug reference if user manually edits
          // This prevents further auto-updates on title change
          if (sanitized && initialSlugValue && sanitized !== initialSlugValue) {
            this.lastAutoGeneratedSlug = '';
          }
        });
      text.inputEl.style.width = '100%';
    });

    // AI翻译按钮
    if (this.plugin.settings.slugGenerationMode === 'ai-translate') {
      if (!this.plugin.settings.aiConfig) {
        slugSetting.addButton(btn => {
          btn.setButtonText(this.t('publishModal_slugAIButtonNeedConfig'))
            .setTooltip(this.t('publishModal_aiServiceRequired'))
            .setDisabled(true);
        });
      } else if (!this.aiService?.hasTextAIKey()) {
        slugSetting.addButton(btn => {
          btn.setButtonText(this.t('publishModal_slugAIButtonNeedConfig'))
            .setTooltip(this.t('notice_textAIApiKeyRequired'))
            .setDisabled(true);
        });
      } else {
        slugSetting.addButton(btn => {
          btn.setButtonText(this.t('publishModal_slugAIButton'))
            .setTooltip(this.t('publishModal_slugAIButton'))
            .onClick(async () => {
              if (!params.title) {
                new Notice(this.t('publishModal_slugNeedTitle'));
                return;
              }

              btn.setDisabled(true);
              btn.setButtonText(this.t('publishModal_slugAIButtonTranslating'));

              try {
                const slug = await this.aiService!.translateToSlug(params.title);
                if (this.slugInput) {
                  this.slugInput.value = slug;
                  params.slug = slug;
                }
                new Notice(this.t('publishModal_slugGenerated'));
              } catch (error) {
                new Notice(this.t('publishModal_slugTranslateFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
              } finally {
                btn.setDisabled(false);
                btn.setButtonText(this.t('publishModal_slugAIButton'));
              }
            });
        });
      }
    }

    // 添加 Slug 信息按钮
    this.addInfoButton(slugSetting, 'publishModal_slugInfo');

    // 分类（仅Post类型）
    // 先过滤掉空值的分类项
    const validCategories = this.categories.items.filter(it => it.name && it.name.trim());

    if (params.postType === PostTypeConst.Post && validCategories.length > 0) {
      // 创建分类设置标题（不使用 Setting 组件，避免移动端布局问题）
      const categoryHeader = card.createDiv('wp-category-header');

      // 创建标题行容器
      const titleRow = categoryHeader.createDiv('wp-category-title-row');
      titleRow.createEl('div', { cls: 'setting-item-name', text: this.t('publishModal_categoryName') });

      // 创建信息按钮
      const infoBtn = titleRow.createEl('button', { cls: 'wp-info-button clickable-icon' });
      infoBtn.setAttribute('aria-label', this.t('publishModal_categoryInfo'));
      setIcon(infoBtn, 'info');
      infoBtn.addEventListener('click', () => {
        new Notice(this.t('publishModal_categoryInfo'), 5000);
      });

      // 创建分类标签容器
      const tagsContainer = document.createElement('div');
      tagsContainer.className = 'wp-category-tags-container';
      categoryHeader.appendChild(tagsContainer);

      // 可用分类列表（排除已选中的）
      const getAvailableCategories = () => {
        return validCategories.filter(cat =>
          !params.categories.includes(Number(cat.id))
        );
      };

      // 渲染已选分类标签
      const renderCategoryTags = () => {
        tagsContainer.empty();

        // 显示已选分类
        params.categories.forEach(catId => {
          const cat = validCategories.find(c => Number(c.id) === catId);
          if (cat) {
            const tag = tagsContainer.createEl('span', {
              cls: 'wp-category-tag',
              text: cat.name
            });

            // 删除按钮
            const removeBtn = tag.createEl('span', {
              cls: 'wp-category-tag-remove',
              text: '×'
            });
            removeBtn.onclick = (e) => {
              e.stopPropagation();
              params.categories = params.categories.filter(id => id !== catId);
              renderCategoryTags();
              renderAddDropdown();
            };
          }
        });
      };

      // 渲染添加下拉框
      const renderAddDropdown = () => {
        // 移除旧的添加控件
        const oldAddControl = tagsContainer.querySelector('.wp-category-add-control');
        if (oldAddControl) oldAddControl.remove();

        const available = getAvailableCategories();
        if (available.length > 0) {
          const addControl = tagsContainer.createEl('div', {
            cls: 'wp-category-add-control'
          });

          const addBtn = addControl.createEl('button', {
            cls: 'wp-category-add-btn',
            text: '+'
          });

          addBtn.onclick = () => {
            // 创建下拉选择
            const select = addControl.createEl('select', {
              cls: 'wp-category-dropdown'
            });

            // 添加占位选项
            select.createEl('option', {
              value: '',
              text: this.t('publishModal_selectCategory') || '选择分类...'
            });

            available.forEach(cat => {
              select.createEl('option', {
                value: String(cat.id),
                text: cat.name
              });
            });

            select.onchange = () => {
              if (select.value) {
                params.categories.push(Number(select.value));
                renderCategoryTags();
                renderAddDropdown();
              }
            };

            select.focus();
            addBtn.style.display = 'none';
          };
        }
      };

      // 初始渲染
      renderCategoryTags();
      renderAddDropdown();

      // 如果没有选择分类，默认选中"未分类"
      if (params.categories.length === 0) {
        const uncategorized = validCategories.find(it =>
          it.name === this.plugin.t('publishModal_uncategorized') ||
          it.name === 'Uncategorized' ||
          it.name === '未分类'
        );
        if (uncategorized) {
          params.categories = [Number(uncategorized.id)];
          renderCategoryTags();
          renderAddDropdown();
        }
      }
    }

    // 发布状态 - preserve slug on state change
    new Setting(card)
      .setName(this.t('publishModal_statusName'))
      .setDesc(this.t('publishModal_statusDesc'))
      .addDropdown((dropdown) => {
        dropdown
          .addOption(PostStatus.Draft, this.plugin.t('publishModal_statusDraft'))
          .addOption(PostStatus.Publish, this.plugin.t('publishModal_statusPublish'))
          .addOption(PostStatus.Private, this.plugin.t('publishModal_statusPrivate'))
          .addOption(PostStatus.Future, this.plugin.t('publishModal_statusFuture'))
          .setValue(params.status)
          .onChange((value) => {
            params.status = value as PostStatus;
            // Do NOT clear slug or other fields when changing status
            this.display(params);
          });
      });

    // 定时发布日期
    if (params.status === PostStatus.Future) {
      new Setting(card)
        .setName(this.t('publishModal_postDateTimeName'))
        .setDesc(this.t('publishModal_postDateTimeDescFormat'))
        .addText(text => {
          text.setValue(format(new Date(), 'yyyy-MM-dd HH:mm:ss'));
          this.setupDateMask(text.inputEl, params);
        });
    } else {
      delete params.datetime;
    }

    // 评论状态
    new Setting(card)
      .setName(this.t('publishModal_commentName'))
      .setDesc(this.t('publishModal_commentDesc'))
      .addDropdown((dropdown) => {
        dropdown
          .addOption(CommentStatus.Open, this.plugin.t('publishModal_commentOpen'))
          .addOption(CommentStatus.Closed, this.plugin.t('publishModal_commentClosed'))
          .setValue(params.commentStatus)
          .onChange((value) => {
            params.commentStatus = value as CommentStatus;
          });
      });

    // 发布为Markdown选项
    new Setting(card)
      .setName(this.t('publishModal_postTypeName'))
      .setDesc(this.t('publishModal_postTypeDesc'))
      .addDropdown((dropdown) => {
        dropdown
          .addOption('html', this.plugin.t('publishModal_formatHTML'))
          .addOption('markdown', this.plugin.t('publishModal_formatMarkdown'))
          .setValue('html')
          .onChange((value) => {
            (params as SafeAny).contentFormat = value;
          });
      });

    // 发布为新文章选项（仅当已有关联文章时显示）
    if (this.matterData.postId) {
      new Setting(card)
        .setName(this.t('publishModal_publishAsNewName'))
        .setDesc(this.t('publishModal_publishAsNewDesc'))
        .addToggle((toggle) => {
          toggle
            .setValue(params.publishAsNew || false)
            .onChange((value) => {
              params.publishAsNew = value;
            });
        });
    }
  }

  // ==================== AI 辅助区域 ====================
  private renderAIAssistSection(container: HTMLElement, params: WordPressPostParams): void {
    const card = container.createDiv('wp-settings-card');

    // AI 标签页导航
    this.renderAITabBar(card, params);

    // AI 标签页内容
    const aiContentContainer = card.createDiv('wp-ai-tab-content');

    if (this.currentAITab === 'featured-image') {
      this.renderAIFeaturedImageTab(aiContentContainer, params);
    } else if (this.currentAITab === 'excerpt') {
      this.renderAIExcerptTab(aiContentContainer, params);
    } else if (this.currentAITab === 'tags') {
      this.renderAITagsTab(aiContentContainer, params);
    }
  }

  /**
   * 渲染 AI 标签页导航栏
   */
  private renderAITabBar(container: HTMLElement, params: WordPressPostParams): void {
    const tabContainer = container.createDiv('wp-ai-tabs');

    const tabs = [
      { id: 'featured-image', label: this.plugin.t('publishModal_featuredImage') },
      { id: 'excerpt', label: this.plugin.t('publishModal_aiExcerpt') },
      { id: 'tags', label: this.plugin.t('publishModal_aiTags') }
    ];

    tabs.forEach(tab => {
      const tabEl = tabContainer.createDiv({
        cls: `wp-ai-tab-item ${this.currentAITab === tab.id ? 'active' : ''}`
      });
      tabEl.createSpan({ text: tab.label });
      tabEl.onclick = () => {
        this.currentAITab = tab.id as 'featured-image' | 'excerpt' | 'tags';
        this.display(params);
      };
    });
  }

  /**
   * 渲染特色图片标签页（从基本设置迁移过来）
   */
  private renderAIFeaturedImageTab(container: HTMLElement, params: WordPressPostParams): void {
    const previewContainer = container.createDiv('featured-image-preview-large');

    // 如果正在加载远程图片，显示加载状态
    if (this.isLoadingRemoteImage) {
      const loadingDiv = previewContainer.createDiv('featured-image-loading');
      loadingDiv.style.display = 'flex';
      loadingDiv.style.flexDirection = 'column';
      loadingDiv.style.alignItems = 'center';
      loadingDiv.style.justifyContent = 'center';
      loadingDiv.style.padding = '40px 20px';
      loadingDiv.style.color = 'var(--text-muted)';

      const spinner = loadingDiv.createDiv('featured-image-spinner');
      spinner.style.width = '32px';
      spinner.style.height = '32px';
      spinner.style.border = '3px solid var(--background-modifier-border)';
      spinner.style.borderTop = '3px solid var(--interactive-accent)';
      spinner.style.borderRadius = '50%';
      spinner.style.animation = 'spin 1s linear infinite';
      spinner.style.marginBottom = '12px';

      loadingDiv.createEl('p', {
        text: this.t('publishModal_loadingRemoteImage') || '正在加载远程图片...',
        cls: 'featured-image-loading-text'
      });

      // 添加 CSS 动画（如果还没有）
      if (!document.getElementById('featured-image-spinner-style')) {
        const style = document.createElement('style');
        style.id = 'featured-image-spinner-style';
        style.textContent = `
          @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
          }
        `;
        document.head.appendChild(style);
      }
    } else if (this.remoteImageLoadFailed) {
      // 如果加载失败，显示错误信息和操作按钮
      const errorDiv = previewContainer.createDiv('featured-image-error');
      errorDiv.style.display = 'flex';
      errorDiv.style.flexDirection = 'column';
      errorDiv.style.alignItems = 'center';
      errorDiv.style.justifyContent = 'center';
      errorDiv.style.padding = '40px 20px';
      errorDiv.style.color = 'var(--text-error)';

      errorDiv.createEl('p', {
        text: '❌ ' + (this.remoteImageError || this.t('publishModal_remoteImageLoadFailed')),
        cls: 'featured-image-error-text'
      });

      const btnRow = errorDiv.createDiv('featured-image-btn-row');
      btnRow.style.marginTop = '16px';

      const retryBtn = btnRow.createEl('button', {
        text: this.t('publishModal_retryLoadImage') || '重试',
        cls: 'feature-btn'
      });
      retryBtn.onclick = async () => {
        if (this.remoteImagePostId) {
          this.remoteImageLoadFailed = false;
          this.remoteImageError = null;
          await this.loadRemoteFeaturedImage(this.remoteImagePostId, params);
        }
      };

      const skipBtn = btnRow.createEl('button', {
        text: this.t('publishModal_skipRemoteImage') || '跳过',
        cls: 'feature-btn'
      });
      skipBtn.onclick = () => {
        this.remoteImageLoadFailed = false;
        this.remoteImageError = null;
        this.remoteImagePostId = null;
        this.display(params);
      };
    } else if (this.featuredImage) {
      // 显示已选择的图片
      const img = previewContainer.createEl('img', {
        cls: 'featured-image-full'
      });
      img.src = `data:${this.featuredImage.mimeType};base64,${this.arrayBufferToBase64(this.featuredImage.content)}`;

      const info = previewContainer.createDiv('featured-image-info');
      info.textContent = `${this.featuredImage.fileName} (${this.formatFileSize(this.featuredImage.content.byteLength)})`;

      const removeBtn = previewContainer.createEl('button', {
        text: this.t('publishModal_removeImage'),
        cls: 'featured-image-remove-btn'
      });
      removeBtn.onclick = async () => {
        this.featuredImage = null;
        this.imageSource = 'auto';
        await this.clearImageCache();
        this.display(params);
      };
    } else {
      // 显示占位符
      previewContainer.createEl('p', {
        text: this.t('publishModal_noImageSelected'),
        cls: 'featured-image-placeholder-text'
      });
    }

    // 操作按钮行
    const btnRow = container.createDiv('featured-image-btn-row');

    // 从库中选择
    const vaultBtn = btnRow.createEl('button', {
      text: '📁 ' + this.t('publishModal_selectFromVault'),
      cls: 'feature-btn'
    });
    vaultBtn.onclick = () => this.selectVaultImage(params);

    // Unsplash
    if (this.unsplashService) {
      const unsplashBtn = btnRow.createEl('button', {
        text: '🖼️ Unsplash',
        cls: 'feature-btn'
      });
      unsplashBtn.onclick = () => this.selectUnsplashImage(params);
    }

    // AI 生成
    if (this.aiService?.hasImageAIKey()) {
      const aiBtn = btnRow.createEl('button', {
        text: '🤖 ' + this.t('publishModal_aiGenerate'),
        cls: 'feature-btn'
      });
      aiBtn.onclick = () => this.generateFeaturedImage(params);
    } else {
      const aiBtn = btnRow.createEl('button', {
        text: '🤖 ' + this.t('publishModal_aiGenerate'),
        cls: 'feature-btn disabled'
      });
      aiBtn.onclick = () => {
        new Notice(this.t('notice_imageAIApiKeyRequired'));
      };
    }
  }

  /**
   * 渲染摘要标签页（支持编辑）
   */
  private renderAIExcerptTab(container: HTMLElement, params: WordPressPostParams): void {
    // AI 生成按钮
    const btnContainer = container.createDiv('wp-ai-buttons');
    const generateBtn = btnContainer.createEl('button', { text: this.t('publishModal_generateSummary') });

    if (!this.aiService) {
      generateBtn.addClass('disabled');
      generateBtn.onclick = () => {
        new Notice(this.t('notice_aiConfigRequired'));
      };
    } else if (!this.aiService.hasTextAIKey()) {
      generateBtn.addClass('disabled');
      generateBtn.onclick = () => {
        new Notice(this.t('notice_textAIApiKeyRequired'));
      };
    } else {
      generateBtn.onclick = () => this.generateSummary(params);
    }

    // 摘要编辑区域
    const excerptEditor = container.createDiv('wp-ai-excerpt-editor');
    excerptEditor.style.marginTop = '16px';

    const label = excerptEditor.createEl('label', {
      text: this.t('publishModal_excerptLabel') || '摘要内容',
      cls: 'wp-ai-editor-label'
    });
    label.style.display = 'block';
    label.style.marginBottom = '8px';
    label.style.fontWeight = '500';
    label.style.color = 'var(--text-normal)';

    const textarea = excerptEditor.createEl('textarea', {
      cls: 'wp-preview-textarea'
    });
    textarea.value = params.excerpt || '';
    textarea.placeholder = this.t('publishModal_excerptPlaceholder') || '在此输入或生成摘要...';
    textarea.style.width = '100%';
    textarea.style.minHeight = '120px';
    textarea.style.padding = '12px';
    textarea.style.borderRadius = '6px';
    textarea.style.border = '1px solid var(--background-modifier-border)';
    textarea.style.backgroundColor = 'var(--background-primary)';
    textarea.style.color = 'var(--text-normal)';
    textarea.style.fontFamily = 'var(--font-text)';
    textarea.style.fontSize = '14px';
    textarea.style.lineHeight = '1.6';
    textarea.style.resize = 'vertical';

    // 实时同步到 params
    textarea.addEventListener('input', () => {
      params.excerpt = textarea.value;
    });
  }

  /**
   * 渲染标签标签页（支持编辑）
   */
  private renderAITagsTab(container: HTMLElement, params: WordPressPostParams): void {
    // AI 生成按钮
    const btnContainer = container.createDiv('wp-ai-buttons');
    const generateBtn = btnContainer.createEl('button', { text: this.t('publishModal_generateTags') });

    if (!this.aiService) {
      generateBtn.addClass('disabled');
      generateBtn.onclick = () => {
        new Notice(this.t('notice_aiConfigRequired'));
      };
    } else if (!this.aiService.hasTextAIKey()) {
      generateBtn.addClass('disabled');
      generateBtn.onclick = () => {
        new Notice(this.t('notice_textAIApiKeyRequired'));
      };
    } else {
      generateBtn.onclick = () => this.generateTags(params);
    }

    // 标签编辑区域
    const tagsEditor = container.createDiv('wp-ai-tags-editor');
    tagsEditor.style.marginTop = '16px';

    const label = tagsEditor.createEl('label', {
      text: this.t('publishModal_tagsLabel') || '标签',
      cls: 'wp-ai-editor-label'
    });
    label.style.display = 'block';
    label.style.marginBottom = '8px';
    label.style.fontWeight = '500';
    label.style.color = 'var(--text-normal)';

    // 标签容器
    const tagsContainer = tagsEditor.createDiv('wp-preview-tags-editable');
    this.tagsContainer = tagsContainer;

    // 初始化可编辑标签数组
    this.editableTags = params.tags ? [...params.tags] : [];

    // 渲染标签
    this.refreshTagsPreview(params);
  }

  private setupDateMask(inputEl: HTMLInputElement, params: WordPressPostParams): void {
    const dateTimeFormat = 'yyyy-MM-dd HH:mm:ss';
    const dateBlocks = {
      yyyy: { mask: IMask.MaskedRange, from: 1970, to: 9999 },
      MM: { mask: IMask.MaskedRange, from: 1, to: 12 },
      dd: { mask: IMask.MaskedRange, from: 1, to: 31 },
    };

    if (this.dateInputMask) {
      this.dateInputMask.destroy();
    }

    this.dateInputMask = IMask(inputEl, [
      {
        mask: Date,
        lazy: false,
        overwrite: true,
        pattern: dateTimeFormat,
        blocks: {
          ...dateBlocks,
          HH: { mask: IMask.MaskedRange, from: 0, to: 23 },
          mm: { mask: IMask.MaskedRange, from: 0, to: 59 },
          ss: { mask: IMask.MaskedRange, from: 0, to: 59 },
        },
        format: (date: SafeAny) => format(date, dateTimeFormat),
        parse: (str: string) => parse(str, dateTimeFormat, new Date())
      }
    ]);

    this.dateInputMask.on('accept', () => {
      if (this.dateInputMask && this.dateInputMask.masked.isComplete) {
        params.datetime = this.dateInputMask.typedValue;
      }
    });
  }

  // ==================== Preview Tab ====================
  private renderPreviewTab(container: HTMLElement, params: WordPressPostParams): void {
    const card = container.createDiv('wp-preview-card');
    card.createEl('h3', { text: this.plugin.t('publishModal_previewTitle'), cls: 'wp-preview-card-title' });

    if (this.isEditingPreview) {
      this.renderPreviewEditor(card);
    } else {
      this.renderPreviewContent(card, params);
    }
  }

  private renderPreviewEditor(card: HTMLElement): void {
    const editorArea = card.createDiv('wp-preview-editor-area');
    const textarea = editorArea.createEl('textarea', {
      cls: 'wp-preview-textarea',
      attr: { placeholder: this.plugin.t('publishModal_previewEditPlaceholder') }
    });
    textarea.value = this.editableContent;
    textarea.style.width = '100%';
    textarea.style.minHeight = '300px';
    textarea.style.fontFamily = 'var(--font-mono)';
    textarea.oninput = () => {
      this.editableContent = textarea.value;
    };
  }

  private renderPreviewContent(card: HTMLElement, params: WordPressPostParams): void {
    // 同步 editableTags 与 params.tags（确保冲突解决后能更新）
    // 如果 params.tags 发生变化，需要重新同步
    const paramsTagsStr = JSON.stringify(params.tags || []);
    const editableTagsStr = JSON.stringify(this.editableTags);
    if (paramsTagsStr !== editableTagsStr) {
      this.editableTags = params.tags ? [...params.tags] : [];
    }

    // Check if featuredImageId exists but no image is loaded
    const hasImageId = this.matterData.featuredImageId && this.matterData.featuredImageId !== '';

    if (hasImageId && !this.featuredImage && !this.autoFeaturedImage) {
      // Warning: featuredImageId exists but no image loaded
      const warningDiv = card.createDiv('wp-preview-warning');
      warningDiv.createEl('strong', { text: '⚠️ ' + this.plugin.t('publishModal_previewInconsistencyWarning') });
      warningDiv.createEl('p', {
        text: this.plugin.t('publishModal_previewInconsistencyDesc'),
        cls: 'wp-preview-warning-desc'
      });
    }

    // 特色图片 - 优先显示用户选择的图片，否则显示自动检测的图片
    const imageToDisplay = this.featuredImage || this.autoFeaturedImage;
    if (imageToDisplay) {
      this.renderFeaturedImagePreview(card, imageToDisplay);
    } else if (this.matterData.featurePicture) {
      this.renderUploadedImagePreview(card, this.matterData.featurePicture as string);
    }

    // 摘要
    if (params.excerpt) {
      this.renderExcerptPreview(card, params.excerpt);
    }

    // 标签（使用可编辑的标签数组）
    this.renderTagsPreview(card, params);

    // 文章内容
    this.renderArticlePreview(card);
  }

  private renderFeaturedImagePreview(card: HTMLElement, image: FeaturedImageResult): void {
    const section = this.createImageSection(card, this.plugin.t('publishModal_previewFeaturedImage'));
    const blob = new Blob([image.content], { type: image.mimeType });
    const url = URL.createObjectURL(blob);
    this.createPreviewImage(section, url);
  }

  private renderUploadedImagePreview(card: HTMLElement, imageUrl: string): void {
    const section = this.createImageSection(card, this.plugin.t('publishModal_previewFeaturedImageUploaded'));
    this.createPreviewImage(section, imageUrl);
  }

  private createImageSection(card: HTMLElement, labelText: string): HTMLElement {
    const section = card.createDiv('wp-preview-featured-image');
    section.style.marginBottom = '16px';
    section.style.textAlign = 'center';

    const label = section.createEl('div', { text: labelText });
    label.style.fontSize = '12px';
    label.style.color = 'var(--text-muted)';
    label.style.marginBottom = '8px';

    return section;
  }

  private createPreviewImage(section: HTMLElement, src: string): void {
    const imgContainer = section.createDiv();
    Object.assign(imgContainer.style, {
      maxWidth: '100%',
      borderRadius: '8px',
      overflow: 'hidden',
      border: '1px solid var(--background-modifier-border)'
    });

    const img = imgContainer.createEl('img', { attr: { src } });
    Object.assign(img.style, {
      maxWidth: '100%',
      maxHeight: '180px',
      objectFit: 'cover',
      display: 'block',
      width: '100%'
    });
  }

  private renderExcerptPreview(card: HTMLElement, excerpt: string): void {
    const section = card.createDiv('wp-preview-excerpt');
    Object.assign(section.style, {
      padding: '10px 14px',
      backgroundColor: 'var(--background-secondary)',
      borderRadius: '6px',
      marginBottom: '16px',
      fontSize: '13px',
      color: 'var(--text-muted)',
      borderLeft: '3px solid var(--interactive-accent)'
    });
    section.createEl('strong', { text: this.plugin.t('publishModal_previewSummary') });
    section.createSpan({ text: excerpt });
  }

  private renderTagsPreview(card: HTMLElement, params: WordPressPostParams): void {
    // 如果容器已存在，清空内容复用；否则创建新容器
    let section: HTMLElement;
    if (this.tagsContainer && this.tagsContainer.parentElement === card) {
      // 容器存在且父元素正确，清空内容复用
      section = this.tagsContainer;
      section.empty();
    } else {
      // 容器不存在或父元素不对，创建新容器
      section = card.createDiv('wp-preview-tags-editable');
      this.tagsContainer = section;
      Object.assign(section.style, {
        marginBottom: '16px',
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
        alignItems: 'center',
        padding: '12px',
        backgroundColor: 'var(--background-primary)',
        borderRadius: '6px',
        border: '1px solid var(--background-modifier-border)'
      });
    }

    const label = section.createEl('span', { text: this.plugin.t('publishModal_previewTags') });
    Object.assign(label.style, {
      fontSize: '12px',
      color: 'var(--text-muted)',
      fontWeight: '500'
    });

    // 渲染现有标签
    this.editableTags.forEach((tag) => {
      this.renderTagItem(section, tag, params);
    });

    // 添加"+"按钮
    this.renderAddTagButton(section, params);
  }

  /**
   * 渲染单个标签项（带删除按钮）
   */
  private renderTagItem(container: HTMLElement, tag: string, params: WordPressPostParams): void {
    const tagEl = container.createEl('span');
    tagEl.addClass('wp-tag-item');
    const bgColor = getTagColor(tag);
    Object.assign(tagEl.style, {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '4px',
      padding: '4px 10px',
      backgroundColor: bgColor,
      color: '#fff',
      borderRadius: '12px',
      fontSize: '12px',
      fontWeight: '500',
      cursor: 'default',
      transition: 'all 0.2s ease'
    });

    // 标签文本
    const textSpan = tagEl.createEl('span', { text: tag });
    textSpan.addClass('wp-tag-text');

    // 删除按钮
    const removeBtn = tagEl.createEl('span', { text: '×' });
    removeBtn.addClass('wp-tag-remove');
    Object.assign(removeBtn.style, {
      cursor: 'pointer',
      fontSize: '16px',
      fontWeight: 'bold',
      lineHeight: '1',
      opacity: '0.7',
      transition: 'opacity 0.2s ease'
    });

    removeBtn.addEventListener('mouseenter', () => {
      removeBtn.style.opacity = '1';
    });

    removeBtn.addEventListener('mouseleave', () => {
      removeBtn.style.opacity = '0.7';
    });

    removeBtn.addEventListener('click', (e) => {
      e.stopPropagation();
      this.removeTag(tag, params);
    });

    // 标签悬停效果
    tagEl.addEventListener('mouseenter', () => {
      tagEl.style.transform = 'translateY(-1px)';
      tagEl.style.boxShadow = 'var(--wp-shadow-hover)';
    });

    tagEl.addEventListener('mouseleave', () => {
      tagEl.style.transform = 'translateY(0)';
      tagEl.style.boxShadow = 'none';
    });
  }

  /**
   * 渲染添加标签按钮
   */
  private renderAddTagButton(container: HTMLElement, params: WordPressPostParams): void {
    const addBtn = container.createEl('span', { text: '+' });
    addBtn.addClass('wp-tag-add-btn');
    Object.assign(addBtn.style, {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '24px',
      height: '24px',
      backgroundColor: 'var(--interactive-accent)',
      color: 'var(--text-on-accent)',
      borderRadius: '50%',
      fontSize: '18px',
      fontWeight: 'bold',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      lineHeight: '1'
    });

    addBtn.addEventListener('mouseenter', () => {
      addBtn.style.transform = 'scale(1.1)';
      addBtn.style.backgroundColor = 'var(--interactive-accent-hover)';
    });

    addBtn.addEventListener('mouseleave', () => {
      addBtn.style.transform = 'scale(1)';
      addBtn.style.backgroundColor = 'var(--interactive-accent)';
    });

    addBtn.addEventListener('click', () => {
      this.showTagInput(container, addBtn, params);
    });
  }

  /**
   * 显示标签输入框
   */
  private showTagInput(container: HTMLElement, addBtn: HTMLElement, params: WordPressPostParams): void {
    // 隐藏加号按钮
    addBtn.style.display = 'none';

    // 创建输入框
    const input = container.createEl('input');
    input.addClass('wp-tag-input');
    input.type = 'text';
    input.placeholder = this.plugin.t('publishModal_tagInputPlaceholder') || '输入标签名...';
    Object.assign(input.style, {
      padding: '4px 10px',
      fontSize: '12px',
      border: '1px solid var(--interactive-accent)',
      borderRadius: '12px',
      outline: 'none',
      minWidth: '120px',
      backgroundColor: 'var(--background-primary)',
      color: 'var(--text-normal)'
    });

    input.focus();

    // 标志位，防止重复添加
    let tagAdded = false;

    // 监听 Enter 键
    input.addEventListener('keydown', (e) => {
      if (e.key === 'Enter') {
        e.preventDefault();
        const tagName = input.value.trim();
        if (tagName && !tagAdded) {
          this.addTag(tagName, params);
          tagAdded = true;
        }
        input.remove();
        addBtn.style.display = 'inline-flex';
      } else if (e.key === 'Escape') {
        tagAdded = true; // 取消时也设置标志，防止 blur 触发
        input.remove();
        addBtn.style.display = 'inline-flex';
      }
    });

    // 监听失焦事件
    input.addEventListener('blur', () => {
      setTimeout(() => {
        if (!tagAdded) {
          const tagName = input.value.trim();
          if (tagName) {
            this.addTag(tagName, params);
            tagAdded = true;
          }
        }
        input.remove();
        addBtn.style.display = 'inline-flex';
      }, 200);
    });
  }

  /**
   * 删除标签（通过标签名而不是索引）
   */
  private removeTag(tagName: string, params: WordPressPostParams): void {
    const index = this.editableTags.indexOf(tagName);
    if (index > -1) {
      this.editableTags.splice(index, 1);
      // 同步到 params
      params.tags = [...this.editableTags];
      this.refreshTagsPreview(params);
    }
  }

  /**
   * 添加标签
   */
  private addTag(tagName: string, params: WordPressPostParams): void {
    const trimmed = tagName.trim();
    if (!trimmed) return;

    // 去重检查
    if (this.editableTags.includes(trimmed)) {
      new Notice(this.plugin.t('publishModal_tagExists') || '标签已存在');
      return;
    }

    this.editableTags.push(trimmed);
    // 同步到 params
    params.tags = [...this.editableTags];
    this.refreshTagsPreview(params);

    // 提示标签已添加
    new Notice(this.plugin.t('publishModal_tagAdded') || '标签已添加');
  }

  /**
   * 刷新标签预览
   */
  private refreshTagsPreview(params: WordPressPostParams): void {
    if (!this.tagsContainer) return;
    const card = this.tagsContainer.parentElement;
    if (!card) return;
    this.renderTagsPreview(card, params);
  }

  private renderArticlePreview(card: HTMLElement): void {
    const previewContent = card.createDiv('wp-preview-rendered');
    const html = AppState.markdownParser.render(this.editableContent);
    previewContent.innerHTML = html;

    const style = document.createElement('style');
    style.textContent = `
      .wp-preview-rendered h1, .wp-preview-rendered h2, .wp-preview-rendered h3 {
        margin-top: 1em; margin-bottom: 0.5em; font-weight: 600;
      }
      .wp-preview-rendered p { margin-bottom: 1em; line-height: 1.6; }
      .wp-preview-rendered img { max-width: 100%; max-height: 300px; object-fit: contain; height: auto; }
      .wp-preview-rendered code {
        background: var(--background-secondary); padding: 2px 4px; border-radius: 3px;
      }
      .wp-preview-rendered pre {
        background: var(--background-secondary); padding: 12px; border-radius: 5px; overflow-x: auto;
      }
      .wp-preview-rendered blockquote {
        border-left: 3px solid var(--text-accent); padding-left: 12px; color: var(--text-muted);
      }
    `;
    previewContent.appendChild(style);
  }

  // ==================== Advanced Settings Tab ====================

  // ==================== API Warning Display ====================
  private renderApiWarning(container: HTMLElement, apiType: string): void {
    const warningContainer = container.createDiv('wp-api-warning');
    warningContainer.addClass('mod-warning');
    
    const capabilities = getApiCapabilities(apiType as any);
    const limitations = getApiLimitations(apiType as any);
    const recommendation = getApiRecommendation(apiType as any);
    
    // 警告标题
    const title = warningContainer.createDiv('wp-api-warning-title');
    title.createEl('strong', { text: '⚠️ API Limitations: Using XML-RPC' });
    
    // 限制列表
    if (limitations.length > 0) {
      const list = warningContainer.createEl('ul', { cls: 'wp-api-limitations' });
      limitations.forEach(limitation => {
        list.createEl('li', { text: limitation });
      });
    }
    
    // 推荐
    const rec = warningContainer.createDiv('wp-api-recommendation');
    rec.createEl('p', { text: `Recommendation: ${recommendation}` });
    
    // 了解更多链接
    const learnMore = warningContainer.createDiv('wp-api-learn-more');
    learnMore.createEl('a', {
      text: 'Learn more about API differences',
      href: '#',
      cls: 'external-link'
    }).onclick = (e) => {
      e.preventDefault();
      this.showApiInfoModal(apiType);
    };
  }
  
  private showApiInfoModal(apiType: string): void {
    const capabilities = getApiCapabilities(apiType as any);
    const limitations = getApiLimitations(apiType as any);
    const recommendation = getApiRecommendation(apiType as any);
    
    const message = `
# API Capabilities: ${apiType}

## Supported Features
${capabilities.supportsCategoryCreation ? '✅ Category Creation' : '❌ Category Creation'}
${capabilities.supportsTagCreation ? '✅ Tag Creation' : '❌ Tag Creation'}
${capabilities.supportsRichCategoryProperties ? '✅ Rich Category Properties' : '❌ Rich Category Properties'}
${capabilities.supportsBatchOperations ? '✅ Batch Operations' : '❌ Batch Operations'}
${capabilities.supportsCustomPostTypes ? '✅ Custom Post Types' : '❌ Custom Post Types'}

## Limitations
${limitations.map(l => `• ${l}`).join('\n')}

## Recommendation
${recommendation}

## Security Note
XML-RPC uses basic authentication which may be less secure than REST API with Application Passwords.
Consider migrating to REST API for better security and feature support.
    `;
    
    // 使用内置的confirm modal显示信息
    const modal = this.plugin.app.workspace.activeLeaf?.view.containerEl.createEl('div');
    if (modal) {
      modal.innerHTML = `
        <div class="modal-bg" style="position:fixed;top:0;left:0;width:100%;height:100%;background:var(--wp-modal-overlay);z-index:9999;">
          <div class="modal" style="position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);background:var(--background-primary);padding:20px;border-radius:8px;max-width:600px;max-height:80vh;overflow:auto;">
            <div class="modal-header" style="display:flex;justify-content:space-between;align-items:center;margin-bottom:15px;">
              <h3 style="margin:0;">API Information</h3>
              <button class="modal-close" style="background:none;border:none;font-size:20px;cursor:pointer;">×</button>
            </div>
            <div class="modal-content">${message}</div>
            <div class="modal-footer" style="margin-top:15px;text-align:right;">
              <button class="mod-cta" style="padding:5px 15px;">Close</button>
            </div>
          </div>
        </div>
      `;
      
      // 添加关闭事件
      modal.querySelector('.modal-close')?.addEventListener('click', () => modal.remove());
      modal.querySelector('.mod-cta')?.addEventListener('click', () => modal.remove());
      modal.querySelector('.modal-bg')?.addEventListener('click', (e) => {
        if (e.target === modal.querySelector('.modal-bg')) {
          modal.remove();
        }
      });
    }
  }

  // ==================== Bottom Action Bar ====================
  private renderBottomBar(container: HTMLElement, params: WordPressPostParams): void {
    const bottomContainer = container.createDiv('wp-publish-bottom-bar');

    if (this.currentTab === 'preview') {
      const editBtn = bottomContainer.createEl('button', {
        text: this.isEditingPreview ? this.plugin.t('publishModal_saveButton') : this.plugin.t('publishModal_editButton'),
        cls: 'mod-cta'
      });
      editBtn.onclick = () => {
        if (this.isEditingPreview) {
          this.isEditingPreview = false;
          new Notice(this.t('publishModal_contentSaved'));
        } else {
          this.isEditingPreview = true;
        }
        this.display(params);
      };

      const publishBtn = bottomContainer.createEl('button', {
        text: this.t('publishModal_publishButton'),
        cls: 'mod-cta publish-btn'
      });
      this.publishBtn = publishBtn;
      publishBtn.onclick = () => this.doPublish(params, publishBtn);
    } else {
      const publishBtn = bottomContainer.createEl('button', {
        text: this.t('publishModal_publishButton'),
        cls: 'mod-cta publish-btn-full'
      });
      this.publishBtn = publishBtn;
      publishBtn.onclick = () => this.doPublish(params, publishBtn);
    }
  }

  private sanitizeContentForAI(content: string, maxLen: number = 2000): string {
    let cleaned = content
      .replace(/^---[\s\S]*?---\n?/m, '') // frontmatter
      .replace(/```[\s\S]*?```/g, '')     // code blocks
      .replace(/!\[.*?\]\(.*?\)/g, '')    // md images
      .replace(/!\[\[.*?\]\]/g, '')       // wiki images
      .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1') // md links -> text only
      .replace(/\[\[([^\]|]*)\|?([^\]]*)\]\]/g, '$2$1') // wiki links
      .replace(/#{1,6}\s*/g, '')          // headers
      .replace(/[*_~`]+/g, '')            // emphasis
      .replace(/\n{3,}/g, '\n\n')         // multiple newlines
      .trim();
    return cleaned.substring(0, maxLen);
  }

  private async generateSummary(params: WordPressPostParams): Promise<void> {
    if (!this.aiService) {
      new Notice(this.t('publishModal_aiServiceRequired'));
      return;
    }
    if (!this.aiService.hasTextAIKey()) {
      new Notice(this.t('notice_textAIApiKeyRequired'));
      return;
    }

    const contentToUse = this.editableContent || this.articleContent;
    if (!contentToUse) {
      new Notice(this.t('publishModal_emptyContentForTags'));
      return;
    }

    try {
      new Notice(this.t('publishModal_generatingSummary'));
      const cleanContent = this.sanitizeContentForAI(contentToUse, 2000);
      log.info('Generating summary from content length:', cleanContent.length);

      // 检测文章语言并适配提示词
      const language = detectLanguage(cleanContent);
      log.info('Detected language:', language);
      const basePrompt = this.summaryPrompt || this.plugin.t('defaultPrompt_summary');
      const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'summary');
      const prompt = localizedPrompt.replace('{content}', cleanContent);

      const summary = await this.aiService.generateText(prompt);
      params.excerpt = summary.trim();
      new Notice(this.t('publishModal_summaryGenerated', { summary: params.excerpt.substring(0, 50) }));
      this.display(params);
    } catch (error) {
      log.error('Generate summary error:', error);
      new Notice(this.t('publishModal_summaryGenerateFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
    }
  }

  private async generateTags(params: WordPressPostParams): Promise<void> {
    if (!this.aiService) {
      new Notice(this.t('notice_aiConfigRequired'));
      return;
    }
    if (!this.aiService.hasTextAIKey()) {
      new Notice(this.t('notice_textAIApiKeyRequired'));
      return;
    }

    const contentToUse = this.editableContent || this.articleContent;
    if (!contentToUse) {
      new Notice(this.t('publishModal_emptyContentForTags'));
      return;
    }

    try {
      new Notice(this.t('publishModal_generatingTags'));
      const cleanContent = this.sanitizeContentForAI(contentToUse, 2000);
      log.info('Generating tags from content length:', cleanContent.length);

      // 检测文章语言并适配提示词
      const language = detectLanguage(cleanContent);
      log.info('Detected language:', language);
      const basePrompt = this.tagsPrompt || this.plugin.t('defaultPrompt_tags');
      const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'tags');
      const prompt = localizedPrompt.replace('{content}', cleanContent);

      const tags = await this.aiService.generateText(prompt);
      params.tags = tags.split(/[,，]/).map(t => t.trim()).filter(t => t).slice(0, 4);
      new Notice(this.t('publishModal_tagsGenerated', { tags: params.tags.join(', ') }));
      this.display(params);
    } catch (error) {
      log.error('Generate tags error:', error);
      new Notice(this.t('publishModal_tagsGenerateFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
    }
  }

  private doPublish(params: WordPressPostParams, btn?: HTMLButtonElement): void {
    // 防止重复点击
    if (this.isPublishing) {
      log.info('Already publishing, ignoring click');
      return;
    }

    this.isPublishing = true;
    // 保存参数以便重试
    this.lastPublishParams = params;

    // Pass edited content via params, NOT via frontmatter
    params.content = this.editableContent;

    // 同步可编辑标签到发布参数
    if (this.editableTags.length > 0) {
      params.tags = [...this.editableTags];
    }

    // 隐藏模态窗口，显示全屏进度条
    this.modalEl.style.display = 'none';
    const progressOverlay = this.showPublishProgress();

    const doSubmit = () => {
      if (this.matterData.postType
        && this.matterData.postType !== PostTypeConst.Post
        && (this.matterData.tags || this.matterData.categories)
      ) {
        return openConfirmModal({
          message: this.t('publishModal_wrongMatterDataForPage')
        }, this.plugin)
          .then(result => {
            if (result.code === ConfirmCode.Confirm) {
              return this.onSubmit(params, fm => {
                delete fm.categories;
                delete fm.tags;
              }, this.featuredImage || undefined);
            }
            throw new Error('User cancelled');
          });
      } else {
        return new Promise<void>((resolve, reject) => {
          try {
            this.onSubmit(params, fm => {
              // Save excerpt and tags to frontmatter via callback
              if (params.excerpt) {
                fm.excerpt = params.excerpt;
              }
              if (params.tags && params.tags.length > 0) {
                // 根据用户设置格式化标签
                fm.tags = TagFormatter.formatTags(
                  params.tags,
                  this.plugin.settings.tagFormat
                );
              }
            }, this.featuredImage || undefined);
            resolve();
          } catch (e) {
            reject(e);
          }
        });
      }
    };

    doSubmit()
      .then(() => {
        // 发布成功 - 移除进度条
        progressOverlay.remove();
        // 显示纸屑烟花特效
        this.showConfetti();
        // 显示成功提示
        this.showSuccessNotice();
      })
      .catch(err => {
        log.error('Publish error:', err);
        progressOverlay.remove();
        if (err instanceof Error && err.message !== 'User cancelled') {
          // 显示失败提示卡片
          this.showErrorCard(err.message);
        } else {
          this.close();
        }
        this.isPublishing = false;
      });
  }

  /**
   * 显示全屏发布进度条
   */
  private showPublishProgress(): HTMLElement {
    const overlay = document.body.createDiv('wp-publish-overlay');

    const container = overlay.createDiv('wp-publish-progress-container');

    // 进度动画
    const spinner = container.createDiv('wp-publish-spinner');
    spinner.createSpan({ cls: 'wp-spinner-cat' });

    // Progress text
    const text = container.createDiv('wp-publish-progress-text');
    text.textContent = this.plugin.t('publishModal_publishingProgress');

    // 进度条背景动画
    const progressBar = container.createDiv('wp-publish-progress-bar');
    progressBar.createDiv('wp-publish-progress-fill');

    return overlay;
  }

  /**
   * 显示发布成功提示
   */
  private showSuccessNotice(): void {
    new Notice(this.t('publishModal_publishSuccess'), 5000);
    // 延迟关闭窗口，让用户看到成功提示
    setTimeout(() => {
      this.close();
    }, 2000);
  }

  /**
   * 显示纸屑烟花特效
   */
  private showConfetti(): void {
    const container = document.body.createDiv('wp-confetti-container');

    // 创建多个彩色纸屑
    const colors = ['#ff6b6b', '#ffd93d', '#6bcb77', '#4d96ff', '#9c88ff', '#ff9ff3', '#54a0ff', '#5f27cd'];
    const confettiCount = 150;

    for (let i = 0; i < confettiCount; i++) {
      const confetti = container.createDiv('wp-confetti');
      const color = colors[Math.floor(Math.random() * colors.length)];
      const size = Math.random() * 10 + 5;
      const left = Math.random() * 100;
      const animDuration = Math.random() * 2 + 2;
      const animDelay = Math.random() * 0.5;

      confetti.style.cssText = `
        position: fixed;
        width: ${size}px;
        height: ${size}px;
        background: ${color};
        left: ${left}vw;
        top: -20px;
        opacity: 1;
        border-radius: ${Math.random() > 0.5 ? '50%' : '2px'};
        animation: confettiFall ${animDuration}s ease-out ${animDelay}s forwards;
        transform: rotate(${Math.random() * 360}deg);
        z-index: 10000;
        pointer-events: none;
      `;
    }

    // 动画结束后移除
    setTimeout(() => {
      container.remove();
    }, 4000);
  }

  /**
   * 显示发布失败提示卡片
   */
  private showErrorCard(errorMessage: string): void {
    const overlay = document.body.createDiv('wp-publish-overlay');
    const container = overlay.createDiv('wp-error-card');

    // 错误图标
    const icon = container.createDiv('wp-error-icon');
    icon.setText('😢');

    // 错误标题
    const title = container.createDiv('wp-error-title');
    title.setText(this.t('publishModal_publishFailedTitle'));

    // 错误详情
    const detail = container.createDiv('wp-error-detail');
    detail.setText(errorMessage);

    // 按钮区域
    const buttons = container.createDiv('wp-error-buttons');

    // 重试按钮
    const retryBtn = buttons.createEl('button', { cls: 'wp-error-retry-btn' });
    retryBtn.setText(this.t('publishModal_retryButton'));
    retryBtn.onclick = () => {
      overlay.remove();
      // 恢复模态窗口显示
      this.modalEl.style.display = '';
      // 重新发布
      if (this.lastPublishParams) {
        this.doPublish(this.lastPublishParams);
      }
    };

    // 关闭按钮
    const closeBtn = buttons.createEl('button', { cls: 'wp-error-close-btn' });
    closeBtn.setText(this.t('publishModal_closeButton'));
    closeBtn.onclick = () => {
      overlay.remove();
      this.close();
    };

    // 5秒后自动关闭
    setTimeout(() => {
      if (overlay.isConnected) {
        overlay.remove();
        this.close();
      }
    }, 8000);
  }

  private generateDefaultSlug(title: string, params?: WordPressPostParams): void {
    if (!title || !this.slugInput) return;

    try {
      if (this.plugin.settings.slugGenerationMode === 'ai-translate' && this.aiService) {
        this.aiService.translateToSlug(title).then(slug => {
          if (this.slugInput) {
            this.slugInput.value = slug;
            if (params) params.slug = slug;
          }
          this.slugGenerated = true;
        }).catch(() => {
          const fallbackSlug = SlugGenerator.autoGenerateSlug(title);
          if (this.slugInput) {
            this.slugInput.value = fallbackSlug;
            if (params) params.slug = fallbackSlug;
          }
          this.slugGenerated = true;
        });
      } else {
        const slug = SlugGenerator.autoGenerateSlug(title);
        if (this.slugInput) {
          this.slugInput.value = slug;
          if (params) params.slug = slug;
        }
        this.slugGenerated = true;
      }
    } catch (error) {
      log.error('Slug generation failed:', error);
    }
  }

  /**
   * Normalize tags from frontmatter to string array
   * Handles YAML array, inline tags (#tag), and comma-separated string formats
   */
  private normalizeTags(tags: any): string[] {
    // Use TagFormatter to parse tags (supports YAML array, inline tags, and comma-separated)
    return TagFormatter.parseToArray(tags);
  }
}
