import { Setting, Notice, TFile } from 'obsidian';
import { toNumber } from 'lodash-es';
import { format, parse } from 'date-fns';
import IMask, { DynamicMaskType, InputMask } from 'imask';

import WordpressPlugin from './main';
import { WordPressPostParams } from './wp-client';
import { CommentStatus, PostStatus, PostType, PostTypeConst, Term } from './wp-api';
import { MatterData } from './types';
import { ConfirmCode, openConfirmModal } from './confirm-modal';
import { AbstractModal } from './abstract-modal';
import { SafeAny } from './utils';
import { SlugGenerator } from './slug-generator';
import { FeaturedImageResult, VaultImagePickerModal, UnsplashPickerModal, resizeFeaturedImage } from './featured-image-modal';
import { UnsplashService, UnsplashImage } from './unsplash-service';
import { AIService } from './ai-service';
import { AppState } from './app-state';
import { ImageCacheManager, CachedFeaturedImage } from './image-cache-manager';
import { createModuleLogger } from './utils/logger';

const log = createModuleLogger('WpPublishModalV2');

// Default prompt templates will be loaded from i18n

/**
 * 检测文本的主要语言
 */
function detectLanguage(text: string): 'zh' | 'en' | 'other' {
  if (!text || text.length < 10) return 'en';

  // 统计中文字符数量
  const chineseChars = text.match(/[\u4e00-\u9fa5]/g);
  const chineseCount = chineseChars ? chineseChars.length : 0;

  // 统计英文字符数量
  const englishChars = text.match(/[a-zA-Z]/g);
  const englishCount = englishChars ? englishChars.length : 0;

  // 如果中文字符占比超过30%，认为是中文
  if (chineseCount > text.length * 0.3) {
    return 'zh';
  }

  // 如果英文字符占比超过40%，认为是英文
  if (englishCount > text.length * 0.4) {
    return 'en';
  }

  // 其他情况，默认英文
  return 'other';
}

/**
 * Get localized prompt based on language
 */
function getLocalizedPrompt(plugin: WordpressPlugin, language: 'zh' | 'en' | 'other', type: 'summary' | 'tags' | 'image'): string {
  // Use English prompts for English or other languages
  if (language === 'en' || language === 'other') {
    if (type === 'summary') {
      return plugin.t('defaultPrompt_summaryEn');
    } else if (type === 'tags') {
      return plugin.t('defaultPrompt_tagsEn');
    } else {
      return plugin.t('defaultPrompt_imageEn');
    }
  }

  // Use Chinese prompts for Chinese
  if (type === 'summary') {
    return plugin.t('defaultPrompt_summary');
  } else if (type === 'tags') {
    return plugin.t('defaultPrompt_tags');
  } else {
    return plugin.t('defaultPrompt_image');
  }
}

/**
 * WordPress publish modal V2 - New version with improved UI
 * Tabs: settings/preview/advanced
 */
export class WpPublishModalV2 extends AbstractModal {

  private dateInputMask: InputMask<DynamicMaskType> | null = null;
  private featuredImage: FeaturedImageResult | null = null;
  private aiService: AIService | null = null;
  private unsplashService: UnsplashService | null = null;
  private slugInput: HTMLInputElement | null = null;
  private titleInput: HTMLInputElement | null = null;
  private currentTab: 'settings' | 'preview' | 'advanced' = 'settings';
  private editableContent: string = '';
  private isEditingPreview: boolean = false;
  private autoFeaturedImage: FeaturedImageResult | null = null;
  private slugGenerated: boolean = false;
  private lastAutoGeneratedSlug: string = '';
  private isPublishing: boolean = false;
  private lastPublishParams: WordPressPostParams | null = null;
  private publishBtn: HTMLButtonElement | null = null;
  private featurePictureUrl: string | null = null; // 已上传到 WordPress 的特色图片 URL
  private imageCacheManager: ImageCacheManager; // 图片缓存管理器
  private notePath: string; // 当前笔记路径，用于缓存关联
  private imageSource: 'local' | 'unsplash' | 'ai' | 'vault' | 'cached' | 'auto' = 'auto'; // 图片来源类型
  private currentParams: WordPressPostParams | null = null; // 当前的发布参数，用于在关闭时保存生成的内容

  // Prompt templates from settings, with proper defaults
  private get imageGenerationPrompt(): string {
    return this.plugin.settings.imageGenerationPrompt || this.plugin.t('defaultPrompt_image');
  }

  private get summaryPrompt(): string {
    return this.plugin.settings.summaryPrompt || this.plugin.t('defaultPrompt_summary');
  }

  private get tagsPrompt(): string {
    return this.plugin.settings.tagsPrompt || this.plugin.t('defaultPrompt_tags');
  }

  constructor(
    readonly plugin: WordpressPlugin,
    private readonly categories: {
      items: Term[],
      selected: number[]
    },
    private readonly postTypes: {
      items: PostType[],
      selected: PostType
    },
    private readonly onSubmit: (
      params: WordPressPostParams,
      updateMatterData: (matter: MatterData) => void,
      featuredImage?: FeaturedImageResult
    ) => void,
    private readonly matterData: MatterData,
    private readonly articleContent: string = '',
    private readonly noteTitle: string = '',
    notePath: string = ''
  ) {
    super(plugin);
    log.info('Constructor called');

    // 初始化图片缓存管理器
    this.imageCacheManager = new ImageCacheManager(plugin.app);
    this.notePath = notePath;

    if (plugin.settings.aiConfig) {
      this.aiService = new AIService(plugin.settings.aiConfig);
    }

    if (plugin.settings.unsplashAccessKey) {
      this.unsplashService = new UnsplashService(plugin.settings.unsplashAccessKey);
    }

    // 检查 frontmatter 中是否已有特色图片链接
    if (matterData.featurePicture) {
      log.info('Found featured image in frontmatter:', matterData.featurePicture);
      this.featurePictureUrl = matterData.featurePicture as string;
      // 加载已有的特色图片
      this.loadFeaturePictureFromUrl(matterData.featurePicture as string);
    } else {
      // 尝试从缓存恢复图片
      this.loadCachedImage();
    }
  }

  // 从 URL 加载已有的特色图片
  private async loadFeaturePictureFromUrl(url: string): Promise<void> {
    try {
      log.info('Loading featured image from URL:', url);
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }
      const arrayBuffer = await response.arrayBuffer();

      // 从 URL 或 Content-Type 获取 MIME 类型
      const contentType = response.headers.get('content-type');
      const mimeType = this.getMimeTypeFromResponse(contentType, url);

      // 从 URL 提取文件名
      const fileName = this.extractFileName(url);

      this.autoFeaturedImage = {
        fileName,
        mimeType,
        content: arrayBuffer,
        width: 1200
      };
      log.info('Successfully loaded featured image:', fileName);
    } catch (e) {
      log.info('Failed to load featured image from URL:', e);
      // 加载失败，尝试从缓存恢复
      await this.loadCachedImage();
    }
  }

  /**
   * 从缓存加载图片，如果没有缓存则检测文章第一张图片
   */
  private async loadCachedImage(): Promise<void> {
    if (!this.notePath) {
      // 没有笔记路径，直接检测第一张图片
      await this.detectFirstImage();
      return;
    }

    try {
      const cachedImage = await this.imageCacheManager.loadImage(this.notePath);
      if (cachedImage) {
        log.info('Restored featured image from cache:', cachedImage.fileName);
        this.featuredImage = {
          fileName: cachedImage.fileName,
          mimeType: cachedImage.mimeType,
          content: cachedImage.content,
          width: cachedImage.width
        };
        this.imageSource = 'cached';
      } else {
        // 没有缓存，自动检测文章第一张图片
        await this.detectFirstImage();
      }
    } catch (e) {
      log.info('Failed to load cached image:', e);
      await this.detectFirstImage();
    }
  }

  /**
   * 保存图片到缓存
   */
  private async saveImageToCache(
    imageData: ArrayBuffer,
    fileName: string,
    mimeType: string,
    sourceType: 'local' | 'unsplash' | 'ai' | 'vault'
  ): Promise<void> {
    if (!this.notePath) {
      log.info('No note path, skipping cache save');
      return;
    }

    try {
      await this.imageCacheManager.saveImage(
        this.notePath,
        imageData,
        fileName,
        mimeType,
        sourceType
      );
      log.info('Image saved to cache:', fileName);
    } catch (e) {
      log.error('Failed to save image to cache:', e);
    }
  }

  /**
   * 清除当前笔记的图片缓存
   */
  async clearImageCache(): Promise<void> {
    if (!this.notePath) return;
    
    try {
      await this.imageCacheManager.clearCache(this.notePath);
      log.info('Image cache cleared for:', this.notePath);
    } catch (e) {
      log.error('Failed to clear image cache:', e);
    }
  }

  private getMimeTypeFromResponse(contentType: string | null, url: string): string {
    if (contentType?.startsWith('image/')) {
      return contentType.split(';')[0];
    }

    // 从 URL 扩展名推断
    const ext = url.split('.').pop()?.toLowerCase()?.split('?')[0];
    return this.getMimeType(ext || 'jpg');
  }

  private extractFileName(url: string): string {
    const urlParts = url.split('/');
    const lastPart = urlParts[urlParts.length - 1]?.split('?')[0];
    return (lastPart && lastPart.includes('.')) ? lastPart : 'featured-image.jpg';
  }

  // 检测文章第一张图片
  private async detectFirstImage(): Promise<void> {
    try {
      const imagePath = this.extractFirstImagePath();
      if (!imagePath) {
        await this.loadEmptyImage();
        return;
      }

      if (imagePath.startsWith('http')) {
        await this.loadOnlineImage(imagePath);
      } else {
        await this.loadLocalImage(imagePath);
      }
    } catch (e) {
      log.info('Error detecting first image:', e);
      await this.loadEmptyImage();
    }
  }

  private extractFirstImagePath(): string | null {
    const content = this.articleContent || '';
    const imageRegex = /!\[.*?\]\((.*?)\)|!\[\[(.*?)(?:\|.*?)?\]\]/g;
    const match = imageRegex.exec(content);
    return match ? (match[1] || match[2]) : null;
  }

  private async loadLocalImage(imagePath: string): Promise<void> {
    const file = this.app.metadataCache.getFirstLinkpathDest(imagePath, this.noteTitle);
    if (file instanceof TFile) {
      const binaryContent = await this.app.vault.readBinary(file);
      this.autoFeaturedImage = {
        fileName: file.name,
        mimeType: this.getMimeType(file.extension.toLowerCase()),
        content: binaryContent,
        width: 1200
      };
      log.info('Auto-detected first image:', file.name);
    }
  }

  private async loadOnlineImage(imagePath: string): Promise<void> {
    try {
      const response = await fetch(imagePath);
      const arrayBuffer = await response.arrayBuffer();
      this.autoFeaturedImage = {
        fileName: `featured-${Date.now()}.jpg`,
        mimeType: 'image/jpeg',
        content: arrayBuffer,
        width: 1200
      };
    } catch (e) {
      log.info('Failed to download online image:', e);
    }
  }

  private async loadEmptyImage(): Promise<void> {
    try {
      const emptyFile = this.app.vault.getAbstractFileByPath('empty.png');
      if (emptyFile instanceof TFile) {
        const content = await this.app.vault.readBinary(emptyFile);
        this.autoFeaturedImage = {
          fileName: 'empty.png',
          mimeType: 'image/png',
          content: content,
          width: 1200
        };
      }
    } catch (e) {
      log.info('Could not load empty.png:', e);
    }
  }

  private getMimeType(extension: string): string {
    const mimeTypes: Record<string, string> = {
      'jpg': 'image/jpeg',
      'jpeg': 'image/jpeg',
      'png': 'image/png',
      'gif': 'image/gif',
      'webp': 'image/webp'
    };
    return mimeTypes[extension.toLowerCase()] || 'image/jpeg';
  }

  onOpen() {
    log.info('onOpen called');
    const params: WordPressPostParams = {
      status: this.plugin.settings.defaultPostStatus,
      commentStatus: this.plugin.settings.defaultCommentStatus,
      postType: this.postTypes.selected,
      categories: this.categories.selected,
      tags: this.normalizeTags(this.matterData.tags),
      title: this.noteTitle || '',
      content: '',
      slug: this.matterData.slug || '',
      excerpt: this.matterData.excerpt || ''
    };

    this.editableContent = this.articleContent;
    this.currentTab = 'settings';

    // 设置默认特色图片为自动检测的图片
    if (!this.featuredImage && this.autoFeaturedImage) {
      this.featuredImage = this.autoFeaturedImage;
    }

    // Slug generation: only auto-generate if no existing slug in frontmatter
    // Delay slug generation until title is confirmed available
    if (this.plugin.settings.autoGenerateSlug && params.title && !params.slug) {
      // Use setTimeout to ensure slugInput is created first
      setTimeout(() => {
        if (!this.slugGenerated && !params.slug) {
          this.generateDefaultSlug(params.title, params);
          this.slugGenerated = true;
          this.lastAutoGeneratedSlug = params.slug || '';
        }
      }, 100);
    }

    this.display(params);
  }

  async onClose() {
    const { contentEl } = this;

    // 在关闭前保存生成的内容到 frontmatter
    await this.saveGeneratedContentToFrontmatter();

    contentEl.empty();
    if (this.dateInputMask) {
      this.dateInputMask.destroy();
    }
  }

  /**
   * 保存生成的内容（标签、摘要等）到 frontmatter
   * 当用户生成内容后关闭窗口时，确保内容不会丢失
   */
  private async saveGeneratedContentToFrontmatter(): Promise<void> {
    if (!this.currentParams || !this.notePath) {
      return;
    }

    const file = this.plugin.app.vault.getAbstractFileByPath(this.notePath);
    if (!file || !(file instanceof TFile)) {
      return;
    }

    try {
      // 检查是否有需要保存的生成内容
      const hasGeneratedTags = this.currentParams.tags &&
                               this.currentParams.tags.length > 0 &&
                               JSON.stringify(this.currentParams.tags) !== JSON.stringify(this.matterData.tags);

      const hasGeneratedExcerpt = this.currentParams.excerpt &&
                                  this.currentParams.excerpt !== this.matterData.excerpt;

      if (!hasGeneratedTags && !hasGeneratedExcerpt) {
        return; // 没有需要保存的内容
      }

      // 使用 processFrontMatter 更新 frontmatter
      await this.plugin.app.fileManager.processFrontMatter(file, (fm) => {
        if (hasGeneratedTags) {
          // 保存为数组格式，统一 frontmatter 标签格式
          fm.tags = this.currentParams!.tags;
          log.info('Saved generated tags to frontmatter:', this.currentParams!.tags);
        }
        if (hasGeneratedExcerpt) {
          fm.excerpt = this.currentParams!.excerpt;
          log.info('Saved generated excerpt to frontmatter');
        }
      });
    } catch (error) {
      log.error('Failed to save generated content to frontmatter:', error);
    }
  }

  private display(params: WordPressPostParams): void {
    const { contentEl } = this;

    // 保存当前参数，用于在关闭时保存生成的内容
    this.currentParams = params;

    contentEl.empty();
    contentEl.addClass('wp-publish-modal-v2');

    this.createHeader(this.t('publishModal_title'));

    // 自适应窗口宽度
    this.updateModalWidth();

    // 创建标签切换
    this.renderTabBar(contentEl, params);

    const mainContainer = contentEl.createDiv('wp-publish-container');

    if (this.currentTab === 'settings') {
      this.renderSettingsTab(mainContainer, params);
    } else if (this.currentTab === 'preview') {
      this.renderPreviewTab(mainContainer, params);
    } else if (this.currentTab === 'advanced') {
      this.renderAdvancedTab(mainContainer, params);
    }

    // 底部操作栏（仅在设置和预览标签显示）
    if (this.currentTab !== 'advanced') {
      this.renderBottomBar(contentEl, params);
    }
  }

  private updateModalWidth(): void {
    const modalEl = this.modalEl;
    if (modalEl) {
      modalEl.style.width = '90vw';
      modalEl.style.maxWidth = '800px';
      modalEl.style.minWidth = '400px';
      modalEl.style.boxSizing = 'border-box';
    }
  }

  private renderTabBar(container: HTMLElement, params: WordPressPostParams): void {
    const tabContainer = container.createDiv('wp-publish-tabs');

    const tabs = [
      { id: 'settings', label: this.plugin.t('publishModal_settingsTab') },
      { id: 'preview', label: this.plugin.t('publishModal_previewTab') },
      { id: 'advanced', label: this.plugin.t('publishModal_advancedTab') }
    ];

    tabs.forEach(tab => {
      const tabEl = tabContainer.createDiv({
        cls: `wp-publish-tab-item ${this.currentTab === tab.id ? 'active' : ''}`
      });
      tabEl.createSpan({ text: tab.label });
      tabEl.onclick = () => {
        this.currentTab = tab.id as 'settings' | 'preview' | 'advanced';
        this.display(params);
      };
    });
  }

  // ==================== 设置标签 ====================
  private renderSettingsTab(container: HTMLElement, params: WordPressPostParams): void {
    const topSection = container.createDiv('wp-settings-top');
    this.renderFeaturedImageSettings(topSection, params);

    const bottomSection = container.createDiv('wp-settings-bottom');
    this.renderBasicSettings(bottomSection, params);
  }

  private renderFeaturedImageSettings(container: HTMLElement, params: WordPressPostParams): void {
    const card = container.createDiv('wp-settings-card');
    card.createEl('h3', { text: this.t('publishModal_featuredImage'), cls: 'wp-settings-section-title' });

    const previewContainer = card.createDiv('featured-image-preview-large');

    if (this.featuredImage) {
      const blob = new Blob([this.featuredImage.content], { type: this.featuredImage.mimeType });
      const url = URL.createObjectURL(blob);

      const img = previewContainer.createEl('img', {
        attr: { src: url },
        cls: 'featured-image-full'
      });
      // Constrain image height for better text readability
      img.style.maxWidth = '100%';
      img.style.maxHeight = '160px';
      img.style.objectFit = 'cover';
      img.style.borderRadius = '6px';

      const info = previewContainer.createDiv('featured-image-info');
      info.createSpan({ text: this.featuredImage.fileName });

      const removeBtn = previewContainer.createEl('button', {
        text: this.t('confirmModal_cancel'),
        cls: 'featured-image-remove-btn'
      });
      removeBtn.onclick = () => {
        this.featuredImage = this.autoFeaturedImage;
        this.display(params);
      };
    } else if (this.featurePictureUrl) {
      // 显示已上传到 WordPress 的特色图片
      const img = previewContainer.createEl('img', {
        attr: { src: this.featurePictureUrl },
        cls: 'featured-image-full'
      });
      img.style.maxWidth = '100%';
      img.style.maxHeight = '160px';
      img.style.objectFit = 'cover';
      img.style.borderRadius = '6px';

      const info = previewContainer.createDiv('featured-image-info');
      info.createSpan({ text: this.t('publishModal_uploadedToWordPress') });
      info.style.color = 'var(--text-success)';
      info.style.display = 'flex';
      info.style.alignItems = 'center';
      info.style.justifyContent = 'center';
      info.style.gap = '4px';
    } else {
      previewContainer.createEl('p', {
        text: this.t('publishModal_noFeaturedImage'),
        cls: 'featured-image-placeholder-text'
      });
    }

    // 四个按钮
    const btnRow = card.createDiv('featured-image-btn-row');

    const localBtn = btnRow.createEl('button', { text: this.t('publishModal_localImage'), cls: 'feature-btn' });
    localBtn.onclick = () => this.selectLocalImage(params);

    // 在线按钮 (Unsplash) - use tags as search query
    const onlineBtn = btnRow.createEl('button', { text: this.t('publishModal_onlineImage'), cls: 'feature-btn' });
    onlineBtn.onclick = () => {
      if (!this.plugin.settings.unsplashAccessKey) {
        new Notice(this.t('publishModal_unsplashKeyRequired'));
      } else {
        this.selectUnsplashImage(params);
      }
    };

    const aiBtn = btnRow.createEl('button', { text: this.t('publishModal_aiGenerateBtn'), cls: 'feature-btn' });
    if (!this.plugin.settings.aiConfig) {
      aiBtn.onclick = () => {
        new Notice(this.t('publishModal_imageAIRequired'));
      };
    } else {
      aiBtn.onclick = () => this.generateAImage(params);
    }

    const galleryBtn = btnRow.createEl('button', { text: this.t('publishModal_galleryImage'), cls: 'feature-btn' });
    galleryBtn.onclick = () => this.selectVaultImage(params);
  }

  private selectLocalImage(params: WordPressPostParams): void {
    const fileInput = document.createElement('input');
    fileInput.type = 'file';
    fileInput.accept = 'image/*';
    fileInput.onchange = async (e) => {
      const file = (e.target as HTMLInputElement).files?.[0];
      if (file) {
        try {
          let arrayBuffer = await file.arrayBuffer();
          this.featuredImage = {
            fileName: file.name,
            mimeType: file.type,
            content: arrayBuffer,
            width: 1200
          };
          this.imageSource = 'local';
          // 保存到缓存
          await this.saveImageToCache(arrayBuffer, file.name, file.type, 'local');
          this.display(params);
          new Notice(this.t('publishModal_imageSelected_simple'));
        } catch (error) {
          new Notice(this.t('publishModal_imageSelectFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
        }
      }
    };
    fileInput.click();
  }

  private selectUnsplashImage(params: WordPressPostParams): void {
    if (!this.unsplashService) {
      new Notice(this.t('publishModal_unsplashKeyRequiredSimple'));
      return;
    }

    const tagsQuery = this.getSearchQuery(params);
    const targetWidth = this.plugin.settings.imageCropWidth || 1200;
    const ratio = this.plugin.settings.imageCropRatio || '16:9';

    const modal = new UnsplashPickerModal(
      this.app,
      this.plugin,
      this.unsplashService,
      async (image: UnsplashImage, arrayBuffer: ArrayBuffer) => {
        const processed = await resizeFeaturedImage(arrayBuffer, 'image/jpeg', targetWidth, ratio);
        const finalBuffer = processed || arrayBuffer;
        const fileName = `unsplash-${image.id}.jpg`;
        this.featuredImage = {
          fileName,
          mimeType: 'image/jpeg',
          content: finalBuffer,
          width: targetWidth
        };
        this.imageSource = 'unsplash';
        // 保存到缓存
        await this.saveImageToCache(finalBuffer, fileName, 'image/jpeg', 'unsplash');
        this.display(params);
        new Notice(this.t('publishModal_imageSelected_simple'));
      },
      tagsQuery
    );
    modal.open();
  }

  private getSearchQuery(params: WordPressPostParams): string {
    const frontmatterTag = this.matterData.tag;

    if (Array.isArray(frontmatterTag) && frontmatterTag.length > 0) {
      return String(frontmatterTag[0]);
    }

    if (typeof frontmatterTag === 'string' && frontmatterTag) {
      return frontmatterTag;
    }

    return params.tags?.[0] ? String(params.tags[0]) : '';
  }

  private async generateAImage(params: WordPressPostParams): Promise<void> {
    if (!this.plugin.settings.aiConfig || !this.aiService) {
      new Notice(this.t('publishModal_aiServiceRequired'));
      return;
    }

    try {
      const imagePromptContent = await this.getImagePromptContent(params);
      if (!imagePromptContent) return;

      // 检测文章语言并生成图片描述提示词
      const contentToDetect = this.editableContent || this.articleContent;
      const language = detectLanguage(contentToDetect);
      log.info('Detected language for image generation:', language);

      const basePrompt = this.imageGenerationPrompt || this.plugin.t('defaultPrompt_image');
      const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'image');
      const imageDescriptionPrompt = localizedPrompt
        .replace('{title}', params.title || '')
        .replace('{content}', imagePromptContent);

      new Notice(this.t('publishModal_aiGeneratingImage'));
      const imageUrl = await this.aiService.generateImage(imageDescriptionPrompt);
      const response = await fetch(imageUrl);
      const arrayBuffer = await response.arrayBuffer();

      const fileName = `ai-generated-${Date.now()}.png`;
      this.featuredImage = {
        fileName,
        mimeType: 'image/png',
        content: arrayBuffer,
        width: 1200
      };
      this.imageSource = 'ai';
      // 保存到缓存
      await this.saveImageToCache(arrayBuffer, fileName, 'image/png', 'ai');

      this.display(params);
      new Notice(this.t('publishModal_aiImageGenerated'));
    } catch (error) {
      log.error('AI image generation error:', error);
      new Notice(this.t('publishModal_aiImageGenerateFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
    }
  }

  private async getImagePromptContent(params: WordPressPostParams): Promise<string | null> {
    // Priority: excerpt > tags > generate summary
    if (params.excerpt) {
      return params.excerpt;
    }

    if (params.tags?.length) {
      return params.tags.join(', ');
    }

    // Generate summary first
    if (!this.aiService) {
      new Notice(this.t('notice_aiConfigRequired'));
      return null;
    }

    const contentToUse = this.editableContent || this.articleContent;
    if (!contentToUse) {
      new Notice(this.t('publishModal_emptyContent'));
      return null;
    }

    try {
      new Notice(this.t('publishModal_generatingSummary'));
      const cleanContent = this.sanitizeContentForAI(contentToUse, 2000);

      // 检测文章语言并适配提示词
      const language = detectLanguage(cleanContent);
      log.info('Detected language for image summary:', language);
      const basePrompt = this.summaryPrompt || this.plugin.t('defaultPrompt_summary');
      const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'summary');
      const prompt = localizedPrompt.replace('{content}', cleanContent);

      const summary = await this.aiService.generateText(prompt);
      params.excerpt = summary.trim();
      new Notice(this.t('publishModal_generatingSummary'));
      this.display(params);
      return params.excerpt;
    } catch (error) {
      log.error('Generate summary for image error:', error);
      new Notice(this.t('publishModal_summaryGenerateFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
      return null;
    }
  }

  private selectVaultImage(params: WordPressPostParams): void {
    const modal = new VaultImagePickerModal(
      this.app,
      this.plugin,
      async (file: TFile, arrayBuffer: ArrayBuffer, mimeType: string) => {
        this.featuredImage = {
          fileName: file.name,
          mimeType: mimeType,
          content: arrayBuffer,
          width: 1200
        };
        this.imageSource = 'vault';
        // 保存到缓存
        await this.saveImageToCache(arrayBuffer, file.name, mimeType, 'vault');
        this.display(params);
        new Notice(this.t('publishModal_imageFromGallery', { fileName: file.name }));
      }
    );
    modal.open();
  }

  private renderBasicSettings(container: HTMLElement, params: WordPressPostParams): void {
    const card = container.createDiv('wp-settings-card');
    card.createEl('h3', { text: this.plugin.t('publishModal_basicSettings'), cls: 'wp-settings-section-title' });

    // 标题
    new Setting(card)
      .setName(this.t('publishModal_titleName'))
      .setDesc(this.t('publishModal_titleDesc'))
      .addText(text => {
        this.titleInput = text.inputEl;
        text.setPlaceholder(this.t('publishModal_titlePlaceholder'))
          .setValue(params.title || '')
          .onChange(value => {
            params.title = value;
          });
        text.inputEl.style.width = '100%';

        // 自动更新 slug 的通用逻辑
        const autoUpdateSlug = () => {
          if (this.plugin.settings.autoGenerateSlug && this.slugInput) {
            // Only regenerate if current slug matches the last auto-generated one (not manually modified)
            if (!this.lastAutoGeneratedSlug || params.slug === this.lastAutoGeneratedSlug) {
              this.generateDefaultSlug(params.title, params);
              this.lastAutoGeneratedSlug = params.slug || '';
              new Notice(this.t('publishModal_slugAutoUpdated'));
            }
          }
        };

        // 按下回车时触发 slug 自动更新
        text.inputEl.addEventListener('keydown', (e) => {
          if (e.key === 'Enter') {
            e.preventDefault();
            autoUpdateSlug();
          }
        });

        // 失去焦点时触发 slug 自动更新
        text.inputEl.addEventListener('blur', () => {
          autoUpdateSlug();
        });
      });

    // Slug
    const slugSetting = new Setting(card)
      .setName(this.t('publishModal_slugName'))
      .setDesc(this.t('publishModal_slugDesc'));

    // Track the initial slug value to detect manual edits
    const initialSlugValue = params.slug;

    slugSetting.addText(text => {
      this.slugInput = text.inputEl;
      text.setPlaceholder(this.t('publishModal_slugPlaceholder'))
        .setValue(params.slug || '')
        .onChange(value => {
          const sanitized = SlugGenerator.sanitizeSlug(value);
          params.slug = sanitized;
          // Clear the auto-generated slug reference if user manually edits
          // This prevents further auto-updates on title change
          if (sanitized && initialSlugValue && sanitized !== initialSlugValue) {
            this.lastAutoGeneratedSlug = '';
          }
        });
      text.inputEl.style.width = '100%';
    });

    // AI翻译按钮
    if (this.plugin.settings.slugGenerationMode === 'ai-translate') {
      if (!this.plugin.settings.aiConfig) {
        slugSetting.addButton(btn => {
          btn.setButtonText(this.t('publishModal_slugAIButtonNeedConfig'))
            .setTooltip(this.t('publishModal_aiServiceRequired'))
            .setDisabled(true);
        });
      } else {
        slugSetting.addButton(btn => {
          btn.setButtonText(this.t('publishModal_slugAIButton'))
            .setTooltip(this.t('publishModal_slugAIButton'))
            .onClick(async () => {
              if (!params.title) {
                new Notice(this.t('publishModal_slugNeedTitle'));
                return;
              }

              btn.setDisabled(true);
              btn.setButtonText(this.t('publishModal_slugAIButtonTranslating'));

              try {
                const slug = await this.aiService!.translateToSlug(params.title);
                if (this.slugInput) {
                  this.slugInput.value = slug;
                  params.slug = slug;
                }
                new Notice(this.t('publishModal_slugGenerated'));
              } catch (error) {
                new Notice(this.t('publishModal_slugTranslateFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
              } finally {
                btn.setDisabled(false);
                btn.setButtonText(this.t('publishModal_slugAIButton'));
              }
            });
        });
      }
    }

    // 分类（仅Post类型）
    // 先过滤掉空值的分类项
    const validCategories = this.categories.items.filter(it => it.name && it.name.trim());

    if (params.postType === PostTypeConst.Post && validCategories.length > 0) {
      new Setting(card)
        .setName(this.t('publishModal_categoryName'))
        .setDesc(this.t('publishModal_categoryDesc'))
        .addDropdown((dropdown) => {

          // Find "Uncategorized" category
          const uncategorized = validCategories.find(it =>
            it.name === this.plugin.t('publishModal_uncategorized') ||
            it.name === 'Uncategorized' ||
            it.name === '未分类'
          );

          validCategories.forEach(it => {
            dropdown.addOption(String(it.id), it.name);
          });

          // If no category selected, default to "Uncategorized"
          const selectedCategory = params.categories[0]
            ? String(params.categories[0])
            : (uncategorized ? String(uncategorized.id) : String(validCategories[0]?.id || ''));

          dropdown
            .setValue(selectedCategory)
            .onChange((value) => {
              params.categories = [toNumber(value)];
            });

          // 更新 params.categories 为默认值
          if (!params.categories[0] && uncategorized) {
            params.categories = [toNumber(uncategorized.id)];
          }
        });
    }

    // 发布状态 - preserve slug on state change
    new Setting(card)
      .setName(this.t('publishModal_statusName'))
      .setDesc(this.t('publishModal_statusDesc'))
      .addDropdown((dropdown) => {
        dropdown
          .addOption(PostStatus.Draft, this.plugin.t('publishModal_statusDraft'))
          .addOption(PostStatus.Publish, this.plugin.t('publishModal_statusPublish'))
          .addOption(PostStatus.Private, this.plugin.t('publishModal_statusPrivate'))
          .addOption(PostStatus.Future, this.plugin.t('publishModal_statusFuture'))
          .setValue(params.status)
          .onChange((value) => {
            params.status = value as PostStatus;
            // Do NOT clear slug or other fields when changing status
            this.display(params);
          });
      });

    // 定时发布日期
    if (params.status === PostStatus.Future) {
      new Setting(card)
        .setName(this.t('publishModal_postDateTimeName'))
        .setDesc(this.t('publishModal_postDateTimeDescFormat'))
        .addText(text => {
          text.setValue(format(new Date(), 'yyyy-MM-dd HH:mm:ss'));
          this.setupDateMask(text.inputEl, params);
        });
    } else {
      delete params.datetime;
    }

    // 评论状态
    new Setting(card)
      .setName(this.t('publishModal_commentName'))
      .setDesc(this.t('publishModal_commentDesc'))
      .addDropdown((dropdown) => {
        dropdown
          .addOption(CommentStatus.Open, this.plugin.t('publishModal_commentOpen'))
          .addOption(CommentStatus.Closed, this.plugin.t('publishModal_commentClosed'))
          .setValue(params.commentStatus)
          .onChange((value) => {
            params.commentStatus = value as CommentStatus;
          });
      });

    // 发布为Markdown选项
    new Setting(card)
      .setName(this.t('publishModal_postTypeName'))
      .setDesc(this.t('publishModal_postTypeDesc'))
      .addDropdown((dropdown) => {
        dropdown
          .addOption('html', this.plugin.t('publishModal_formatHTML'))
          .addOption('markdown', this.plugin.t('publishModal_formatMarkdown'))
          .setValue('html')
          .onChange((value) => {
            (params as SafeAny).contentFormat = value;
          });
      });
  }

  private setupDateMask(inputEl: HTMLInputElement, params: WordPressPostParams): void {
    const dateTimeFormat = 'yyyy-MM-dd HH:mm:ss';
    const dateBlocks = {
      yyyy: { mask: IMask.MaskedRange, from: 1970, to: 9999 },
      MM: { mask: IMask.MaskedRange, from: 1, to: 12 },
      dd: { mask: IMask.MaskedRange, from: 1, to: 31 },
    };

    if (this.dateInputMask) {
      this.dateInputMask.destroy();
    }

    this.dateInputMask = IMask(inputEl, [
      {
        mask: Date,
        lazy: false,
        overwrite: true,
        pattern: dateTimeFormat,
        blocks: {
          ...dateBlocks,
          HH: { mask: IMask.MaskedRange, from: 0, to: 23 },
          mm: { mask: IMask.MaskedRange, from: 0, to: 59 },
          ss: { mask: IMask.MaskedRange, from: 0, to: 59 },
        },
        format: (date: SafeAny) => format(date, dateTimeFormat),
        parse: (str: string) => parse(str, dateTimeFormat, new Date())
      }
    ]);

    this.dateInputMask.on('accept', () => {
      if (this.dateInputMask && this.dateInputMask.masked.isComplete) {
        params.datetime = this.dateInputMask.typedValue;
      }
    });
  }

  // ==================== Preview Tab ====================
  private renderPreviewTab(container: HTMLElement, params: WordPressPostParams): void {
    const card = container.createDiv('wp-preview-card');
    card.createEl('h3', { text: this.plugin.t('publishModal_previewTitle'), cls: 'wp-preview-card-title' });

    if (this.isEditingPreview) {
      this.renderPreviewEditor(card);
    } else {
      this.renderPreviewContent(card, params);
    }
  }

  private renderPreviewEditor(card: HTMLElement): void {
    const editorArea = card.createDiv('wp-preview-editor-area');
    const textarea = editorArea.createEl('textarea', {
      cls: 'wp-preview-textarea',
      attr: { placeholder: this.plugin.t('publishModal_previewEditPlaceholder') }
    });
    textarea.value = this.editableContent;
    textarea.style.width = '100%';
    textarea.style.minHeight = '300px';
    textarea.style.fontFamily = 'var(--font-mono)';
    textarea.oninput = () => {
      this.editableContent = textarea.value;
    };
  }

  private renderPreviewContent(card: HTMLElement, params: WordPressPostParams): void {
    // 特色图片
    if (this.featuredImage) {
      this.renderFeaturedImagePreview(card, this.featuredImage);
    } else if (this.matterData.featurePicture) {
      this.renderUploadedImagePreview(card, this.matterData.featurePicture as string);
    }

    // 摘要
    if (params.excerpt) {
      this.renderExcerptPreview(card, params.excerpt);
    }

    // 标签
    if (params.tags?.length) {
      this.renderTagsPreview(card, params.tags);
    }

    // 文章内容
    this.renderArticlePreview(card);
  }

  private renderFeaturedImagePreview(card: HTMLElement, image: FeaturedImageResult): void {
    const section = this.createImageSection(card, this.plugin.t('publishModal_previewFeaturedImage'));
    const blob = new Blob([image.content], { type: image.mimeType });
    const url = URL.createObjectURL(blob);
    this.createPreviewImage(section, url);
  }

  private renderUploadedImagePreview(card: HTMLElement, imageUrl: string): void {
    const section = this.createImageSection(card, this.plugin.t('publishModal_previewFeaturedImageUploaded'));
    this.createPreviewImage(section, imageUrl);
  }

  private createImageSection(card: HTMLElement, labelText: string): HTMLElement {
    const section = card.createDiv('wp-preview-featured-image');
    section.style.marginBottom = '16px';
    section.style.textAlign = 'center';

    const label = section.createEl('div', { text: labelText });
    label.style.fontSize = '12px';
    label.style.color = 'var(--text-muted)';
    label.style.marginBottom = '8px';

    return section;
  }

  private createPreviewImage(section: HTMLElement, src: string): void {
    const imgContainer = section.createDiv();
    Object.assign(imgContainer.style, {
      maxWidth: '100%',
      borderRadius: '8px',
      overflow: 'hidden',
      border: '1px solid var(--background-modifier-border)'
    });

    const img = imgContainer.createEl('img', { attr: { src } });
    Object.assign(img.style, {
      maxWidth: '100%',
      maxHeight: '180px',
      objectFit: 'cover',
      display: 'block',
      width: '100%'
    });
  }

  private renderExcerptPreview(card: HTMLElement, excerpt: string): void {
    const section = card.createDiv('wp-preview-excerpt');
    Object.assign(section.style, {
      padding: '10px 14px',
      backgroundColor: 'var(--background-secondary)',
      borderRadius: '6px',
      marginBottom: '16px',
      fontSize: '13px',
      color: 'var(--text-muted)',
      borderLeft: '3px solid var(--interactive-accent)'
    });
    section.createEl('strong', { text: this.plugin.t('publishModal_previewSummary') });
    section.createSpan({ text: excerpt });
  }

  private renderTagsPreview(card: HTMLElement, tags: string[]): void {
    const section = card.createDiv('wp-preview-tags');
    Object.assign(section.style, {
      marginBottom: '16px',
      display: 'flex',
      flexWrap: 'wrap',
      gap: '6px',
      alignItems: 'center'
    });

    const label = section.createEl('span', { text: this.plugin.t('publishModal_previewTags') });
    label.style.fontSize = '12px';
    label.style.color = 'var(--text-muted)';

    tags.forEach(tag => {
      const tagEl = section.createEl('span', { text: tag });
      Object.assign(tagEl.style, {
        padding: '2px 8px',
        backgroundColor: 'var(--interactive-accent)',
        color: 'var(--text-on-accent)',
        borderRadius: '10px',
        fontSize: '11px'
      });
    });
  }

  private renderArticlePreview(card: HTMLElement): void {
    const previewContent = card.createDiv('wp-preview-rendered');
    const html = AppState.markdownParser.render(this.editableContent);
    previewContent.innerHTML = html;

    const style = document.createElement('style');
    style.textContent = `
      .wp-preview-rendered h1, .wp-preview-rendered h2, .wp-preview-rendered h3 {
        margin-top: 1em; margin-bottom: 0.5em; font-weight: 600;
      }
      .wp-preview-rendered p { margin-bottom: 1em; line-height: 1.6; }
      .wp-preview-rendered img { max-width: 100%; max-height: 300px; object-fit: contain; height: auto; }
      .wp-preview-rendered code {
        background: var(--background-secondary); padding: 2px 4px; border-radius: 3px;
      }
      .wp-preview-rendered pre {
        background: var(--background-secondary); padding: 12px; border-radius: 5px; overflow-x: auto;
      }
      .wp-preview-rendered blockquote {
        border-left: 3px solid var(--text-accent); padding-left: 12px; color: var(--text-muted);
      }
    `;
    previewContent.appendChild(style);
  }

  // ==================== Advanced Settings Tab ====================
  private renderAdvancedTab(container: HTMLElement, params: WordPressPostParams): void {
    const card = container.createDiv('wp-advanced-card');

    const header = card.createDiv('wp-advanced-header');
    header.createEl('h3', { text: this.plugin.t('publishModal_advancedTitle'), cls: 'wp-advanced-card-title' });

    const notice = header.createDiv('wp-advanced-notice');
    notice.style.padding = '12px';
    notice.style.backgroundColor = 'var(--background-secondary)';
    notice.style.borderRadius = '6px';
    notice.style.marginBottom = '20px';
    notice.createEl('p', { text: this.plugin.t('publishModal_advancedNotice') });

    // Summary prompt
    const summarySection = card.createDiv('wp-advanced-section');
    summarySection.createEl('h4', { text: this.plugin.t('publishModal_summaryPromptTitle'), cls: 'wp-advanced-section-title' });
    const summarySetting = new Setting(summarySection);
    summarySetting.addTextArea(text => {
      text.setPlaceholder(this.plugin.t('defaultPrompt_summary'))
        .setValue(this.plugin.settings.summaryPrompt || '')
        .onChange(value => {
          (this.plugin.settings as SafeAny).summaryPrompt = value;
        });
      text.inputEl.rows = 6;
      text.inputEl.style.width = '100%';
      text.inputEl.style.minHeight = '120px';
      text.inputEl.style.fontFamily = 'var(--font-mono)';
      text.inputEl.style.fontSize = '12px';
      text.inputEl.style.lineHeight = '1.5';
    });

    // Tags prompt
    const tagsSection = card.createDiv('wp-advanced-section');
    tagsSection.createEl('h4', { text: this.plugin.t('publishModal_tagsPromptTitle'), cls: 'wp-advanced-section-title' });
    const tagsSetting = new Setting(tagsSection);
    tagsSetting.addTextArea(text => {
      text.setPlaceholder(this.plugin.t('defaultPrompt_tags'))
        .setValue(this.plugin.settings.tagsPrompt || '')
        .onChange(value => {
          (this.plugin.settings as SafeAny).tagsPrompt = value;
        });
      text.inputEl.rows = 6;
      text.inputEl.style.width = '100%';
      text.inputEl.style.minHeight = '120px';
      text.inputEl.style.fontFamily = 'var(--font-mono)';
      text.inputEl.style.fontSize = '12px';
      text.inputEl.style.lineHeight = '1.5';
    });

    // Image generation prompt
    const imageSection = card.createDiv('wp-advanced-section');
    imageSection.createEl('h4', { text: this.plugin.t('publishModal_imagePromptTitle'), cls: 'wp-advanced-section-title' });
    const imageSetting = new Setting(imageSection);
    imageSetting.addTextArea(text => {
      text.setPlaceholder(this.plugin.t('defaultPrompt_image'))
        .setValue(this.plugin.settings.imageGenerationPrompt || '')
        .onChange(value => {
          (this.plugin.settings as SafeAny).imageGenerationPrompt = value;
        });
      text.inputEl.rows = 6;
      text.inputEl.style.width = '100%';
      text.inputEl.style.minHeight = '120px';
      text.inputEl.style.fontFamily = 'var(--font-mono)';
      text.inputEl.style.fontSize = '12px';
      text.inputEl.style.lineHeight = '1.5';
    });

    // 保存设置按钮
    const saveSection = card.createDiv('wp-advanced-save');
    new Setting(saveSection)
      .addButton(btn => {
        btn.setButtonText(this.t('publishModal_saveSettings'))
          .setCta()
          .onClick(async () => {
            await this.plugin.saveSettings();
            new Notice(this.t('publishModal_settingsSaved'));
          });
      });
  }

  // ==================== Bottom Action Bar ====================
  private renderBottomBar(container: HTMLElement, params: WordPressPostParams): void {
    const bottomContainer = container.createDiv('wp-publish-bottom-bar');

    if (this.currentTab === 'preview') {
      const editBtn = bottomContainer.createEl('button', {
        text: this.isEditingPreview ? this.plugin.t('publishModal_saveButton') : this.plugin.t('publishModal_editButton'),
        cls: 'mod-cta'
      });
      editBtn.onclick = () => {
        if (this.isEditingPreview) {
          this.isEditingPreview = false;
          new Notice(this.t('publishModal_contentSaved'));
        } else {
          this.isEditingPreview = true;
        }
        this.display(params);
      };

      const summaryBtn = bottomContainer.createEl('button', { text: this.t('publishModal_generateSummary') });
      if (!this.aiService) {
        summaryBtn.addClass('disabled');
        summaryBtn.onclick = () => {
          new Notice(this.t('notice_aiConfigRequired'));
        };
      } else {
        summaryBtn.onclick = () => this.generateSummary(params);
      }

      const tagsBtn = bottomContainer.createEl('button', { text: this.t('publishModal_generateTags') });
      if (!this.aiService) {
        tagsBtn.addClass('disabled');
        tagsBtn.onclick = () => {
          new Notice(this.t('notice_aiConfigRequired'));
        };
      } else {
        tagsBtn.onclick = () => this.generateTags(params);
      }

      const publishBtn = bottomContainer.createEl('button', {
        text: this.t('publishModal_publishButton'),
        cls: 'mod-cta publish-btn'
      });
      this.publishBtn = publishBtn;
      publishBtn.onclick = () => this.doPublish(params, publishBtn);
    } else {
      const publishBtn = bottomContainer.createEl('button', {
        text: this.t('publishModal_publishButton'),
        cls: 'mod-cta publish-btn-full'
      });
      this.publishBtn = publishBtn;
      publishBtn.onclick = () => this.doPublish(params, publishBtn);
    }
  }

  private sanitizeContentForAI(content: string, maxLen: number = 2000): string {
    let cleaned = content
      .replace(/^---[\s\S]*?---\n?/m, '') // frontmatter
      .replace(/```[\s\S]*?```/g, '')     // code blocks
      .replace(/!\[.*?\]\(.*?\)/g, '')    // md images
      .replace(/!\[\[.*?\]\]/g, '')       // wiki images
      .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1') // md links -> text only
      .replace(/\[\[([^\]|]*)\|?([^\]]*)\]\]/g, '$2$1') // wiki links
      .replace(/#{1,6}\s*/g, '')          // headers
      .replace(/[*_~`]+/g, '')            // emphasis
      .replace(/\n{3,}/g, '\n\n')         // multiple newlines
      .trim();
    return cleaned.substring(0, maxLen);
  }

  private async generateSummary(params: WordPressPostParams): Promise<void> {
    if (!this.aiService) {
      new Notice(this.t('publishModal_aiServiceRequired'));
      return;
    }

    const contentToUse = this.editableContent || this.articleContent;
    if (!contentToUse) {
      new Notice(this.t('publishModal_emptyContentForTags'));
      return;
    }

    try {
      new Notice(this.t('publishModal_generatingSummary'));
      const cleanContent = this.sanitizeContentForAI(contentToUse, 2000);
      log.info('Generating summary from content length:', cleanContent.length);

      // 检测文章语言并适配提示词
      const language = detectLanguage(cleanContent);
      log.info('Detected language:', language);
      const basePrompt = this.summaryPrompt || this.plugin.t('defaultPrompt_summary');
      const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'summary');
      const prompt = localizedPrompt.replace('{content}', cleanContent);

      const summary = await this.aiService.generateText(prompt);
      params.excerpt = summary.trim();
      new Notice(this.t('publishModal_summaryGenerated', { summary: params.excerpt.substring(0, 50) }));
      this.display(params);
    } catch (error) {
      log.error('Generate summary error:', error);
      new Notice(this.t('publishModal_summaryGenerateFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
    }
  }

  private async generateTags(params: WordPressPostParams): Promise<void> {
    if (!this.aiService) {
      new Notice(this.t('notice_aiConfigRequired'));
      return;
    }

    const contentToUse = this.editableContent || this.articleContent;
    if (!contentToUse) {
      new Notice(this.t('publishModal_emptyContentForTags'));
      return;
    }

    try {
      new Notice(this.t('publishModal_generatingTags'));
      const cleanContent = this.sanitizeContentForAI(contentToUse, 2000);
      log.info('Generating tags from content length:', cleanContent.length);

      // 检测文章语言并适配提示词
      const language = detectLanguage(cleanContent);
      log.info('Detected language:', language);
      const basePrompt = this.tagsPrompt || this.plugin.t('defaultPrompt_tags');
      const localizedPrompt = getLocalizedPrompt(this.plugin, language, 'tags');
      const prompt = localizedPrompt.replace('{content}', cleanContent);

      const tags = await this.aiService.generateText(prompt);
      params.tags = tags.split(/[,，]/).map(t => t.trim()).filter(t => t).slice(0, 4);
      new Notice(this.t('publishModal_tagsGenerated', { tags: params.tags.join(', ') }));
      this.display(params);
    } catch (error) {
      log.error('Generate tags error:', error);
      new Notice(this.t('publishModal_tagsGenerateFailed', { error: error instanceof Error ? error.message : 'Unknown error' }));
    }
  }

  private doPublish(params: WordPressPostParams, btn?: HTMLButtonElement): void {
    // 防止重复点击
    if (this.isPublishing) {
      log.info('Already publishing, ignoring click');
      return;
    }

    this.isPublishing = true;
    // 保存参数以便重试
    this.lastPublishParams = params;

    // Pass edited content via params, NOT via frontmatter
    params.content = this.editableContent;

    // 隐藏模态窗口，显示全屏进度条
    this.modalEl.style.display = 'none';
    const progressOverlay = this.showPublishProgress();

    const doSubmit = () => {
      if (this.matterData.postType
        && this.matterData.postType !== PostTypeConst.Post
        && (this.matterData.tags || this.matterData.categories)
      ) {
        return openConfirmModal({
          message: this.t('publishModal_wrongMatterDataForPage')
        }, this.plugin)
          .then(result => {
            if (result.code === ConfirmCode.Confirm) {
              return this.onSubmit(params, fm => {
                delete fm.categories;
                delete fm.tags;
              }, this.featuredImage || undefined);
            }
            throw new Error('User cancelled');
          });
      } else {
        return new Promise<void>((resolve, reject) => {
          try {
            this.onSubmit(params, fm => {
              // Save excerpt and tags to frontmatter via callback
              if (params.excerpt) {
                fm.excerpt = params.excerpt;
              }
              if (params.tags && params.tags.length > 0) {
                // 保存为数组格式，统一 frontmatter 标签格式
                fm.tags = params.tags;
              }
            }, this.featuredImage || undefined);
            resolve();
          } catch (e) {
            reject(e);
          }
        });
      }
    };

    doSubmit()
      .then(() => {
        // 发布成功 - 移除进度条
        progressOverlay.remove();
        // 显示纸屑烟花特效
        this.showConfetti();
        // 显示成功提示
        this.showSuccessNotice();
      })
      .catch(err => {
        log.error('Publish error:', err);
        progressOverlay.remove();
        if (err instanceof Error && err.message !== 'User cancelled') {
          // 显示失败提示卡片
          this.showErrorCard(err.message);
        } else {
          this.close();
        }
        this.isPublishing = false;
      });
  }

  /**
   * 显示全屏发布进度条
   */
  private showPublishProgress(): HTMLElement {
    const overlay = document.body.createDiv('wp-publish-overlay');

    const container = overlay.createDiv('wp-publish-progress-container');

    // 进度动画
    const spinner = container.createDiv('wp-publish-spinner');
    spinner.createSpan({ cls: 'wp-spinner-cat' });

    // Progress text
    const text = container.createDiv('wp-publish-progress-text');
    text.textContent = this.plugin.t('publishModal_publishingProgress');

    // 进度条背景动画
    const progressBar = container.createDiv('wp-publish-progress-bar');
    progressBar.createDiv('wp-publish-progress-fill');

    return overlay;
  }

  /**
   * 显示发布成功提示
   */
  private showSuccessNotice(): void {
    new Notice(this.t('publishModal_publishSuccess'), 5000);
    // 延迟关闭窗口，让用户看到成功提示
    setTimeout(() => {
      this.close();
    }, 2000);
  }

  /**
   * 显示纸屑烟花特效
   */
  private showConfetti(): void {
    const container = document.body.createDiv('wp-confetti-container');

    // 创建多个彩色纸屑
    const colors = ['#ff6b6b', '#ffd93d', '#6bcb77', '#4d96ff', '#9c88ff', '#ff9ff3', '#54a0ff', '#5f27cd'];
    const confettiCount = 150;

    for (let i = 0; i < confettiCount; i++) {
      const confetti = container.createDiv('wp-confetti');
      const color = colors[Math.floor(Math.random() * colors.length)];
      const size = Math.random() * 10 + 5;
      const left = Math.random() * 100;
      const animDuration = Math.random() * 2 + 2;
      const animDelay = Math.random() * 0.5;

      confetti.style.cssText = `
        position: fixed;
        width: ${size}px;
        height: ${size}px;
        background: ${color};
        left: ${left}vw;
        top: -20px;
        opacity: 1;
        border-radius: ${Math.random() > 0.5 ? '50%' : '2px'};
        animation: confettiFall ${animDuration}s ease-out ${animDelay}s forwards;
        transform: rotate(${Math.random() * 360}deg);
        z-index: 10000;
        pointer-events: none;
      `;
    }

    // 动画结束后移除
    setTimeout(() => {
      container.remove();
    }, 4000);
  }

  /**
   * 显示发布失败提示卡片
   */
  private showErrorCard(errorMessage: string): void {
    const overlay = document.body.createDiv('wp-publish-overlay');
    const container = overlay.createDiv('wp-error-card');

    // 错误图标
    const icon = container.createDiv('wp-error-icon');
    icon.setText('😢');

    // 错误标题
    const title = container.createDiv('wp-error-title');
    title.setText(this.t('publishModal_publishFailedTitle'));

    // 错误详情
    const detail = container.createDiv('wp-error-detail');
    detail.setText(errorMessage);

    // 按钮区域
    const buttons = container.createDiv('wp-error-buttons');

    // 重试按钮
    const retryBtn = buttons.createEl('button', { cls: 'wp-error-retry-btn' });
    retryBtn.setText(this.t('publishModal_retryButton'));
    retryBtn.onclick = () => {
      overlay.remove();
      // 恢复模态窗口显示
      this.modalEl.style.display = '';
      // 重新发布
      if (this.lastPublishParams) {
        this.doPublish(this.lastPublishParams);
      }
    };

    // 关闭按钮
    const closeBtn = buttons.createEl('button', { cls: 'wp-error-close-btn' });
    closeBtn.setText(this.t('publishModal_closeButton'));
    closeBtn.onclick = () => {
      overlay.remove();
      this.close();
    };

    // 5秒后自动关闭
    setTimeout(() => {
      if (overlay.isConnected) {
        overlay.remove();
        this.close();
      }
    }, 8000);
  }

  private generateDefaultSlug(title: string, params?: WordPressPostParams): void {
    if (!title || !this.slugInput) return;

    try {
      if (this.plugin.settings.slugGenerationMode === 'ai-translate' && this.aiService) {
        this.aiService.translateToSlug(title).then(slug => {
          if (this.slugInput) {
            this.slugInput.value = slug;
            if (params) params.slug = slug;
          }
          this.slugGenerated = true;
        }).catch(() => {
          const fallbackSlug = SlugGenerator.autoGenerateSlug(title);
          if (this.slugInput) {
            this.slugInput.value = fallbackSlug;
            if (params) params.slug = fallbackSlug;
          }
          this.slugGenerated = true;
        });
      } else {
        const slug = SlugGenerator.autoGenerateSlug(title);
        if (this.slugInput) {
          this.slugInput.value = slug;
          if (params) params.slug = slug;
        }
        this.slugGenerated = true;
      }
    } catch (error) {
      log.error('Slug generation failed:', error);
    }
  }

  /**
   * Normalize tags from frontmatter to string array
   * Handles both YAML array format and comma-separated string format
   */
  private normalizeTags(tags: any): string[] {
    if (!tags) return [];

    // If it's already an array, return it
    if (Array.isArray(tags)) {
      return tags.map(t => String(t).trim()).filter(t => t);
    }

    // If it's a string, split by comma
    if (typeof tags === 'string') {
      return tags.split(/[,，]/).map(t => t.trim()).filter(t => t);
    }

    return [];
  }
}
