// Build a mock PublishModalContext for unit-testing the extracted section
// components. Every delegated action is a jest.fn() so tests can assert the
// wiring; shared state fields default to safe empty values and can be
// overridden per test.

import type { PublishModalContext } from '../../src/sections/publish-modal-context';
import type { FeaturedImageResult } from '../../src/featured-image-modal';
import type { UnsplashService } from '../../src/unsplash-service';
import type { AIService } from '../../src/ai-service';
import type { Term } from '../../src/wp-api';

export interface MockContextOptions {
  featuredImage?: FeaturedImageResult | null;
  autoFeaturedImage?: FeaturedImageResult | null;
  imageSource?: 'local' | 'unsplash' | 'ai' | 'vault' | 'cached' | 'auto';
  editableContent?: string;
  editableTags?: string[];
  matterData?: { featurePicture?: string; postId?: string | number };
  unsplashService?: UnsplashService | null;
  aiService?: AIService | null;
  categories?: { items: Term[]; selected: number[] };
  isLoadingRemoteImage?: boolean;
  remoteImageLoadFailed?: boolean;
  remoteImageError?: string | null;
  remoteImagePostId?: string | number | null;
  pluginSettings?: Record<string, unknown>;
}

export function createMockContext(opts: MockContextOptions = {}): PublishModalContext {
  const plugin = {
    // Return '' so the components exercise their `|| fallback` i18n branches.
    t: (_key: string) => '',
    settings: opts.pluginSettings ?? { autoGenerateSlug: false, aiConfig: {} },
  };

  const ctx: any = {
    plugin,
    featuredImage: opts.featuredImage ?? null,
    autoFeaturedImage: opts.autoFeaturedImage ?? null,
    imageSource: opts.imageSource ?? 'auto',
    editableContent: opts.editableContent ?? '# Hello\n\nsome **content**',
    editableTags: opts.editableTags ?? [],
    titleInput: null,
    slugInput: null,
    lastAutoGeneratedSlug: '',
    publishBtn: null,
    matterData: opts.matterData ?? { featurePicture: '', postId: undefined },
    unsplashService: opts.unsplashService ?? null,
    aiService: opts.aiService ?? null,
    categories: opts.categories ?? { items: [], selected: [] },
    isLoadingRemoteImage: opts.isLoadingRemoteImage ?? false,
    remoteImageLoadFailed: opts.remoteImageLoadFailed ?? false,
    remoteImageError: opts.remoteImageError ?? null,
    remoteImagePostId: opts.remoteImagePostId ?? null,

    display: jest.fn(),
    close: jest.fn(),
    selectLocalFile: jest.fn(),
    selectVaultImage: jest.fn(),
    selectUnsplashImage: jest.fn(),
    generateFeaturedImage: jest.fn(),
    loadRemoteFeaturedImage: jest.fn(),
    generateSummary: jest.fn(),
    generateTags: jest.fn(),
    generateDefaultSlug: jest.fn(),
    setupDateMask: jest.fn(),
    saveParamsToFrontmatter: jest.fn(),
    doPublish: jest.fn(),
  };

  return ctx as PublishModalContext;
}
