name: Release Obsidian plugin

on:
  push:
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"

permissions:
  contents: write

env:
  PLUGIN_NAME: obsidian-wordpresspublisher

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build plugin
        id: build
        run: |
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp output/main.js output/manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            output/main.js
            output/manifest.json
            styles.css
